import test from "node:test";
import assert from "node:assert/strict";
import { TargetRegistry, type TargetDefinition } from "../src/targets";
import { ForwardCloseReturnResolver, TripleBarrierResolver, type ExperienceRecord } from "../src/experience";
import { IntelligenceEngine } from "../src/intelligence";
import { DecisionEngine } from "../src/decision";
import { PredictiveModelBundle, type ModelArtifact } from "../src/ml";
import { TrustedAnalogueEngine, unsafeFitTrustedAnalogueScalerRaw, type TrustedAnalogueObservation } from "../src/analogues";
import { ExecutionCostModel } from "../src/costs";
import { assessEvidence } from "../src/evidence";
import { performanceMetrics } from "../src/metrics";
import { validateDatasetIntegrity, type DatasetObservation } from "../src/ml";
import { IntegratedPaperResearchEngine } from "../src/integrated-engine";
import { PaperBroker } from "../src/broker";
import { RiskManager } from "../src/risk";

const fitTrustedAnalogueScaler = unsafeFitTrustedAnalogueScalerRaw;

const ids = ["ret1", "ret5", "emaFastDistance", "emaSlowDistance", "rsi14Normalized", "realisedVol20", "volumeZ"] as const;
const artifact = (targetVersion: string): ModelArtifact => ({ artifactId: `a-${targetVersion}`, modelId: "model-1", modelVersion: "1", algorithm: "logistic-regression", featureVersion: "baseline-v1", featureSetVersion: "baseline-named-v1", featureIds: ids, targetVersion, scaler: { means: ids.map(() => 0), scales: ids.map(() => 1), fittedRows: 20 }, model: { weights: ids.map(() => 0), bias: 2 }, oodProfile: { featureSetVersion: "baseline-named-v1", featureIds: ids, means: ids.map(() => 0), scales: ids.map(() => 1), minimums: ids.map(() => -10), maximums: ids.map(() => 10) }, createdAt: 1 });
const bars = Array.from({ length: 20 }, (_, i) => ({ symbol: "SPY", startMs: i * 60_000, intervalMs: 60_000, open: 100 + i, high: 101 + i, low: 99 + i, close: 100 + i, volume: 100 }));
const registry = (definition: TargetDefinition) => { const value = new TargetRegistry(); value.register(definition); value.registerResolver(new ForwardCloseReturnResolver()); value.registerResolver(new TripleBarrierResolver()); return value; };
const analogue = (i: number, kind: "FORWARD_CLOSE_RETURN" | "TRIPLE_BARRIER", label: string): TrustedAnalogueObservation => ({ observationId: `o-${i}`, symbol: "SPY", featureTimestamp: i * 1_000, decisionTimestamp: i * 1_000, targetStartTimestamp: i * 1_000 + 1, targetEndTimestamp: i * 1_000 + 2, featureSetVersion: "baseline-named-v1", featureIds: ids, namedFeatures: Object.fromEntries(ids.map((id, index) => [id, index === 0 ? i / 10 : 0])), targetVersion: "triple-barrier-3-u1.5-d1-v1", targetKind: kind, targetLabel: label, forwardReturn: kind === "FORWARD_CLOSE_RETURN" ? (label === "LONG" ? 0.01 : -0.01) : undefined, regime: "UPTREND", sourceKind: "TRAIN_DATASET" });

test("target kind is derived from the registered target definition", () => {
  const target = { targetVersion: "triple-barrier-3-u1.5-d1-v1", kind: "TRIPLE_BARRIER" as const, horizonBars: 3, upperBarrierMultiple: 1.5, lowerBarrierMultiple: 1, ambiguityPolicy: "AMBIGUOUS" as const };
  const observations = [0, 1, 2, 3].map((i) => analogue(i, "TRIPLE_BARRIER", "UP")); const scaler = fitTrustedAnalogueScaler(observations, "baseline-named-v1", ids); const bundle = new PredictiveModelBundle(artifact(target.targetVersion)); const intelligence = new IntelligenceEngine({ model: bundle, targetRegistry: registry(target), trustedAnalogues: observations, analogueScalerProfile: scaler, minimumAnalogueSample: 1 }); let snapshot; for (const bar of bars) snapshot = intelligence.analyze(bar); assert.equal(snapshot?.analogues?.targetKind, "TRIPLE_BARRIER");
});

test("integrated triple-barrier predictions freeze ATR and resolve through the queue", () => { const target = { targetVersion: "triple-barrier-3-u1.5-d1-v1", kind: "TRIPLE_BARRIER" as const, horizonBars: 3, upperBarrierMultiple: 1.5, lowerBarrierMultiple: 1, ambiguityPolicy: "AMBIGUOUS" as const }; const targetRegistry = registry(target); const bundle = new PredictiveModelBundle(artifact(target.targetVersion)); const intelligence = new IntelligenceEngine({ model: bundle, targetRegistry }); const broker = new PaperBroker({ initialCash: 10_000, feeBps: 0, slippageBps: 0 }); const risk = new RiskManager({ maxPositionValue: 1_000, maxGrossExposure: 2_000, maxDailyLoss: 1_000, maxDrawdown: 1_000, maxOrdersPerMinute: 20, feeBps: 0 }); const saved: unknown[] = []; const repository = { append: (value: ExperienceRecord) => { saved.push(value); }, all: () => saved as ExperienceRecord[] }; const engine = new IntegratedPaperResearchEngine(intelligence, new DecisionEngine(), broker, risk, "test", "1", undefined, undefined, undefined, repository); for (const bar of [...bars, { ...bars[0], startMs: 20 * 60_000, open: 120, high: 120, low: 120, close: 120 }, { ...bars[0], startMs: 21 * 60_000, open: 121, high: 121, low: 121, close: 121 }, { ...bars[0], startMs: 22 * 60_000, open: 130, high: 132, low: 130, close: 131 }]) engine.onBar(bar, { symbol: "SPY", ts: bar.startMs + bar.intervalMs, bid: bar.close - .01, ask: bar.close + .01, last: bar.close }); const resolved = saved.find((value) => (value as { targetVersion?: string }).targetVersion === target.targetVersion) as { targetStateAtDecision?: { values: { atrAtDecision?: number } }; resolved?: { targetKind: string; entryPrice: number } } | undefined; assert.ok(resolved); assert.equal(resolved?.resolved?.targetKind, "TRIPLE_BARRIER"); assert.equal(resolved?.resolved?.entryPrice, 120); assert.equal(resolved?.targetStateAtDecision?.values.atrAtDecision, 2); });

test("unknown model target blocks trading and does not create a prediction", () => {
  const bundle = new PredictiveModelBundle(artifact("not-registered-v1")); const intelligence = new IntelligenceEngine({ model: bundle, targetRegistry: registry({ targetVersion: "known-v1", kind: "FORWARD_CLOSE_RETURN", horizonBars: 1 }) }); let snapshot; for (const bar of bars) snapshot = intelligence.analyze(bar); const decision = new DecisionEngine().decide(snapshot!); assert.equal(decision.action, "NO_TRADE"); assert.deepEqual(decision.reasonCodes, ["TARGET_MISMATCH"]); assert.equal(snapshot?.prediction, undefined);
});

test("trusted analogue normalization and target-specific rates are explicit", () => {
  const observations = [0, 1, 2, 3, 4].map((i) => analogue(i, "TRIPLE_BARRIER", ["UP", "UP", "UP", "DOWN", "TIMEOUT"][i])); const scaler = fitTrustedAnalogueScaler(observations, "baseline-named-v1", ids); const result = new TrustedAnalogueEngine().query(observations, { currentFeatures: observations[0].namedFeatures, decisionTimestamp: 10_000, featureSetVersion: "baseline-named-v1", featureIds: ids, targetVersion: "triple-barrier-3-u1.5-d1-v1", targetKind: "TRIPLE_BARRIER", scalerProfile: scaler, k: 5, minimumSample: 1 }); assert.equal(result.barrier?.upRate, 0.6); assert.equal(result.barrier?.downRate, 0.2); assert.equal(result.barrier?.timeoutRate, 0.2); assert.equal(result.distances[0], 0);
});

test("cost estimates use distinct entry and exit slippage and return units", () => { const model = new ExecutionCostModel({ spreadBps: 10, entrySlippageBps: 1, exitSlippageBps: 7, entryFeeBps: 2, exitFeeBps: 3 }); const estimate = model.estimateRoundTrip(100, 1_000); assert.ok(estimate.exitPrice < 100); assert.equal(estimate.currency / 1_000, estimate.returnUnits); assert.notEqual(estimate.entryPrice, estimate.exitPrice); });

test("evidence cannot claim passed reports without report provenance", () => { const noReports = assessEvidence({ sampleSize: 100, regimeConsistent: true }); assert.notEqual(noReports.quality, "VERY_STRONG"); const passed = { reportId: "r", status: "PASSED" as const }; const complete = assessEvidence({ sampleSize: 100, regimeConsistent: true, context: { outOfSampleReport: passed, calibrationReport: passed, costStressReport: passed, walkForwardReport: passed, parameterStabilityReport: passed, recentStabilityReport: passed } }); assert.equal(complete.provenance.outOfSampleReportId, "r"); });

test("timestamp gaps do not change declared-frequency risk metrics", () => { const points = [{ ts: 0, value: 100 }, { ts: 60_000, value: 101 }, { ts: 120_000, value: 100.5 }]; const shifted = points.map((point) => ({ ...point, ts: point.ts + (point.ts ? 10 * 86_400_000 : 0) })); const a = performanceMetrics(points, [], 100_000); const b = performanceMetrics(shifted, [], 100_000); assert.equal(a.annualisedVolatility, b.annualisedVolatility); assert.equal(a.sharpe, b.sharpe); });

test("trusted dataset observations require complete provenance", () => { const observation: DatasetObservation = { observationId: "o", symbol: "SPY", featureTimestamp: 1, decisionTimestamp: 2, targetStartTimestamp: 2, targetEndTimestamp: 3, plannedTargetEndTimestamp: 3, outcomeAvailableTimestamp: 3, featureSetVersion: "f", featureIds: ["x"], targetVersion: "t", targetKind: "FORWARD_CLOSE_RETURN", namedFeatures: { x: 1 }, rawTargetLabel: "LONG", label: 1, labelPolicy: { version: "lp1", description: "positive vs non-positive", targetVersion: "t", positiveClass: "LONG", negativeClass: "SHORT", includedRawLabels: ["LONG"], excludedRawLabels: ["SHORT", "FLAT"], probabilityMeaning: "P_UP_OUTCOME" }, split: "TRAIN" }; assert.equal(validateDatasetIntegrity([observation]).length, 1); assert.throws(() => validateDatasetIntegrity([{ ...observation, targetEndTimestamp: undefined as never }])); });
