import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalDatasetHash } from "../src/data";
import { exchangeCalendarSpec } from "../src/calendar";
import { runHistoricalPreflight } from "../src/historical-preflight";
import { suggestSplits } from "../src/historical-data";
import { ExperimentRunner, validateManifest } from "../src/experiment";
import { TwelveDataProvider, writeAcquisitionOutput } from "../src/data-acquisition";
import { verifyArtifactManifest } from "../src/serialization";

const bars = Array.from({ length: 6 * 30 }, (_, index) => ({ symbol: "TEST", startMs: Math.floor(index / 30) * 86_400_000 + (index % 30) * 60_000, intervalMs: 60_000, open: 100, high: 101, low: 99, close: 100, volume: 100 }));
const manifest = () => { const calendar = exchangeCalendarSpec({ timeZone: "UTC", sessionOpenHour: 0, sessionOpenMinute: 0, sessionCloseHour: 23, sessionCloseMinute: 59 }); return { datasetId: "test-dataset", datasetVersion: "1", origin: "SYNTHETIC_FIXTURE" as const, source: "test-fixture", licenceNotes: "synthetic", permittedForResearch: true, symbols: ["TEST"], barIntervalMs: 60_000, timezone: "UTC", startTimestamp: bars[0]!.startMs, endTimestamp: bars.at(-1)!.startMs + 60_000, adjustmentType: "RAW" as const, corporateActionStatus: "NONE_IN_RANGE" as const, expectedSession: "ALL", sessionCoveragePolicy: "PARTIAL_ALLOWED" as const, calendarId: calendar.calendarId, calendarSpecVersion: calendar.version, calendarSpecHash: calendar.contentHash, calendarHolidays: calendar.holidays, calendarEarlyCloses: calendar.earlyCloses, contentHash: canonicalDatasetHash(bars), canonicalizationVersion: "bars-canonical-json-v1" as const, createdAt: 0, dataQualitySummary: { totalRows: bars.length, acceptedRows: bars.length, rejectedRows: 0, duplicateRows: 0, invalidRows: 0, unexpectedGaps: 0, symbols: ["TEST"], issues: [] }, featureSetVersion: "baseline-ohlcv-v2", targetVersion: "triple-barrier-next-open-20-u1.5-d1-v1", labelPolicyVersion: "tb-up-vs-down-exclude-timeout-ambiguous-v1" }; };

test("shared historical preflight is strict and rejects spoofed origins", () => { const result = runHistoricalPreflight(manifest(), bars); assert.equal(result.passed, true); assert.deepEqual(validateManifest(manifest(), bars), result.dataQuality); const invalid = runHistoricalPreflight({ ...manifest(), origin: "REAL_DATA_I_PROMISE" as never }, bars); assert.equal(invalid.passed, false); assert.ok(invalid.blockingReasons.includes("DATASET_ORIGIN_VALID")); });
test("split suggestion uses session boundaries and reserves a tail", () => { const suggestion = suggestSplits(bars, manifest()); const session = (ts: number) => Math.floor(ts / (30 * 60_000)); assert.equal(session(suggestion.trainEnd), session(suggestion.trainEnd)); assert.ok(suggestion.outcomeTailBars > 0); assert.ok(suggestion.testDecisionEnd < suggestion.outcomeDataEnd); });
test("runtime reports measured feature parity and candidate stays candidate", () => { const report = new ExperimentRunner().syntheticSmoke("feature-parity-final"); assert.ok(report.featureParity); assert.ok(report.featureParity!.checkedCount > 0); assert.equal(report.featureParity!.mismatchCount, 0); assert.equal(report.modelLifecycle, "CANDIDATE"); });
test("mock read-only acquisition normalizes duplicates, ordering, and secrets", async () => { let calls = 0; const provider = new TwelveDataProvider("secret-key", async (url) => { calls++; assert.match(url, /time_series/); return new Response(JSON.stringify({ values: [{ datetime: "2024-01-01 00:01:00", open: "101", high: "102", low: "100", close: "101", volume: "2" }, { datetime: "2024-01-01 00:00:00", open: "100", high: "101", low: "99", close: "100", volume: "1" }, { datetime: "2024-01-01 00:00:00", open: "100", high: "101", low: "99", close: "100", volume: "1" }] }), { status: 200 }); }); const response = await provider.fetchBars({ symbol: "TEST", interval: "1m", start: "2024-01-01", end: "2024-01-01" }); assert.equal(calls, 1); assert.equal(response.bars.length, 2); assert.ok(response.bars[0]!.startMs < response.bars[1]!.startMs); assert.equal(JSON.stringify(response.metadata).includes("secret-key"), false); const directory = mkdtempSync(join(tmpdir(), "paper-acquisition-")); const path = join(directory, "bars.csv"); writeAcquisitionOutput(path, response); assert.equal(readFileSync(path, "utf8").includes("secret-key"), false); rmSync(directory, { recursive: true, force: true }); });
test("mock acquisition retries transient provider responses", async () => { let calls = 0; const provider = new TwelveDataProvider("secret-key", async () => { calls++; if (calls === 1) return new Response("busy", { status: 429 }); return new Response(JSON.stringify({ values: [{ datetime: "2024-01-01 00:00:00", open: "100", high: "101", low: "99", close: "100", volume: "1" }] }), { status: 200 }); }); const response = await provider.fetchBars({ symbol: "TEST", interval: "1m", start: "2024-01-01", end: "2024-01-01" }); assert.equal(calls, 2); assert.equal(response.bars.length, 1); });
test("artifact manifest verification detects tampering", () => { const directory = mkdtempSync(join(tmpdir(), "paper-artifacts-")); const artifact = join(directory, "result.json"); writeFileSync(artifact, "ok"); const manifest = { artifacts: [{ relativePath: "result.json", sizeBytes: 2, sha256: "bad" }] }; assert.equal(verifyArtifactManifest(directory, manifest).valid, false); rmSync(directory, { recursive: true, force: true }); });
