import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalDatasetHash } from "../src/data";
import { exchangeCalendarSpec } from "../src/calendar";
import { runHistoricalPreflight } from "../src/historical-preflight";
import { suggestSplits } from "../src/historical-data";
import { ExperimentRunner, measureFeatureParity, validateManifest } from "../src/experiment";
import { TwelveDataProvider, toTwelveDataInterval, writeAcquisitionOutput } from "../src/data-acquisition";
import { verifyArtifactManifest } from "../src/serialization";
import { DecisionEngine } from "../src/decision";
import { IntelligenceEngine } from "../src/intelligence";
import { IntegratedPaperResearchEngine, replayIntegrated } from "../src/integrated-engine";
import { PaperBroker } from "../src/broker";
import { RiskManager } from "../src/risk";
import { TradingCalendar } from "../src/calendar";

const bars = Array.from({ length: 6 * 30 }, (_, index) => ({ symbol: "TEST", startMs: Math.floor(index / 30) * 86_400_000 + (index % 30) * 60_000, intervalMs: 60_000, open: 100, high: 101, low: 99, close: 100, volume: 100 }));
const manifest = () => { const calendar = exchangeCalendarSpec({ timeZone: "UTC", sessionOpenHour: 0, sessionOpenMinute: 0, sessionCloseHour: 23, sessionCloseMinute: 59 }); return { datasetId: "test-dataset", datasetVersion: "1", origin: "SYNTHETIC_FIXTURE" as const, source: "test-fixture", licenceNotes: "synthetic", permittedForResearch: true, symbols: ["TEST"], barIntervalMs: 60_000, timezone: "UTC", startTimestamp: bars[0]!.startMs, endTimestamp: bars.at(-1)!.startMs + 60_000, adjustmentType: "RAW" as const, corporateActionStatus: "NONE_IN_RANGE" as const, expectedSession: "ALL", sessionCoveragePolicy: "PARTIAL_ALLOWED" as const, calendarId: calendar.calendarId, calendarSpecVersion: calendar.version, calendarSpecHash: calendar.contentHash, calendarHolidays: calendar.holidays, calendarEarlyCloses: calendar.earlyCloses, contentHash: canonicalDatasetHash(bars), canonicalizationVersion: "bars-canonical-json-v1" as const, createdAt: 0, dataQualitySummary: { totalRows: bars.length, acceptedRows: bars.length, rejectedRows: 0, duplicateRows: 0, invalidRows: 0, unexpectedGaps: 0, symbols: ["TEST"], issues: [] }, featureSetVersion: "baseline-ohlcv-v2", targetVersion: "triple-barrier-next-open-20-u1.5-d1-v1", labelPolicyVersion: "tb-up-vs-down-exclude-timeout-ambiguous-v1" }; };

test("shared historical preflight is strict and rejects spoofed origins", () => { const result = runHistoricalPreflight(manifest(), bars); assert.equal(result.passed, true); assert.deepEqual(validateManifest(manifest(), bars), result.dataQuality); const invalid = runHistoricalPreflight({ ...manifest(), origin: "REAL_DATA_I_PROMISE" as never }, bars); assert.equal(invalid.passed, false); assert.ok(invalid.blockingReasons.includes("DATASET_ORIGIN_VALID")); });
test("split suggestion uses distinct session boundaries and reserves a full tail", () => { const session = (ts: number) => Math.floor(ts / 86_400_000); const tenSessions = Array.from({ length: 10 * 30 }, (_, index) => ({ ...bars[index % bars.length]!, startMs: Math.floor(index / 30) * 86_400_000 + (index % 30) * 60_000 })); const suggestion = suggestSplits(tenSessions, manifest()); assert.notEqual(session(suggestion.trainEnd - 60_000), session(suggestion.validationEnd - 60_000)); assert.notEqual(session(suggestion.validationEnd - 60_000), session(suggestion.calibrationEnd - 60_000)); assert.notEqual(session(suggestion.calibrationEnd - 60_000), session(suggestion.testDecisionEnd)); assert.equal(suggestion.outcomeTailBars, 20); assert.equal(suggestion.perSymbolOutcomeTailBars.TEST, 20); assert.ok(suggestion.testDecisionEnd < suggestion.outcomeDataEnd); });
test("runtime reports measured feature parity and candidate stays candidate", () => { const report = new ExperimentRunner().syntheticSmoke("feature-parity-final"); assert.ok(report.featureParity); assert.ok(report.featureParity!.checkedCount > 0); assert.equal(report.featureParity!.mismatchCount, 0); assert.equal(report.modelLifecycle, "CANDIDATE"); });
test("mock read-only acquisition normalizes duplicates, ordering, and secrets", async () => { let calls = 0; const provider = new TwelveDataProvider("secret-key", async (url) => { calls++; assert.match(url, /time_series/); return new Response(JSON.stringify({ values: [{ datetime: "2024-01-01 00:01:00", open: "101", high: "102", low: "100", close: "101", volume: "2" }, { datetime: "2024-01-01 00:00:00", open: "100", high: "101", low: "99", close: "100", volume: "1" }, { datetime: "2024-01-01 00:00:00", open: "100", high: "101", low: "99", close: "100", volume: "1" }] }), { status: 200 }); }); const response = await provider.fetchBars({ symbol: "TEST", interval: "1m", start: "2024-01-01", end: "2024-01-01" }); assert.equal(calls, 1); assert.equal(response.bars.length, 2); assert.ok(response.bars[0]!.startMs < response.bars[1]!.startMs); assert.equal(response.metadata.rawResponseCount, 3); assert.equal(response.metadata.normalizedBarCount, 3); assert.equal(response.metadata.duplicateCount, 1); assert.equal(response.metadata.rejectedProviderRows, 0); assert.equal(JSON.stringify(response.metadata).includes("secret-key"), false); const directory = mkdtempSync(join(tmpdir(), "paper-acquisition-")); const path = join(directory, "bars.csv"); writeAcquisitionOutput(path, response); assert.equal(readFileSync(path, "utf8").includes("secret-key"), false); rmSync(directory, { recursive: true, force: true }); });
test("mock acquisition retries transient provider responses", async () => { let calls = 0; const provider = new TwelveDataProvider("secret-key", async () => { calls++; if (calls === 1) return new Response("busy", { status: 429 }); return new Response(JSON.stringify({ values: [{ datetime: "2024-01-01 00:00:00", open: "100", high: "101", low: "99", close: "100", volume: "1" }] }), { status: 200 }); }); const response = await provider.fetchBars({ symbol: "TEST", interval: "1m", start: "2024-01-01", end: "2024-01-01" }); assert.equal(calls, 2); assert.equal(response.bars.length, 1); });
test("Twelve Data interval mapping uses provider parameter semantics", () => {
  assert.equal(toTwelveDataInterval("1m"), "1min");
  assert.equal(toTwelveDataInterval("5m"), "5min");
  assert.equal(toTwelveDataInterval("15m"), "15min");
  assert.equal(toTwelveDataInterval("1h"), "1h");
  assert.equal(toTwelveDataInterval("1d"), "1day");
});
test("Twelve Data requests contain exact mapped intervals", async () => {
  const observed: string[] = [];
  const provider = new TwelveDataProvider("secret-key", async (url) => {
    observed.push(new URL(url).searchParams.get("interval") ?? "");
    return new Response(JSON.stringify({ values: [{ datetime: "2024-01-01 00:00:00", open: "100", high: "101", low: "99", close: "100", volume: "1" }] }), { status: 200 });
  });
  for (const interval of ["1m", "5m", "15m", "1h", "1d"] as const) await provider.fetchBars({ symbol: "TEST", interval, start: "2024-01-01", end: "2024-01-01" });
  assert.deepEqual(observed, ["1min", "5min", "15min", "1h", "1day"]);
});
test("provider truncation is detected and subdivided into auditable chunks", async () => {
  let calls = 0;
  const provider = new TwelveDataProvider("secret-key", async (url) => {
    calls++;
    const query = new URL(url).searchParams;
    const spanDays = (Date.parse(query.get("end_date")!) - Date.parse(query.get("start_date")!)) / 86_400_000 + 1;
    const values = spanDays > 1
      ? Array.from({ length: 5000 }, (_, index) => ({ datetime: `2024-01-${String((index % 3) + 1).padStart(2, "0")} 00:00:00`, open: "100", high: "101", low: "99", close: "100", volume: "1" }))
      : [{ datetime: `${query.get("start_date")} 00:00:00`, open: "100", high: "101", low: "99", close: "100", volume: "1" }];
    return new Response(JSON.stringify({ values }), { status: 200 });
  });
  const response = await provider.fetchBars({ symbol: "TEST", interval: "1m", start: "2024-01-01", end: "2024-01-03" });
  const chunks = response.metadata.chunks as { returnedCount: number; requestedStart: string; requestedEnd: string; subdivided: boolean }[];
  assert.ok(calls > 2);
  assert.ok(chunks.some((chunk) => chunk.returnedCount === 5000 && chunk.subdivided));
  assert.ok(chunks.every((chunk) => chunk.requestedStart && chunk.requestedEnd));
  assert.equal(response.metadata.rejectedProviderRows, 0);
});
test("invalid dates and provider bars fail closed", async () => {
  const provider = new TwelveDataProvider("secret-key", async () => new Response(JSON.stringify({ values: [{ datetime: "2024-01-01 00:00:00", open: "NaN", high: "101", low: "99", close: "100", volume: "1" }] }), { status: 200 }));
  await assert.rejects(() => provider.fetchBars({ symbol: "TEST", interval: "1m", start: "not-a-date", end: "2024-01-01" }), /INVALID_HISTORICAL_DATE_RANGE/);
  await assert.rejects(() => provider.fetchBars({ symbol: "TEST", interval: "1m", start: "2024-01-02", end: "2024-01-01" }), /INVALID_HISTORICAL_DATE_RANGE/);
  await assert.rejects(() => provider.fetchBars({ symbol: "TEST", interval: "1m", start: "2024-01-01", end: "2024-01-01" }), /TWELVE_DATA_INVALID_BAR/);
});
test("artifact manifest verification detects tampering", () => { const directory = mkdtempSync(join(tmpdir(), "paper-artifacts-")); const artifact = join(directory, "result.json"); writeFileSync(artifact, "ok"); const manifest = { artifacts: [{ relativePath: "result.json", sizeBytes: 2, sha256: "bad" }] }; assert.equal(verifyArtifactManifest(directory, manifest).valid, false); rmSync(directory, { recursive: true, force: true }); });
test("historical preflight rejects non-monotonic input and invalid origins", () => { const swapped = [bars[0]!, bars[2]!, bars[1]!, ...bars.slice(3)]; const nonMonotonic = runHistoricalPreflight(manifest(), swapped); assert.equal(nonMonotonic.passed, false); assert.ok(nonMonotonic.dataQuality.issues.some((issue) => issue.startsWith("NON_MONOTONIC"))); assert.ok(nonMonotonic.blockingReasons.includes("INPUT_ORDER_VALID")); const invalid = new ExperimentRunner().run({ manifest: { ...manifest(), origin: "REAL_DATA_I_PROMISE" as never }, config: { experimentId: "invalid-origin" } as never, bars }); assert.notEqual(invalid.status, "COMPLETED"); assert.equal(invalid.sourceDataKind, "UNKNOWN"); assert.equal(invalid.message, "INVALID_DATASET_ORIGIN"); });
test("atomic close marks are complete for every same-timestamp decision and survive symbol renaming", () => {
  const makeRun = (firstSymbol: string, secondSymbol: string) => { const broker = new PaperBroker({ initialCash: 100_000, feeBps: 0, slippageBps: 0 }); const engine = new IntegratedPaperResearchEngine(new IntelligenceEngine(), new DecisionEngine(), broker, new RiskManager({ maxPositionValue: 100_000, maxGrossExposure: 200_000, maxDailyLoss: 100_000, maxDrawdown: 100_000, maxOrdersPerMinute: 100, feeBps: 0 }), "test", "1", new TradingCalendar({ timeZone: "UTC", sessionOpenHour: 0, sessionOpenMinute: 0, sessionCloseHour: 23, sessionCloseMinute: 59 })); const observed = new Map<string, Readonly<Record<string, number>>>(); const original = engine.decisions.decide.bind(engine.decisions); engine.decisions.decide = (context: any) => { observed.set(context.analysis.symbol, { ...context.portfolio.marks }); return original(context); }; const start = 1_000_000; const event = (symbol: string, open: number, close: number) => ({ bar: { symbol, startMs: start, intervalMs: 60_000, open, high: Math.max(open, close), low: Math.min(open, close), close, volume: 1 }, quote: { symbol, ts: start + 60_000, bid: close, ask: close, last: close } }); engine.onBatch([event(firstSymbol, 100, 200), event(secondSymbol, 500, 600)]); return observed; };
  const first = makeRun("AAA", "BBB"); const renamed = makeRun("ZZZ", "AAA"); assert.deepEqual(first.get("AAA"), { AAA: 200, BBB: 600 }); assert.deepEqual(first.get("BBB"), { AAA: 200, BBB: 600 }); assert.deepEqual(renamed.get("ZZZ"), { AAA: 600, ZZZ: 200 }); assert.deepEqual(renamed.get("AAA"), { AAA: 600, ZZZ: 200 });
});
test("multi-symbol split suggestion reserves 20 eligible bars per symbol", () => { const multi = [...bars.map((bar) => ({ ...bar, symbol: "AAA" })), ...bars.map((bar) => ({ ...bar, symbol: "BBB" }))]; const suggestion = suggestSplits(multi, { ...manifest(), symbols: ["AAA", "BBB"] }); assert.equal(suggestion.outcomeTailBars, 20); assert.deepEqual(suggestion.perSymbolOutcomeTailBars, { AAA: 20, BBB: 20 }); assert.ok(suggestion.safeFinalDecisionTimestampBySymbol.AAA <= suggestion.testDecisionEnd); assert.ok(suggestion.safeFinalDecisionTimestampBySymbol.BBB <= suggestion.testDecisionEnd); });
test("feature parity fails when an expected runtime feature vector is missing", () => { const observation = { observationId: "missing", split: "TEST", namedFeatures: { ret1: 1 }, featureIds: ["ret1"], featureSetVersion: "baseline-ohlcv-v2" }; const parity = measureFeatureParity([observation] as never, []); assert.equal(parity.expectedComparableCount, 1); assert.equal(parity.checkedCount, 0); assert.equal(parity.missingRuntimeFeatureCount, 1); assert.deepEqual(parity.missingRuntimeFeatureObservationIds, ["missing"]); });
test("conflicting duplicate provider bars fail closed", async () => { const provider = new TwelveDataProvider("secret-key", async () => new Response(JSON.stringify({ values: [{ datetime: "2024-01-01 00:00:00", open: "100", high: "101", low: "99", close: "100", volume: "1" }, { datetime: "2024-01-01 00:00:00", open: "101", high: "102", low: "100", close: "101", volume: "1" }] }), { status: 200 })); await assert.rejects(() => provider.fetchBars({ symbol: "TEST", interval: "1m", start: "2024-01-01", end: "2024-01-01" }), /CONFLICTING_DUPLICATE_PROVIDER_BAR/); });
test("multi-symbol outcome-tail resolution preserves every result ID", () => { const broker = new PaperBroker({ initialCash: 100_000, feeBps: 0, slippageBps: 0 }); const engine = new IntegratedPaperResearchEngine(new IntelligenceEngine(), new DecisionEngine(), broker, new RiskManager({ maxPositionValue: 100_000, maxGrossExposure: 200_000, maxDailyLoss: 100_000, maxDrawdown: 100_000, maxOrdersPerMinute: 100, feeBps: 0 }), "tail-test", "1", new TradingCalendar({ timeZone: "UTC", sessionOpenHour: 0, sessionOpenMinute: 0, sessionCloseHour: 23, sessionCloseMinute: 59 })); const prediction = (symbol: string, id: string) => ({ predictionId: id, symbol, featureTimestamp: 0, decisionTimestamp: 0, targetVersion: "triple-barrier-1-u1-d1-v1", entryReferenceMethod: "NEXT_BAR_OPEN", modelId: "test", modelVersion: "1", featureSetVersion: "baseline-ohlcv-v2", featureIds: [], featureVersion: "baseline-ohlcv-v2", rawProbability: 0.5, calibratedProbability: 0.5, probability: 0.5, targetStateAtDecision: { status: "AVAILABLE", values: { atrAtDecision: 1 }, featureVersions: [] }, decision: "HOLD" }); engine.predictionQueue.enqueue(prediction("AAA", "prediction-AAA") as never); engine.predictionQueue.enqueue(prediction("BBB", "prediction-BBB") as never); const event = (symbol: string, price: number) => ({ bar: { symbol, startMs: 0, intervalMs: 60_000, open: price, high: price + 1, low: price - 1, close: price, volume: 1 }, quote: { symbol, ts: 60_000, bid: price, ask: price, last: price } }); const replay = replayIntegrated([event("AAA", 100), event("BBB", 500)], engine, { decisionWindowStart: 0, decisionWindowEnd: 30_000, outcomeDataEnd: 60_000 }); assert.deepEqual(new Set(replay.tailResolvedPredictionIds), new Set(["prediction-AAA", "prediction-BBB"])); assert.deepEqual(new Set((replay.resolvedExperiences ?? []).map((experience) => experience.predictionId)), new Set(["prediction-AAA", "prediction-BBB"])); });
