import test from "node:test";
import assert from "node:assert/strict";
import { TradingCalendar } from "../src/calendar";
import { resampleEquityCurveWithQuality } from "../src/metrics";
import { ExperimentRunner, validateManifest, FIRST_LABEL_POLICY, FIRST_TARGET, type DatasetManifest } from "../src/experiment";
import { assessEvidence } from "../src/evidence";
import { validateTrustedDatasetIntegrity, prepareTrustedDataset, type DatasetObservation, type LabelPolicy, validateTrustedModelArtifact, type ModelArtifact } from "../src/ml";
import { fitTrustedAnalogueScaler, TrustedAnalogueEngine, type TrustedAnalogueObservation } from "../src/analogues";
import { TripleBarrierResolver } from "../src/experience";

const policy: LabelPolicy = { version: "p", description: "UP versus DOWN", targetVersion: "t", positiveClass: "UP", negativeClass: "DOWN", includedRawLabels: ["UP", "DOWN"], excludedRawLabels: ["TIMEOUT", "AMBIGUOUS"], probabilityMeaning: "P_UP_GIVEN_UP_OR_DOWN" };
const observation = (id: string, split: DatasetObservation["split"], decisionTimestamp: number, outcomeAvailableTimestamp: number): DatasetObservation => ({ observationId: id, symbol: "SPY", featureTimestamp: decisionTimestamp, decisionTimestamp, targetStartTimestamp: decisionTimestamp, targetEndTimestamp: outcomeAvailableTimestamp, plannedTargetEndTimestamp: outcomeAvailableTimestamp, outcomeAvailableTimestamp, featureSetVersion: "f", featureIds: ["ret1"], targetVersion: "t", targetKind: "TRIPLE_BARRIER", namedFeatures: { ret1: 0 }, rawTargetLabel: "UP", label: 1, labelPolicy: policy, split });
const analogue = (id: string, sourceKind: TrustedAnalogueObservation["sourceKind"], decisionTimestamp: number, targetEndTimestamp: number): TrustedAnalogueObservation => ({ observationId: id, symbol: "SPY", featureTimestamp: decisionTimestamp, decisionTimestamp, targetStartTimestamp: decisionTimestamp, targetEndTimestamp, featureSetVersion: "f", featureIds: ["ret1"], namedFeatures: { ret1: 0 }, targetVersion: "t", targetKind: "TRIPLE_BARRIER", targetLabel: "UP", forwardReturn: .01, mfe: .01, mae: 0, regime: "RANGE", sourceKind });

test("session bounds are timezone-safe across EST and EDT", () => { const calendar = new TradingCalendar(); const january = calendar.sessionBounds(Date.parse("2026-01-15T15:00:00Z")); const july = calendar.sessionBounds(Date.parse("2026-07-15T14:00:00Z")); assert.equal(new Date(january.openMs).toISOString(), "2026-01-15T14:30:00.000Z"); assert.equal(new Date(july.openMs).toISOString(), "2026-07-15T13:30:00.000Z"); });
test("session resampling is anchored and gap policy changes validity", () => { const calendar = new TradingCalendar(); const open = calendar.sessionBounds(Date.parse("2026-01-15T15:00:00Z")).openMs; const points = [{ ts: open, value: 100 }, { ts: open + 2 * 3_600_000, value: 102 }]; const reject = resampleEquityCurveWithQuality(points, "1h", calendar, "REJECT_UNEXPECTED_GAP"); const fill = resampleEquityCurveWithQuality(points, "1h", calendar, "FORWARD_FILL_WITHIN_SESSION"); assert.equal(reject.points[0].ts, open); assert.equal(reject.quality.complete, false); assert.notEqual(reject.points.length, fill.points.length); });
test("missing expected evidence provenance cannot pass", () => { const result = assessEvidence({ sampleSize: 100, context: { modelId: "m", modelVersion: "1", experimentId: "e", outOfSampleReport: { reportId: "o", status: "PASSED", sampleSize: 100, modelId: "m", modelVersion: "1", experimentId: "e" } }, expectedProvenance: { modelId: "m", modelVersion: "1", experimentId: "different" }, required: { requireOutOfSample: true } }); assert.equal(result.gatesPassed, false); assert.notEqual(result.quality, "VERY_STRONG"); });
test("trusted split order and purge preserve future partitions", () => { assert.throws(() => validateTrustedDatasetIntegrity([observation("test", "TEST", 1, 2), observation("train", "TRAIN", 2, 2)])); assert.throws(() => validateTrustedDatasetIntegrity([observation("train-a", "TRAIN", 1, 2), observation("train-b", "TRAIN", 3, 4), observation("validation", "VALIDATION", 2, 2)])); const rows = validateTrustedDatasetIntegrity([observation("train", "TRAIN", 1, 10), observation("validation", "VALIDATION", 10, 11), observation("calibration", "CALIBRATION", 20, 21), observation("test", "TEST", 30, 31)], "PURGE_OVERLAP"); assert.deepEqual(rows.map((row) => row.observationId), ["validation", "calibration", "test"]); });
test("trusted analogue cutoffs and pool provenance are enforced", () => { assert.throws(() => fitTrustedAnalogueScaler({ role: "TRAIN", observations: [analogue("late", "TRAIN_DATASET", 1, 11)], featureTrainingStartTimestamp: 0, featureTrainingEndTimestamp: 10, trainingDecisionCutoff: 10, outcomeAvailabilityCutoff: 10, datasetId: "d", datasetVersion: "1", splitId: "TRAIN" }, "f", ["ret1"])); const scaler = fitTrustedAnalogueScaler({ role: "TRAIN", observations: [analogue("train", "TRAIN_DATASET", 1, 2)], featureTrainingStartTimestamp: 0, featureTrainingEndTimestamp: 10, trainingDecisionCutoff: 10, outcomeAvailabilityCutoff: 10, datasetId: "d", datasetVersion: "1", splitId: "TRAIN" }, "f", ["ret1"]); const result = new TrustedAnalogueEngine().query([analogue("historical-test", "TRAIN_DATASET", 20, 21), analogue("paper", "RESOLVED_PAPER_EXPERIENCE", 20, 21)], { currentFeatures: { ret1: 0 }, decisionTimestamp: 30, featureSetVersion: "f", featureIds: ["ret1"], targetVersion: "t", targetKind: "TRIPLE_BARRIER", scalerProfile: scaler, poolPolicy: "TRAIN_PLUS_RESOLVED_EXPERIENCE", k: 10, minimumSample: 1 }); assert.equal(result.sampleSize, 1); });
test("early barrier keeps the independently planned horizon", () => { const resolver = new TripleBarrierResolver(); const bars = Array.from({ length: 3 }, (_, index) => ({ symbol: "SPY", startMs: index * 60_000, intervalMs: 60_000, open: 100, high: index === 1 ? 102 : 100, low: 100, close: 100, volume: 1 })); const result = resolver.resolve({ targetVersion: "t", kind: "TRIPLE_BARRIER", horizonBars: 20, upperBarrierMultiple: 1, lowerBarrierMultiple: 1, ambiguityPolicy: "AMBIGUOUS" }, bars, 0, 1); assert.equal(result?.label, "UP"); assert.equal(result?.plannedTargetEndTimestamp, 20 * 60_000); assert.equal(result?.outcomeAvailableTimestamp, 2 * 60_000); });
test("trusted artifact provenance is mandatory", () => { const artifact: ModelArtifact = { artifactId: "a", modelId: "m", modelVersion: "1", algorithm: "logistic-regression", featureVersion: "v", featureSetVersion: "f", featureIds: ["ret1"], targetVersion: "t", scaler: { means: [0], scales: [1], fittedRows: 1 }, model: { weights: [1], bias: 0 }, oodProfile: { featureSetVersion: "f", featureIds: ["ret1"], means: [0], scales: [1], minimums: [-1], maximums: [1] }, createdAt: 1 }; assert.throws(() => validateTrustedModelArtifact(artifact)); });
test("synthetic smoke actually completes the offline pipeline", () => { const report = new ExperimentRunner().syntheticSmoke(); assert.equal(report.status, "COMPLETED"); assert.equal(report.dataKind, "SYNTHETIC"); assert.ok(report.sampleSizes.TRAIN > 0); assert.ok(report.test?.metrics); assert.ok(report.benchmarks); assert.ok(report.artifactManifest.artifacts.length > 0); assert.equal(report.integratedReplay?.status, "EXECUTED"); assert.equal(report.integratedReplay?.barCount > 0, true); assert.ok((report.integratedReplay?.actionCounts?.BUY ?? 0) > 0); assert.ok((report.integratedReplay?.actionCounts?.SELL ?? 0) > 0); assert.equal(report.integratedReplay?.warmupOrderCount, 0); assert.equal(report.integratedReplay?.testOrderCount, report.integratedReplay?.orderCount); assert.ok((report.integratedReplay?.estimatedSlippage ?? 0) > 0); assert.equal(report.test?.analogueCoverage, 1); assert.equal(report.test?.expectedValueAudit?.methodVersion, "binary-up-unit-payoff-minus-round-trip-cost-v1"); assert.equal(report.frozenRuntime?.targetVersion, FIRST_TARGET.targetVersion); assert.equal(report.frozenRuntime?.targetDefinition.entryReferenceMethod, "NEXT_BAR_OPEN"); assert.equal(report.frozenRuntime?.labelPolicyVersion, FIRST_LABEL_POLICY.version); assert.equal(report.frozenRuntime?.modelArtifactId, report.persistedArtifacts?.modelArtifact.artifactId); assert.equal(report.persistedArtifacts?.analogueDatabase?.length, 219); assert.equal(report.modelLifecycle, "CANDIDATE"); });
test("excluded target outcomes remain in analogue data but never become binary model rows", () => { const excluded = { ...observation("timeout", "TRAIN", 1, 2), rawTargetLabel: "TIMEOUT" as const, label: undefined, modelLabel: undefined }; const trusted = validateTrustedDatasetIntegrity([excluded]); const prepared = prepareTrustedDataset(trusted); assert.equal(prepared.observations.length, 1); assert.equal(prepared.rows.length, 0); });
test("manifest validation is chronological, calendar-aware and corporate-action safe", () => { const friday = Date.parse("2026-01-16T20:59:00Z"); const monday = Date.parse("2026-01-19T14:30:00Z"); const bars = [{ symbol: "SPY", startMs: monday, intervalMs: 60_000, open: 101, high: 102, low: 100, close: 101, volume: 10 }, { symbol: "SPY", startMs: friday, intervalMs: 60_000, open: 100, high: 101, low: 99, close: 100, volume: 10 }]; const base: DatasetManifest = { datasetId: "d", datasetVersion: "1", source: "fixture", licenceNotes: "fixture", permittedForResearch: true, symbols: ["SPY"], barIntervalMs: 60_000, timezone: "America/New_York", startTimestamp: friday, endTimestamp: monday + 60_000, adjustmentType: "RAW", corporateActionStatus: "NONE_IN_RANGE", assetClass: "EQUITY", expectedSession: "REGULAR", contentHash: "unused", createdAt: 0, dataQualitySummary: { totalRows: 2, acceptedRows: 2, rejectedRows: 0, duplicateRows: 0, invalidRows: 0, unexpectedGaps: 0, symbols: ["SPY"], issues: [] }, featureSetVersion: "f", targetVersion: "t", labelPolicyVersion: "p" }; const valid = validateManifest(base, bars); assert.equal(valid.unexpectedGaps, 0); assert.ok(valid.issues.includes("NON_MONOTONIC:SPY:" + friday)); const sameSessionGap = validateManifest(base, [{ ...bars[1], startMs: Date.parse("2026-01-16T15:00:00Z") }, { ...bars[1], startMs: Date.parse("2026-01-16T15:02:00Z") }]); assert.ok(sameSessionGap.issues.some((issue) => issue.startsWith("GAP:"))); const unsafe = validateManifest({ ...base, corporateActionStatus: "UNKNOWN" }, bars); assert.ok(unsafe.issues.includes("CORPORATE_ACTIONS_UNSAFE_OR_UNKNOWN")); });
test("analogue fixture preserves the four-way outcome distribution", () => { const labels = [...Array(30).fill("UP"), ...Array(20).fill("DOWN"), ...Array(40).fill("TIMEOUT"), ...Array(10).fill("AMBIGUOUS")]; const observations = labels.map((label, index) => ({ ...analogue(`fixture-${index}`, "TRAIN_DATASET", index + 1, index + 2), targetLabel: label })); const scaler = fitTrustedAnalogueScaler({ role: "TRAIN", observations, featureTrainingStartTimestamp: 0, featureTrainingEndTimestamp: 200, trainingDecisionCutoff: 200, outcomeAvailabilityCutoff: 200, datasetId: "fixture", datasetVersion: "1", splitId: "TRAIN" }, "f", ["ret1"]); const result = new TrustedAnalogueEngine().query(observations, { currentFeatures: { ret1: 0 }, decisionTimestamp: 200, featureSetVersion: "f", featureIds: ["ret1"], targetVersion: "t", targetKind: "TRIPLE_BARRIER", scalerProfile: scaler, k: 100, minimumSample: 1 }); assert.equal(result.sampleSize, 100); assert.deepEqual(result.barrier && { up: result.barrier.upCount, down: result.barrier.downCount, timeout: result.barrier.timeoutCount, ambiguous: result.barrier.ambiguousCount }, { up: 30, down: 20, timeout: 40, ambiguous: 10 }); });
