import { median, quantile } from "./statistics";
import type { ScalerState } from "./ml";
import type { FeatureId, NamedFeatureVector } from "./feature-schema";
import type { TargetKind } from "./targets";
export interface TrustedAnalogueObservation { observationId: string; symbol: string; featureTimestamp: number; decisionTimestamp: number; targetStartTimestamp: number; targetEndTimestamp: number; featureSetVersion: string; featureIds: readonly FeatureId[]; namedFeatures: NamedFeatureVector; targetVersion: string; targetKind: TargetKind; targetLabel: string; forwardReturn?: number; mfe?: number; mae?: number; regime: string; }
export interface TargetSpecificAnalogueResult { targetKind: TargetKind; sampleSize: number; forwardReturn?: { mean: number; median: number; positiveRate: number }; barrier?: Readonly<Record<"UP" | "DOWN" | "TIMEOUT" | "AMBIGUOUS", number>>; }
export function validateTrustedAnalogue(observation: TrustedAnalogueObservation, expectedFeatureSetVersion?: string, expectedFeatureIds?: readonly FeatureId[], expectedTargetVersion?: string): void { if (!observation.observationId || !observation.symbol || !Number.isFinite(observation.featureTimestamp) || !Number.isFinite(observation.decisionTimestamp) || !Number.isFinite(observation.targetStartTimestamp) || !Number.isFinite(observation.targetEndTimestamp) || observation.featureTimestamp > observation.decisionTimestamp || observation.targetStartTimestamp < observation.decisionTimestamp || observation.targetEndTimestamp <= observation.targetStartTimestamp) throw new Error("Trusted analogue timestamps are invalid"); if (expectedFeatureSetVersion && observation.featureSetVersion !== expectedFeatureSetVersion) throw new Error("Analogue feature-set version mismatch"); if (expectedFeatureIds && (observation.featureIds.length !== expectedFeatureIds.length || observation.featureIds.some((id, index) => id !== expectedFeatureIds[index]))) throw new Error("Analogue feature IDs mismatch"); if (expectedTargetVersion && observation.targetVersion !== expectedTargetVersion) throw new Error("Analogue target version mismatch"); if (observation.targetKind === "FORWARD_CLOSE_RETURN" && (observation.targetLabel !== "LONG" && observation.targetLabel !== "SHORT" && observation.targetLabel !== "FLAT" || !Number.isFinite(observation.forwardReturn))) throw new Error("Forward analogue label is invalid"); if (observation.targetKind === "TRIPLE_BARRIER" && !["UP", "DOWN", "TIMEOUT", "AMBIGUOUS"].includes(observation.targetLabel)) throw new Error("Barrier analogue label is invalid"); if (new Set(observation.featureIds).size !== observation.featureIds.length || observation.featureIds.some((id) => !(id in observation.namedFeatures) || !Number.isFinite(observation.namedFeatures[id]))) throw new Error("Analogue feature schema is invalid"); }

export interface TrustedAnalogueQuery { currentFeatures: NamedFeatureVector; decisionTimestamp: number; featureSetVersion: string; featureIds: readonly FeatureId[]; targetVersion: string; targetKind: TargetKind; regime?: string; k?: number; minimumSample?: number; }
export class TrustedAnalogueEngine {
  query(observations: readonly TrustedAnalogueObservation[], query: TrustedAnalogueQuery): TargetSpecificAnalogueResult & { distances: readonly number[]; evidence: "INSUFFICIENT" | "SUFFICIENT" } {
    const eligible = observations.filter((observation) => { try { validateTrustedAnalogue(observation, query.featureSetVersion, query.featureIds, query.targetVersion); } catch { return false; } return observation.targetKind === query.targetKind && observation.targetEndTimestamp <= query.decisionTimestamp && (!query.regime || observation.regime === query.regime); });
    const ranked = eligible.map((observation) => ({ observation, distance: Math.sqrt(query.featureIds.reduce((sum, id) => sum + (observation.namedFeatures[id] - query.currentFeatures[id]) ** 2, 0)) })).sort((a, b) => a.distance - b.distance).slice(0, query.k ?? 50);
    const result = summarizeTrustedAnalogues(ranked.map(({ observation }) => observation), query.targetKind); return { ...result, distances: ranked.map(({ distance }) => distance), evidence: ranked.length >= (query.minimumSample ?? 20) ? "SUFFICIENT" : "INSUFFICIENT" };
  }
}
export function summarizeTrustedAnalogues(observations: readonly TrustedAnalogueObservation[], targetKind: TargetKind): TargetSpecificAnalogueResult { const selected = observations.filter((observation) => observation.targetKind === targetKind); if (targetKind === "TRIPLE_BARRIER") { const counts = { UP: 0, DOWN: 0, TIMEOUT: 0, AMBIGUOUS: 0 }; for (const observation of selected) if (observation.targetLabel in counts) counts[observation.targetLabel as keyof typeof counts]++; return { targetKind, sampleSize: selected.length, barrier: counts }; } const returns = selected.map((observation) => observation.forwardReturn).filter((value): value is number => value !== undefined); const ordered = [...returns].sort((a, b) => a - b); return { targetKind, sampleSize: selected.length, forwardReturn: { mean: returns.length ? returns.reduce((a, b) => a + b, 0) / returns.length : Number.NaN, median: ordered.length ? ordered[Math.floor(ordered.length / 2)] : Number.NaN, positiveRate: returns.length ? returns.filter((value) => value > 0).length / returns.length : Number.NaN } }; }
export interface AnalogueObservation { features: readonly number[]; featureVersion?: string; targetVersion?: string; forwardReturn: number; decisionTimestamp?: number; targetEndTimestamp?: number; symbol?: string; regime?: string; mfe?: number; mae?: number; }
export interface AnalogueResult { sampleSize: number; meanForwardReturn: number; medianForwardReturn: number; quantiles: Readonly<{ p10: number; p25: number; p75: number; p90: number }>; positiveRate: number; meanMfe?: number; meanMae?: number; regimeDistribution: Readonly<Record<string, number>>; distances: readonly number[]; evidence: "INSUFFICIENT" | "SUFFICIENT"; }
export interface AnalogueQuery { asOfTimestamp?: number; scaler?: ScalerState; requiredRegime?: string; featureVersion?: string; targetVersion?: string; }
const emptyResult = (): AnalogueResult => ({ sampleSize: 0, meanForwardReturn: Number.NaN, medianForwardReturn: Number.NaN, quantiles: { p10: Number.NaN, p25: Number.NaN, p75: Number.NaN, p90: Number.NaN }, positiveRate: Number.NaN, regimeDistribution: {}, distances: [], evidence: "INSUFFICIENT" });
export function nearestAnalogues(current: readonly number[], observations: readonly AnalogueObservation[], k = 50, minimumSample = 20, query: AnalogueQuery = {}): AnalogueResult { const eligible = observations.filter((observation) => { if (query.asOfTimestamp !== undefined && (observation.decisionTimestamp === undefined || observation.targetEndTimestamp === undefined || observation.decisionTimestamp >= query.asOfTimestamp || observation.targetEndTimestamp >= query.asOfTimestamp)) return false; if (query.requiredRegime !== undefined && observation.regime !== query.requiredRegime) return false; if (query.featureVersion !== undefined && observation.featureVersion !== query.featureVersion) return false; if (query.targetVersion !== undefined && observation.targetVersion !== query.targetVersion) return false; return true; }); if (!eligible.length || eligible.some((observation) => observation.features.length !== current.length || observation.features.some((value) => !Number.isFinite(value)))) return emptyResult(); const scale = (row: readonly number[]) => query.scaler ? row.map((value, index) => (value - query.scaler!.means[index]) / (query.scaler!.scales[index] || 1)) : [...row]; const scaledCurrent = scale(current); const ranked = eligible.map((observation) => ({ observation, distance: Math.sqrt(scale(observation.features).reduce((sum, value, index) => sum + (value - scaledCurrent[index]) ** 2, 0)) })).sort((a, b) => a.distance - b.distance).slice(0, Math.max(1, k)); const returns = ranked.map(({ observation }) => observation.forwardReturn); const regimes: Record<string, number> = {}; ranked.forEach(({ observation }) => { if (observation.regime) regimes[observation.regime] = (regimes[observation.regime] ?? 0) + 1; }); const mean = returns.reduce((sum, value) => sum + value, 0) / returns.length; const mfe = ranked.map(({ observation }) => observation.mfe).filter((value): value is number => value !== undefined); const mae = ranked.map(({ observation }) => observation.mae).filter((value): value is number => value !== undefined); return { sampleSize: ranked.length, meanForwardReturn: mean, medianForwardReturn: median(returns), quantiles: { p10: quantile(returns, 0.1), p25: quantile(returns, 0.25), p75: quantile(returns, 0.75), p90: quantile(returns, 0.9) }, positiveRate: returns.filter((value) => value > 0).length / returns.length, meanMfe: mfe.length ? mfe.reduce((sum, value) => sum + value, 0) / mfe.length : undefined, meanMae: mae.length ? mae.reduce((sum, value) => sum + value, 0) / mae.length : undefined, regimeDistribution: Object.fromEntries(Object.entries(regimes).map(([key, value]) => [key, value / ranked.length])), distances: ranked.map(({ distance }) => distance), evidence: ranked.length >= minimumSample ? "SUFFICIENT" : "INSUFFICIENT" }; }
