export interface TradingCalendarConfig { timeZone?: string; sessionOpenHour?: number; sessionOpenMinute?: number; sessionCloseHour?: number; sessionCloseMinute?: number; holidays?: readonly string[]; earlyCloses?: Readonly<Record<string, number>>; }
export interface ExchangeCalendarSpec { calendarId: string; version: string; exchange: string; timeZone: string; regularOpen: string; regularClose: string; holidays: readonly string[]; earlyCloses: Readonly<Record<string, number>>; contentHash: string; config: TradingCalendarConfig; }
export interface HolidayProvider { isHoliday(sessionKey: string): boolean; earlyCloseMinutes(sessionKey: string): number | null; }
export class ConfiguredHolidayProvider implements HolidayProvider { constructor(private readonly holidays: readonly string[] = [], private readonly earlyCloses: Readonly<Record<string, number>> = {}) {} isHoliday(sessionKey: string) { return this.holidays.includes(sessionKey); } earlyCloseMinutes(sessionKey: string) { return this.earlyCloses[sessionKey] ?? null; } }
export class TradingCalendar {
  private readonly config: Required<Omit<TradingCalendarConfig, "holidays" | "earlyCloses">>; private readonly holidayProvider: HolidayProvider;
  constructor(config: TradingCalendarConfig = {}, holidayProvider?: HolidayProvider) { this.config = { timeZone: "America/New_York", sessionOpenHour: 9, sessionOpenMinute: 30, sessionCloseHour: 16, sessionCloseMinute: 0, ...config }; this.holidayProvider = holidayProvider ?? new ConfiguredHolidayProvider(config.holidays, config.earlyCloses); }
  sessionKey(timestamp: number): string { const map = this.localParts(timestamp); return `${String(map.year).padStart(4, "0")}-${String(map.month).padStart(2, "0")}-${String(map.day).padStart(2, "0")}`; }
  isTradingDay(timestamp: number): boolean { const key = this.sessionKey(timestamp); const weekday = new Intl.DateTimeFormat("en-US", { timeZone: this.config.timeZone, weekday: "short" }).format(new Date(timestamp)); return weekday !== "Sat" && weekday !== "Sun" && !this.holidayProvider.isHoliday(key); }
  isRegularSession(timestamp: number): boolean { if (!this.isTradingDay(timestamp)) return false; const map = this.localParts(timestamp); const minutes = map.hour * 60 + map.minute; return minutes >= this.sessionOpenMinutes() && minutes < this.sessionCloseMinutes(this.sessionKey(timestamp)); }
  sessionOpen(_timestamp: number) { return this.sessionOpenMinutes(); }
  sessionClose(timestamp: number) { return this.sessionCloseMinutes(this.sessionKey(timestamp)); }
  sessionBounds(timestamp: number): { openMs: number; closeMs: number; sessionKey: string } { const key = this.sessionKey(timestamp); return { openMs: this.exchangeLocalToUtc(key, this.sessionOpenMinutes()), closeMs: this.exchangeLocalToUtc(key, this.sessionCloseMinutes(key)), sessionKey: key }; }
  private exchangeLocalToUtc(key: string, minutes: number): number { const [year, month, day] = key.split("-").map(Number); const desired = Date.UTC(year, month - 1, day, Math.floor(minutes / 60), minutes % 60); const local = this.localParts(desired); const represented = Date.UTC(local.year, local.month - 1, local.day, local.hour, local.minute, local.second); const offset = desired - represented; return desired + offset; }
  private sessionOpenMinutes() { return this.config.sessionOpenHour * 60 + this.config.sessionOpenMinute; }
  private sessionCloseMinutes(key: string) { return this.holidayProvider.earlyCloseMinutes(key) ?? this.config.sessionCloseHour * 60 + this.config.sessionCloseMinute; }
  private localParts(timestamp: number) { const parts = new Intl.DateTimeFormat("en-US", { timeZone: this.config.timeZone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).formatToParts(timestamp); const values = Object.fromEntries(parts.filter((part) => part.type !== "literal").map((part) => [part.type, Number(part.value)])); return { year: values.year, month: values.month, day: values.day, hour: values.hour === 24 ? 0 : values.hour, minute: values.minute, second: values.second }; }
}

import { createHash } from "node:crypto";
export function exchangeCalendarSpec(config: TradingCalendarConfig = {}): ExchangeCalendarSpec { const timeZone = config.timeZone ?? "America/New_York"; const openHour = config.sessionOpenHour ?? 9; const openMinute = config.sessionOpenMinute ?? 30; const closeHour = config.sessionCloseHour ?? 16; const closeMinute = config.sessionCloseMinute ?? 0; const allSession = openHour === 0 && openMinute === 0 && closeHour === 23 && closeMinute === 59; const open = `${String(openHour).padStart(2, "0")}:${String(openMinute).padStart(2, "0")}`; const close = `${String(closeHour).padStart(2, "0")}:${String(closeMinute).padStart(2, "0")}`; const holidays = [...(config.holidays ?? [])].sort(); const earlyCloses = Object.fromEntries(Object.entries(config.earlyCloses ?? {}).sort()); const body = { calendarId: allSession ? "SYNTHETIC_ALL_SESSION" : "US_EQUITIES_RTH", version: allSession ? "synthetic-calendar-spec-v1" : "exchange-calendar-spec-v2", exchange: allSession ? "SYNTHETIC" : "US_EQUITIES", timeZone, regularOpen: open, regularClose: close, holidays, earlyCloses }; return { ...body, contentHash: createHash("sha256").update(JSON.stringify(body)).digest("hex"), config: structuredClone({ ...config, timeZone, sessionOpenHour: openHour, sessionOpenMinute: openMinute, sessionCloseHour: closeHour, sessionCloseMinute: closeMinute, holidays, earlyCloses }) }; }
export function calendarProvenanceMatches(manifest: { calendarId?: string; calendarSpecVersion?: string; calendarSpecHash?: string }, config: TradingCalendarConfig): boolean { const spec = exchangeCalendarSpec(config); return manifest.calendarId === spec.calendarId && manifest.calendarSpecVersion === spec.version && manifest.calendarSpecHash === spec.contentHash; }
