import type { ClosedTrade } from "./domain";
import { performanceMetrics, type PerformanceMetrics } from "./metrics";

export interface ConditionalTradeStatistics { label: string; sampleCount: number; winRate: number; expectancy: number; profitFactor: number; averageWinner: number; averageLoser: number; payoffRatio: number; meanReturn: number; medianReturn: number; returnStd: number; meanMfe: number; meanMae: number; totalNetPnl: number; }
export function conditionalTradeStatistics(trades: readonly ClosedTrade[], labelOf: (trade: ClosedTrade) => string | undefined): readonly ConditionalTradeStatistics[] { const groups = new Map<string, ClosedTrade[]>(); for (const trade of trades) { const label = labelOf(trade); if (label) groups.set(label, [...(groups.get(label) ?? []), trade]); } return [...groups.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([label, group]) => { const returns = group.map((trade) => trade.entryPrice > 0 && trade.quantity > 0 ? trade.netPnl / (trade.entryPrice * trade.quantity) : 0); const wins = group.filter((trade) => trade.netPnl > 0).map((trade) => trade.netPnl); const losses = group.filter((trade) => trade.netPnl < 0).map((trade) => trade.netPnl); const average = (values: readonly number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0; const sorted = [...returns].sort((a, b) => a - b); const mean = average(returns); const median = sorted.length ? sorted.length % 2 ? sorted[(sorted.length - 1) / 2] : (sorted[sorted.length / 2 - 1] + sorted[sorted.length / 2]) / 2 : 0; return { label, sampleCount: group.length, winRate: wins.length / group.length, expectancy: average(group.map((trade) => trade.netPnl)), profitFactor: Math.abs(losses.reduce((a, b) => a + b, 0)) ? wins.reduce((a, b) => a + b, 0) / Math.abs(losses.reduce((a, b) => a + b, 0)) : wins.length ? Infinity : 0, averageWinner: average(wins), averageLoser: average(losses), payoffRatio: average(losses) ? average(wins) / Math.abs(average(losses)) : 0, meanReturn: mean, medianReturn: median, returnStd: returns.length > 1 ? Math.sqrt(returns.reduce((sum, value) => sum + (value - mean) ** 2, 0) / (returns.length - 1)) : 0, meanMfe: average(group.map((trade) => trade.mfePerShare ?? 0)), meanMae: average(group.map((trade) => trade.maePerShare ?? 0)), totalNetPnl: group.reduce((sum, trade) => sum + trade.netPnl, 0) }; }); }
export interface ConditionalPerformance { label: string; sampleCount: number; metrics: PerformanceMetrics; }
export function performanceByLabel(trades: readonly ClosedTrade[], labelOf: (trade: ClosedTrade) => string | undefined, periodsPerYear = 252): readonly ConditionalPerformance[] {
  const groups = new Map<string, ClosedTrade[]>(); for (const trade of trades) { const label = labelOf(trade); if (!label) continue; const group = groups.get(label) ?? []; group.push(trade); groups.set(label, group); }
  return [...groups.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([label, group]) => { const ordered = [...group].sort((a, b) => a.exitTimestamp - b.exitTimestamp); const returns = ordered.map((trade) => trade.entryPrice > 0 && trade.quantity > 0 ? trade.netPnl / (trade.entryPrice * trade.quantity) : 0); const equity = ordered.reduce<{ ts: number; value: number }[]>((values, trade, index) => [...values, { ts: trade.exitTimestamp, value: values.at(-1)!.value * (1 + returns[index]) }], [{ ts: ordered[0].entryTimestamp, value: 100_000 }]); return { label, sampleCount: group.length, metrics: performanceMetrics(equity, returns, periodsPerYear) }; });
}
