import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { loadBarsFile, suggestSplits } from "./historical-data";
import { BAR_CANONICALIZATION_VERSION, canonicalDatasetHash } from "./data";
import { validateManifest, type DatasetManifest } from "./experiment";
import { FIRST_LABEL_POLICY, FIRST_TARGET, FEATURE_SET_VERSION } from "./experiment";
const args = process.argv.slice(2); const value = (flag: string) => { const index = args.indexOf(flag); return index >= 0 ? args[index + 1] : undefined; }; const command = args[0];
const fail = (message: string, code = 1): never => { console.error(message); process.exit(code); };
const data = value("--data"); const output = value("--output") ?? value("--out"); const symbols = (value("--symbols") ?? value("--symbol") ?? "").split(",").map((s) => s.trim()).filter(Boolean); const intervalMs = Number(value("--interval") ?? 60_000);
if (!data) fail("--data FILE is required", 2);
try {
  const bars = loadBarsFile(data!, { intervalMs, symbols });
  if (command === "manifest:init") { const manifest: DatasetManifest = { datasetId: "REPLACE_DATASET_ID", datasetVersion: "1", origin: "EXTERNAL_HISTORICAL_FILE", source: "", licenceNotes: "", permittedForResearch: false, symbols: symbols.length ? symbols : [...new Set(bars.map((bar) => bar.symbol))].sort(), barIntervalMs: intervalMs, timezone: value("--timezone") ?? "UTC", startTimestamp: Math.min(...bars.map((bar) => bar.startMs)), endTimestamp: Math.max(...bars.map((bar) => bar.startMs + bar.intervalMs)), adjustmentType: "RAW", corporateActionStatus: "UNKNOWN", assetClass: "EQUITY", expectedSession: value("--expected-session") ?? "ALL", sessionCoveragePolicy: "PARTIAL_ALLOWED", contentHash: canonicalDatasetHash(bars), canonicalizationVersion: BAR_CANONICALIZATION_VERSION, createdAt: Date.now(), dataQualitySummary: { totalRows: bars.length, acceptedRows: bars.length, rejectedRows: 0, duplicateRows: 0, invalidRows: 0, unexpectedGaps: 0, symbols: [...new Set(bars.map((bar) => bar.symbol))].sort(), issues: [] }, featureSetVersion: FEATURE_SET_VERSION, targetVersion: FIRST_TARGET.targetVersion, labelPolicyVersion: FIRST_LABEL_POLICY.version }; if (output) writeFileSync(output, JSON.stringify(manifest, null, 2)); console.log(JSON.stringify(manifest, null, 2)); }
  else if (command === "validate-data") { const manifestPath = value("--manifest"); if (!manifestPath || !existsSync(manifestPath)) fail("--manifest FILE is required", 2); const manifest = JSON.parse(readFileSync(manifestPath!, "utf8")) as DatasetManifest; const quality = validateManifest(manifest, bars); const actualHash = canonicalDatasetHash(bars); const summary = { valid: quality.issues.length === 0 && actualHash === manifest.contentHash && manifest.canonicalizationVersion === BAR_CANONICALIZATION_VERSION && Boolean(manifest.origin), origin: manifest.origin, rowCount: bars.length, symbols: quality.symbols, canonicalizationVersion: BAR_CANONICALIZATION_VERSION, canonicalHash: actualHash, manifestHash: manifest.contentHash, quality, suggestedSplits: args.includes("--suggest-splits") ? suggestSplits(bars) : undefined }; if (output) writeFileSync(output, JSON.stringify(summary, null, 2)); console.log(JSON.stringify(summary, null, 2)); if (!summary.valid) process.exitCode = 1; }
  else fail("Usage: manifest:init or validate-data", 2);
} catch (error) { fail(error instanceof Error ? error.message : String(error)); }
