import { writeFileSync } from "node:fs";
import { parseTimestampStrict } from "./data";
import type { Bar } from "./domain";

export type HistoricalInterval = "1m" | "5m" | "15m" | "1h" | "1d";
export interface HistoricalBarsRequest { symbol: string; interval: HistoricalInterval; start: string; end: string; regularSessionOnly?: boolean; }
export interface HistoricalBarsResponse { bars: readonly Bar[]; provider: string; requested: HistoricalBarsRequest; rawResponseCount: number; metadata: Record<string, unknown>; }
export interface HistoricalDataProvider { providerId: string; fetchBars(request: HistoricalBarsRequest): Promise<HistoricalBarsResponse>; }
export interface FetchLike { (input: string, init?: RequestInit): Promise<Response>; }

function normalize(symbol: string, interval: HistoricalInterval, values: readonly Record<string, unknown>[]): Bar[] { const bars = values.map((row) => { const raw = String(row.datetime ?? row.timestamp ?? ""); const explicit = /^\d+$/.test(raw) ? raw : /(?:Z|[+-]\d{2}:?\d{2})$/.test(raw) ? raw : `${raw.replace(" ", "T")}Z`; const timestamp = /^\d+$/.test(explicit) ? Number(explicit) * (Number(explicit) < 10_000_000_000 ? 1000 : 1) : parseTimestampStrict(explicit); return { symbol, startMs: timestamp, intervalMs: interval === "1m" ? 60_000 : interval === "5m" ? 300_000 : interval === "15m" ? 900_000 : interval === "1h" ? 3_600_000 : 86_400_000, open: Number(row.open), high: Number(row.high), low: Number(row.low), close: Number(row.close), volume: Number(row.volume) }; }).filter((bar) => [bar.startMs, bar.open, bar.high, bar.low, bar.close, bar.volume].every(Number.isFinite)); const unique = new Map<string, Bar>(); for (const bar of bars) unique.set(`${bar.symbol}:${bar.startMs}`, bar); return [...unique.values()].sort((a, b) => a.startMs - b.startMs); }

export class TwelveDataProvider implements HistoricalDataProvider {
  readonly providerId = "twelve-data";
  constructor(private readonly apiKey: string | undefined = process.env.TWELVE_DATA_API_KEY, private readonly fetchImpl: FetchLike = fetch, private readonly baseUrl = "https://api.twelvedata.com/time_series") {}
  async fetchBars(request: HistoricalBarsRequest): Promise<HistoricalBarsResponse> { if (!this.apiKey?.trim()) throw new Error("TWELVE_DATA_API_KEY_REQUIRED"); const chunks: Record<string, unknown>[] = []; let rawResponseCount = 0; const startMs = Date.parse(request.start); const endMs = Date.parse(request.end); const cursorStep = 90 * 86_400_000; for (let cursor = startMs; cursor <= endMs; cursor += cursorStep) { const chunkStart = new Date(cursor).toISOString().slice(0, 10); const chunkEnd = new Date(Math.min(endMs, cursor + cursorStep - 1)).toISOString().slice(0, 10); const params = new URLSearchParams({ symbol: request.symbol, interval: request.interval, start_date: chunkStart, end_date: chunkEnd, timezone: "UTC", order: "asc", format: "JSON", outputsize: "5000", apikey: this.apiKey }); if (request.regularSessionOnly) params.set("prepost", "false"); let response: Response | undefined; let lastError: unknown; for (let attempt = 0; attempt < 3; attempt++) { try { response = await this.fetchImpl(`${this.baseUrl}?${params.toString()}`); if (response.ok) break; if (![429, 500, 502, 503, 504].includes(response.status)) throw new Error(`TWELVE_DATA_HTTP_${response.status}`); lastError = new Error(`TWELVE_DATA_HTTP_${response.status}`); await new Promise((resolve) => setTimeout(resolve, 250 * (attempt + 1))); } catch (error) { lastError = error; if (attempt === 2) throw error; await new Promise((resolve) => setTimeout(resolve, 250 * (attempt + 1))); } } if (!response?.ok) throw lastError instanceof Error ? lastError : new Error("TWELVE_DATA_REQUEST_FAILED"); const body = await response.json() as { status?: string; message?: string; values?: Record<string, unknown>[]; meta?: Record<string, unknown> }; if (body.status === "error" || !Array.isArray(body.values)) throw new Error(`TWELVE_DATA_RESPONSE_INVALID:${body.message ?? "values missing"}`); rawResponseCount += body.values.length; chunks.push(...body.values); if (endMs - startMs < cursorStep) break; } const bars = normalize(request.symbol, request.interval, chunks); return { bars, provider: this.providerId, requested: request, rawResponseCount, metadata: { endpoint: "time_series", timezone: "UTC", chunks: Math.max(1, Math.ceil((endMs - startMs + 1) / cursorStep)), retrievedAt: new Date().toISOString(), apiKeyPersisted: false } }; }
}

export function barsToCsv(bars: readonly Bar[]): string { return ["timestamp,symbol,open,high,low,close,volume", ...bars.map((bar) => `${new Date(bar.startMs).toISOString()},${bar.symbol},${bar.open},${bar.high},${bar.low},${bar.close},${bar.volume}`)].join("\n") + "\n"; }
export function writeAcquisitionOutput(outputPath: string, response: HistoricalBarsResponse): void { writeFileSync(outputPath, barsToCsv(response.bars)); writeFileSync(`${outputPath}.provenance.json`, JSON.stringify({ provider: response.provider, symbols: [response.requested.symbol], interval: response.requested.interval, requestedStart: response.requested.start, requestedEnd: response.requested.end, downloadedAt: response.metadata.retrievedAt, rawResponseCount: response.rawResponseCount, normalizedBarCount: response.bars.length, metadata: response.metadata }, null, 2)); }
