import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { loadBarsFile, parseIntervalMs, suggestSplits } from "./historical-data";
import { BAR_CANONICALIZATION_VERSION, canonicalDatasetHash } from "./data";
import { FIRST_LABEL_POLICY, FIRST_TARGET, FEATURE_SET_VERSION, type DatasetManifest } from "./experiment";
import { exchangeCalendarSpec } from "./calendar";
import { runHistoricalPreflight } from "./historical-preflight";

const args = process.argv.slice(2); const value = (flag: string) => { const index = args.indexOf(flag); return index >= 0 ? args[index + 1] : undefined; }; const command = args[0];
const fail = (message: string, code = 1): never => { console.error(message); process.exit(code); };
const data = value("--data"); const output = value("--output") ?? value("--out"); const symbols = (value("--symbols") ?? value("--symbol") ?? "").split(",").map((s) => s.trim()).filter(Boolean); const manifestPathForLoad = value("--manifest"); const manifestForLoad = manifestPathForLoad && existsSync(manifestPathForLoad) ? JSON.parse(readFileSync(manifestPathForLoad, "utf8")) as Partial<DatasetManifest> : undefined; const intervalMs = manifestForLoad?.barIntervalMs ?? parseIntervalMs(value("--interval") ?? 60_000);
if (!data) fail("--data FILE is required", 2);
try {
  const calendarPath = value("--calendar"); const suppliedCalendar = calendarPath ? JSON.parse(readFileSync(calendarPath, "utf8")) as Record<string, unknown> : undefined; const bars = loadBarsFile(data!, { intervalMs, symbols });
  if (command === "manifest:init") {
    const timezone = String(value("--timezone") ?? suppliedCalendar?.timeZone ?? "UTC"); const expectedSession = String(value("--expected-session") ?? "ALL"); if (expectedSession === "REGULAR" && !suppliedCalendar) fail("CALENDAR_REQUIRED_FOR_REGULAR_SESSION: pass --calendar FILE", 2); const calendarConfig = suppliedCalendar ? { ...suppliedCalendar, timeZone: timezone } : { timeZone: timezone, sessionOpenHour: 0, sessionOpenMinute: 0, sessionCloseHour: 23, sessionCloseMinute: 59 }; const calendar = exchangeCalendarSpec(calendarConfig as never); const manifest: DatasetManifest = { datasetId: "REPLACE_DATASET_ID", datasetVersion: "1", origin: "EXTERNAL_HISTORICAL_FILE", source: "", licenceNotes: "", permittedForResearch: false, symbols: symbols.length ? symbols : [...new Set(bars.map((bar) => bar.symbol))].sort(), barIntervalMs: intervalMs, timezone, startTimestamp: Math.min(...bars.map((bar) => bar.startMs)), endTimestamp: Math.max(...bars.map((bar) => bar.startMs + bar.intervalMs)), adjustmentType: "UNCONFIRMED", corporateActionStatus: "UNKNOWN", assetClass: "EQUITY", expectedSession, sessionCoveragePolicy: expectedSession === "REGULAR" ? "FULL_RTH" : "PARTIAL_ALLOWED", calendarId: calendar.calendarId, calendarSpecVersion: calendar.version, calendarSpecHash: calendar.contentHash, calendarHolidays: calendar.holidays, calendarEarlyCloses: calendar.earlyCloses, contentHash: canonicalDatasetHash(bars), canonicalizationVersion: BAR_CANONICALIZATION_VERSION, createdAt: Date.now(), dataQualitySummary: { totalRows: bars.length, acceptedRows: bars.length, rejectedRows: 0, duplicateRows: 0, invalidRows: 0, unexpectedGaps: 0, symbols: [...new Set(bars.map((bar) => bar.symbol))].sort(), issues: [] }, featureSetVersion: FEATURE_SET_VERSION, targetVersion: FIRST_TARGET.targetVersion, labelPolicyVersion: FIRST_LABEL_POLICY.version }; if (output) writeFileSync(output, JSON.stringify(manifest, null, 2)); console.log(JSON.stringify({ generatedAutomatically: { symbols: manifest.symbols, interval: manifest.barIntervalMs, range: [manifest.startTimestamp, manifest.endTimestamp], canonicalHash: manifest.contentHash, calendar: { id: manifest.calendarId, version: manifest.calendarSpecVersion, hash: manifest.calendarSpecHash } }, mustConfirm: ["source", "licenceNotes", "permittedForResearch", "adjustmentType", "corporateActionStatus"], manifest }, null, 2));
  } else if (command === "validate-data") {
    const manifestPath = value("--manifest"); if (!manifestPath || !existsSync(manifestPath)) fail("--manifest FILE is required", 2); const manifest = JSON.parse(readFileSync(manifestPath!, "utf8")) as DatasetManifest; const result = runHistoricalPreflight(manifest, bars); if (!result.checks.find((check) => check.code === "DATASET_ORIGIN_VALID")?.passed) fail("INVALID_DATASET_ORIGIN", 1); const split = args.includes("--suggest-splits") ? suggestSplits(bars, manifest) : undefined; const summary = { valid: result.passed, message: result.passed ? "DATASET/MANIFEST PREFLIGHT PASSED" : "DATASET/MANIFEST PREFLIGHT FAILED", canonicalHash: result.canonicalDatasetHash, calendarHash: result.calendarSpec.contentHash, symbols: result.dataQuality.symbols, rows: bars.length, sessions: result.sessionCount, interval: manifest.barIntervalMs, timeRange: [manifest.startTimestamp, manifest.endTimestamp], origin: manifest.origin, source: manifest.source, adjustmentStatus: manifest.adjustmentType, corporateActionStatus: manifest.corporateActionStatus, checks: result.checks, blockingReasons: result.blockingReasons, suggestedSplits: split, nextStep: `npm run experiment -- --data ${data} --manifest ${manifestPath} --config ./experiments/first-real-historical.json --output ./runs/first-real-historical` }; if (output) writeFileSync(output, JSON.stringify(summary, null, 2)); console.log(JSON.stringify(summary, null, 2)); if (!result.passed) process.exitCode = 1;
  } else if (command === "splits:suggest") { const manifestPath = value("--manifest"); if (!manifestPath || !existsSync(manifestPath)) fail("--manifest FILE is required", 2); const manifest = JSON.parse(readFileSync(manifestPath!, "utf8")) as DatasetManifest; const suggestion = suggestSplits(bars, manifest); console.log(JSON.stringify(suggestion, null, 2)); console.log(`Observed trading sessions: ${suggestion.sessionCount}\nSuggested:\nTRAIN: sessions 1–${suggestion.trainSessions}\nVALIDATION: sessions ${suggestion.trainSessions + 1}–${suggestion.validationEndSession}\nCALIBRATION: sessions ${suggestion.validationEndSession + 1}–${suggestion.calibrationEndSession}\nTEST decisions: sessions ${suggestion.calibrationEndSession + 1}–${suggestion.testEndSession}\nOutcome tail reserved: ${suggestion.outcomeTailBars} eligible bars`);
  } else fail("Usage: manifest:init, validate-data, or splits:suggest", 2);
} catch (error) { fail(error instanceof Error ? error.message : String(error)); }
