import type { Position, PortfolioSnapshot } from "./domain";
import type { IntelligenceDecision, MarketAnalysisSnapshot } from "./intelligence";
import { ExitPolicy, type ExitPolicyState } from "./exit-policy";

export type DecisionReasonCode = "FEATURE_WARMUP" | "TARGET_STATE_UNAVAILABLE" | "INSUFFICIENT_DATA" | "DATA_QUALITY_FAILURE" | "QUOTE_STALE" | "QUOTE_FROM_FUTURE" | "OUTSIDE_TRADING_SESSION" | "MODEL_UNAVAILABLE" | "MODEL_SCHEMA_MISMATCH" | "MODEL_UNVALIDATED" | "MODEL_NOT_CALIBRATED" | "MODEL_OOD_WARNING" | "MODEL_OUT_OF_DISTRIBUTION" | "TARGET_MISMATCH" | "INSUFFICIENT_ANALOGUES" | "ANALOGUE_TARGET_MISMATCH" | "ANALOGUE_SCHEMA_MISMATCH" | "LOW_EXPECTED_VALUE" | "WEAK_EVIDENCE" | "ENTRY_THRESHOLD_MET" | "ENTRY_THRESHOLD_NOT_MET" | "MODEL_EXIT_THRESHOLD" | "MAX_HOLD_REACHED" | "REGIME_INVALIDATION" | "PATTERN_INVALIDATION" | "RISK_EXIT" | "HOLD_POSITION" | "NO_POSITION" | "POSITION_LIMIT" | "GROSS_EXPOSURE_LIMIT" | "DAILY_LOSS_LIMIT" | "DRAWDOWN_LIMIT" | "ORDER_RATE_LIMIT" | "KILL_SWITCH" | "RISK_APPROVED";
export interface DecisionResult { action: IntelligenceDecision; symbol: string; timestamp: number; allowed: boolean; reasonCodes: readonly DecisionReasonCode[]; humanReadableReason: string; reason: string; evidenceQuality?: string; expectedValue?: number; }
export interface DecisionContext { analysis: MarketAnalysisSnapshot; position?: Position; portfolio?: PortfolioSnapshot; riskSummary?: Readonly<Record<string, unknown>>; exitPolicyState?: ExitPolicyState; }
export interface DecisionPolicy { minimumEvidence?: "WEAK" | "MODERATE" | "STRONG" | "VERY_STRONG"; allowWarnings?: boolean; entryProbability?: number; exitPolicy?: ExitPolicy; }
const rank: Record<string, number> = { INSUFFICIENT: 0, WEAK: 1, MODERATE: 2, STRONG: 3, VERY_STRONG: 4 };
export class DecisionEngine {
  constructor(private readonly policy: DecisionPolicy = {}) {}
  get exitPolicyVersion(): string | undefined { return this.policy.exitPolicy?.version; }
  decide(input: DecisionContext | MarketAnalysisSnapshot): DecisionResult { const context = "analysis" in input ? input : { analysis: input }; const snapshot = context.analysis; const position = context.position; const quality = snapshot.evidence?.quality; const minimum = this.policy.minimumEvidence ?? "MODERATE"; const evidenceAllowed = quality !== undefined && rank[quality] >= rank[minimum]; const oodStatus = snapshot.prediction?.ood?.status; const oodAllowed = oodStatus === undefined || oodStatus === "IN_DISTRIBUTION" || (oodStatus === "WARNING" && this.policy.allowWarnings === true); const common = { symbol: snapshot.symbol, timestamp: snapshot.decisionTimestamp, evidenceQuality: quality, expectedValue: snapshot.expectedValue };
    if (position) { const exit = this.policy.exitPolicy?.evaluate(snapshot, position, context.exitPolicyState ?? { now: snapshot.decisionTimestamp }); if (exit?.action === "CLOSE_POSITION") return { ...common, action: "SELL", allowed: true, reasonCodes: exit.reasonCodes as DecisionReasonCode[], humanReadableReason: exit.humanReadableReason, reason: exit.humanReadableReason }; if (!snapshot.features) return { ...common, action: "HOLD", allowed: true, reasonCodes: ["HOLD_POSITION"], humanReadableReason: "Features are warming up; no feature-independent exit fired", reason: "Features are warming up; no feature-independent exit fired" }; return { ...common, action: "HOLD", allowed: true, reasonCodes: ["HOLD_POSITION"], humanReadableReason: "Position is held", reason: "Position is held" }; }
    if (!snapshot.features) return { ...common, action: "NO_TRADE", allowed: false, reasonCodes: ["FEATURE_WARMUP"], humanReadableReason: "Features are warming up", reason: "Features are warming up" };
    if (snapshot.targetState?.status === "TARGET_UNREGISTERED") return { ...common, action: "NO_TRADE", allowed: false, reasonCodes: ["TARGET_MISMATCH"], humanReadableReason: "Prediction target is not registered", reason: "Prediction target is not registered" };
    if (snapshot.targetState && snapshot.targetState.status !== "AVAILABLE") return { ...common, action: "NO_TRADE", allowed: false, reasonCodes: ["TARGET_STATE_UNAVAILABLE"], humanReadableReason: "Required target state is unavailable", reason: "Required target state is unavailable" };
    if (!evidenceAllowed) return { ...common, action: "NO_TRADE", allowed: false, reasonCodes: ["WEAK_EVIDENCE"], humanReadableReason: "Evidence quality is below decision policy", reason: "Evidence quality is below decision policy" };
    if (!oodAllowed) return { ...common, action: "NO_TRADE", allowed: false, reasonCodes: [oodStatus === "WARNING" ? "MODEL_OOD_WARNING" : "MODEL_OUT_OF_DISTRIBUTION"], humanReadableReason: "OOD state is blocked by decision policy", reason: "OOD state is blocked by decision policy" };
    const probability = snapshot.prediction?.calibratedProbability ?? snapshot.prediction?.rawProbability ?? snapshot.prediction?.probability;
    const entryAllowed = probability !== undefined && probability >= (this.policy.entryProbability ?? 0.6) && (snapshot.expectedValueEstimate?.netExpectedValue ?? snapshot.expectedValue ?? -Infinity) > 0;
    if (!entryAllowed) return { ...common, action: "NO_TRADE", allowed: false, reasonCodes: [probability !== undefined && probability < (this.policy.entryProbability ?? 0.6) ? "ENTRY_THRESHOLD_NOT_MET" : "LOW_EXPECTED_VALUE"], humanReadableReason: "Entry gates are not met", reason: "Entry gates are not met" };
    return { ...common, action: "BUY", allowed: true, reasonCodes: ["ENTRY_THRESHOLD_MET", "RISK_APPROVED"], humanReadableReason: "Entry gates are met", reason: "Entry gates are met" };
  }
}
