import type { Bar } from "./domain";
import { TargetRegistry, type TargetDefinition, type TargetResolution, type TargetResolver } from "./targets";

export interface PredictionRecord { predictionId: string; symbol: string; featureTimestamp?: number; decisionTimestamp: number; targetVersion: string; /** @deprecated TargetDefinition.horizonBars is authoritative; this must match when supplied. */ horizonBars?: number; targetParameters?: Readonly<Record<string, number>>; modelId?: string; modelVersion: string; featureSetVersion?: string; featureVersion: string; rawProbability?: number; calibratedProbability?: number; probability: number; decision: "BUY" | "SELL" | "HOLD" | "NO_TRADE"; resolved?: PredictionResolution; }
export interface PredictionResolution { targetVersion: string; targetKind: string; entryMethod: "NEXT_BAR_OPEN" | "PAPER_FILL" | "NEXT_QUOTE"; entryTimestamp: number; entryPrice: number; targetStartTimestamp: number; targetEndTimestamp: number; resolutionTimestamp: number; actualLabel: string; forwardReturn: number; maxFavorableExcursion: number; maxAdverseExcursion: number; label: "WIN" | "LOSS" | "FLAT" | "AMBIGUOUS"; }
export interface ExperienceRecord extends PredictionRecord { resolved: PredictionResolution; }

export class ForwardCloseReturnResolver implements TargetResolver {
  readonly kind = "FORWARD_CLOSE_RETURN" as const;
  resolve(definition: TargetDefinition, bars: readonly Bar[], entryIndex: number): TargetResolution | null { const end = entryIndex + definition.horizonBars - 1; if (entryIndex < 0 || end >= bars.length) return null; const entry = bars[entryIndex]; const window = bars.slice(entryIndex, end + 1); const forwardReturn = bars[end].close / entry.open - 1; const threshold = Math.abs(definition.costThreshold ?? 0); return { targetVersion: definition.targetVersion, targetKind: definition.kind, entryTimestamp: entry.startMs, entryPrice: entry.open, targetStartTimestamp: entry.startMs, targetEndTimestamp: bars[end].startMs + bars[end].intervalMs, resolutionTimestamp: bars[end].startMs + bars[end].intervalMs, label: forwardReturn > threshold ? "LONG" : forwardReturn < -threshold ? "SHORT" : "FLAT", forwardReturn, mfe: Math.max(...window.map((bar) => bar.high / entry.open - 1)), mae: Math.min(...window.map((bar) => bar.low / entry.open - 1)) }; }
}
export class TripleBarrierResolver implements TargetResolver {
  readonly kind = "TRIPLE_BARRIER" as const;
  resolve(definition: TargetDefinition, bars: readonly Bar[], entryIndex: number, atr?: number): TargetResolution | null { const end = entryIndex + definition.horizonBars - 1; if (entryIndex < 0 || end >= bars.length || !Number.isFinite(atr) || atr! <= 0) return null; const entry = bars[entryIndex]; const upper = entry.open + atr! * definition.upperBarrierMultiple!; const lower = entry.open - atr! * definition.lowerBarrierMultiple!; let label: TargetResolution["label"] = "TIMEOUT"; for (let i = entryIndex; i <= end; i++) { const up = bars[i].high >= upper; const down = bars[i].low <= lower; if (up && down) { label = definition.ambiguityPolicy === "CONSERVATIVE_DOWN" ? "DOWN" : "AMBIGUOUS"; break; } if (up) { label = "UP"; break; } if (down) { label = "DOWN"; break; } } const window = bars.slice(entryIndex, end + 1); const forwardReturn = bars[end].close / entry.open - 1; return { targetVersion: definition.targetVersion, targetKind: definition.kind, entryTimestamp: entry.startMs, entryPrice: entry.open, targetStartTimestamp: entry.startMs, targetEndTimestamp: bars[end].startMs + bars[end].intervalMs, resolutionTimestamp: bars[end].startMs + bars[end].intervalMs, label, forwardReturn, mfe: Math.max(...window.map((bar) => bar.high / entry.open - 1)), mae: Math.min(...window.map((bar) => bar.low / entry.open - 1)) }; }
}

export const defaultTargetRegistry = new TargetRegistry(); defaultTargetRegistry.register({ targetVersion: "forward-close-1-v1", kind: "FORWARD_CLOSE_RETURN", horizonBars: 1 }); defaultTargetRegistry.register({ targetVersion: "triple-barrier-1-u1-d1-v1", kind: "TRIPLE_BARRIER", horizonBars: 1, upperBarrierMultiple: 1, lowerBarrierMultiple: 1, ambiguityPolicy: "AMBIGUOUS" }); defaultTargetRegistry.registerResolver(new ForwardCloseReturnResolver()); defaultTargetRegistry.registerResolver(new TripleBarrierResolver());
export function resolvePrediction(prediction: PredictionRecord, bars: readonly Bar[], registry: TargetRegistry = defaultTargetRegistry): ExperienceRecord | null { const definition = registry.get(prediction.targetVersion); if (!definition || (prediction.horizonBars !== undefined && prediction.horizonBars !== definition.horizonBars)) return null; const history = bars.filter((bar) => bar.symbol === prediction.symbol).sort((a, b) => a.startMs - b.startMs); const entryIndex = history.findIndex((bar) => bar.startMs >= prediction.decisionTimestamp); if (entryIndex < 0) return null; const resolution = registry.resolver(definition.kind)?.resolve(definition, history, entryIndex, prediction.targetParameters?.atr); if (!resolution) return null; const label = resolution.label === "UP" || resolution.label === "LONG" ? "WIN" : resolution.label === "DOWN" || resolution.label === "SHORT" ? "LOSS" : resolution.label === "AMBIGUOUS" ? "AMBIGUOUS" : "FLAT"; return { ...prediction, resolved: { ...resolution, entryMethod: "NEXT_BAR_OPEN", actualLabel: resolution.label, label, maxFavorableExcursion: resolution.mfe, maxAdverseExcursion: resolution.mae } }; }
export class PredictionQueue { private readonly pending = new Map<string, PredictionRecord>(); enqueue(prediction: PredictionRecord): void { if (this.pending.has(prediction.predictionId)) throw new Error(`Duplicate prediction id: ${prediction.predictionId}`); this.pending.set(prediction.predictionId, structuredClone(prediction)); } resolveAvailable(bars: readonly Bar[]): readonly ExperienceRecord[] { const resolved: ExperienceRecord[] = []; for (const [id, prediction] of this.pending) { const experience = resolvePrediction(prediction, bars); if (experience) { resolved.push(experience); this.pending.delete(id); } } return resolved; } pendingRecords(): readonly PredictionRecord[] { return [...this.pending.values()].map((prediction) => structuredClone(prediction)); } }
