import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { timingSafeEqual } from "node:crypto";
import { TwelveDataProvider } from "./data-acquisition";
import { boundedLimit } from "./forward-store";
import { ForwardPaperRuntime } from "./forward-runtime";
import { loadForwardConfig } from "./forward-config";

const json = (response: ServerResponse, status: number, body: unknown) => { response.statusCode = status; response.setHeader("Content-Type", "application/json"); response.end(JSON.stringify(body)); };
const log = (event: string, payload: Record<string, unknown> = {}) => process.stdout.write(`${JSON.stringify({ timestamp: new Date().toISOString(), event, ...payload })}\n`);
function authorized(request: IncomingMessage, token: string | undefined): boolean { if (!token) return false; const value = request.headers.authorization ?? ""; const supplied = value.startsWith("Bearer ") ? value.slice(7) : ""; const a = Buffer.from(supplied); const b = Buffer.from(token); return a.length === b.length && timingSafeEqual(a, b); }
function lastRequestWindow(runtime: ForwardPaperRuntime) { const last = runtime.status().lastCompletedBarTimestamp ?? runtime.config.forwardStartTimestamp ?? Date.now() - 86_400_000; return new Date(last).toISOString().slice(0, 10); }

export class ForwardPaperService {
  readonly runtime = new ForwardPaperRuntime(loadForwardConfig());
  private readonly provider = new TwelveDataProvider();
  private server?: ReturnType<typeof createServer>;
  private timer?: NodeJS.Timeout;
  private stopping = false;
  async start() { log("SERVICE_STARTED", { runtimeMode: "FORWARD_PAPER", paperOnly: true, externalExecutionEnabled: false, symbol: "AMZN", interval: "5m" }); this.server = createServer((request, response) => void this.handle(request, response)); await new Promise<void>((resolve, reject) => this.server!.listen(this.runtime.config.apiPort, this.runtime.config.apiHost, () => resolve()).on("error", reject)); log("API_STARTED", { host: this.runtime.config.apiHost, port: this.runtime.config.apiPort }); await this.poll(); this.timer = setInterval(() => void this.poll(), 60_000); }
  private async poll() { if (this.stopping) return; const now = Date.now(); if (!this.runtime.config.calendar.isRegularSession(now)) { log("MARKET_CLOSED", { symbol: "AMZN" }); return; } try { const response = await this.provider.fetchBars({ symbol: "AMZN", interval: "5m", start: lastRequestWindow(this.runtime), end: new Date(now).toISOString().slice(0, 10), regularSessionOnly: true }); this.runtime.recordProviderSuccess(now); log("PROVIDER_SUCCESS", { provider: response.provider, returnedBars: response.bars.length }); for (const bar of response.bars) { const result = this.runtime.processBar(bar, now); if (result.status === "PROCESSED") log("BAR_PROCESSED", { barId: result.barId, decision: result.decision?.action, filled: result.filled }); else if (result.status === "DUPLICATE") log("BAR_DUPLICATE", { barId: result.barId }); } await this.runtime.maybeTrain(now); } catch (error) { const message = error instanceof Error ? error.message : "PROVIDER_FAILURE"; this.runtime.recordProviderFailure(message); log("PROVIDER_FAILURE", { reason: message }); } }
  private async handle(request: IncomingMessage, response: ServerResponse) { const url = new URL(request.url ?? "/", `http://${this.runtime.config.apiHost}:${this.runtime.config.apiPort}`); if (request.method !== "GET") return json(response, 405, { error: "READ_ONLY_API" }); if (url.pathname === "/health") return json(response, 200, this.runtime.health()); if (!url.pathname.startsWith("/api/")) return json(response, 404, { error: "NOT_FOUND" }); if (!authorized(request, this.runtime.config.apiToken)) return json(response, 401, { error: "UNAUTHORIZED" }); try { const limit = boundedLimit(url.searchParams.get("limit")); const path = url.pathname; if (path === "/api/status") return json(response, 200, this.runtime.status()); if (path === "/api/model") return json(response, 200, this.runtime.verifyModel()); if (path === "/api/paper/portfolio") return json(response, 200, this.runtime.status().portfolio); if (path === "/api/paper/positions") return json(response, 200, this.runtime.broker.openPositions); if (path === "/api/paper/orders") return json(response, 200, this.runtime.query("paper_orders", limit)); if (path === "/api/paper/fills") return json(response, 200, this.runtime.query("paper_fills", limit)); if (path === "/api/paper/trades") return json(response, 200, this.runtime.query("paper_orders", limit).filter((order: any) => order.status === "FILLED")); if (path === "/api/paper/decisions" || path === "/api/decisions") return json(response, 200, this.runtime.query("decisions", limit)); if (path === "/api/predictions") return json(response, 200, this.runtime.query("predictions", limit)); if (path === "/api/experience/summary") { const rows = this.runtime.store.all<any>("resolved_experiences"); return json(response, 200, { total: rows.length, binary: rows.filter((row) => ["LONG", "SHORT"].includes(row.resolved?.actualLabel)).length, up: rows.filter((row) => row.resolved?.actualLabel === "LONG").length, down: rows.filter((row) => row.resolved?.actualLabel === "SHORT").length, noTrade: rows.filter((row) => String(row.category).startsWith("NO_TRADE")).length, recent: rows.slice(-limit) }); } if (path === "/api/learning/status") return json(response, 200, this.runtime.learningStatus()); if (path === "/api/learning/runs") return json(response, 200, this.runtime.store.recent("training_runs", limit)); if (path === "/api/models") return json(response, 200, this.runtime.store.recent("models", limit)); if (path === "/api/drift") return json(response, 200, { status: "DIAGNOSTIC_ONLY", message: "Feature drift is diagnostic and never changes thresholds automatically" }); return json(response, 404, { error: "NOT_FOUND" }); } catch (error) { return json(response, 400, { error: error instanceof Error ? error.message : "BAD_REQUEST" }); } }
  async stop() { this.stopping = true; if (this.timer) clearInterval(this.timer); await new Promise<void>((resolve) => this.server?.close(() => resolve()) ?? resolve()); this.runtime.close(); log("SERVICE_STOPPED"); }
}

if (import.meta.url === `file://${process.argv[1]}`) { const service = new ForwardPaperService(); const stop = () => void service.stop().finally(() => process.exit(0)); process.on("SIGTERM", stop); process.on("SIGINT", stop); service.start().catch((error) => { log("SERVICE_START_FAILED", { reason: error instanceof Error ? error.message : "UNKNOWN" }); process.exitCode = 1; }); }
