import type { Bar, PortfolioSnapshot, Quote } from "./domain";
import { validateBar, validateQuote } from "./data";
import { PaperBroker } from "./broker";
import { DecisionEngine, type DecisionResult } from "./decision";
import { IntelligenceEngine, type MarketAnalysisSnapshot } from "./intelligence";
import { RiskManager, type RiskState } from "./risk";
import { TradeLedger } from "./trades";
import { performanceMetrics, type PerformanceMetrics } from "./metrics";
import type { LocalEnginePort } from "./local-service";

export interface IntegratedEvent { bar: Bar; quote: Quote; }
export interface IntegratedResult { snapshot: MarketAnalysisSnapshot; decision: DecisionResult; filled: number; }
export interface IntegratedReplayResult { snapshots: readonly PortfolioSnapshot[]; trades: ReturnType<TradeLedger["all"]>; metrics: PerformanceMetrics; finalEquity: number; }

export class IntegratedPaperResearchEngine implements LocalEnginePort {
  private paused = false; private killSwitch = false; private operationalNowMs?: number; private highWaterMark: number; private dayStartEquity: number; private orderSequence = 0; private bars = 0; private readonly orderTimes: number[] = []; private readonly marks = new Map<string, number>(); private readonly lastQuoteTs = new Map<string, number>();
  constructor(readonly intelligence: IntelligenceEngine, readonly decisions: DecisionEngine, readonly broker: PaperBroker, private readonly risk: RiskManager, private readonly strategyId = "integrated-intelligence", private readonly strategyVersion = "1") { this.highWaterMark = broker.balance; this.dayStartEquity = broker.balance; }
  onBar(bar: Bar, quote: Quote): IntegratedResult { validateBar(bar); validateQuote(quote); if (quote.symbol !== bar.symbol || quote.ts < bar.startMs + bar.intervalMs) return this.rejected(bar, "Quote is not aligned to completed bar"); if (this.operationalNowMs !== undefined && quote.ts > this.operationalNowMs + 1_000) return this.rejected(bar, "Quote is from the future"); if (this.operationalNowMs !== undefined && this.operationalNowMs - quote.ts > 120_000) return this.rejected(bar, "Market data is stale"); const snapshot = this.intelligence.analyze(bar, quote); this.bars++; const mark = quote.last ?? (quote.bid + quote.ask) / 2; this.marks.set(bar.symbol, mark); this.lastQuoteTs.set(bar.symbol, quote.ts); const decision = this.decisions.decide(snapshot); if (!decision.allowed || this.paused || this.killSwitch) return { snapshot, decision: { ...decision, action: "NO_TRADE", allowed: false, reason: this.killSwitch ? "Kill switch is active" : this.paused ? "Engine is paused" : decision.reason }, filled: 0 }; const price = decision.action === "BUY" ? quote.ask : quote.bid; const position = this.broker.openPositions.find((item) => item.symbol === bar.symbol); const requested = decision.action === "SELL" ? position?.quantity ?? 0 : Math.floor(10_000 / quote.ask); if (requested <= 0) return { snapshot, decision: { ...decision, action: "NO_TRADE", allowed: false, reason: "No executable quantity" }, filled: 0 }; const now = Math.max(bar.startMs + bar.intervalMs, quote.ts); this.orderTimes.splice(0, this.orderTimes.length, ...this.orderTimes.filter((timestamp) => now - timestamp < 60_000)); const state: RiskState = { equity: this.markToMarket(bar.symbol, quote), dayStartEquity: this.dayStartEquity, highWaterMark: this.highWaterMark, openPositions: this.broker.openPositions, ordersInLastMinute: this.orderTimes.length, killSwitch: this.paused || this.killSwitch, marks: Object.fromEntries(this.marks) }; const intent = { symbol: bar.symbol, side: decision.action === "BUY" ? "BUY" as const : "SELL" as const, type: "MARKET" as const, quantity: requested, strategyId: this.strategyId, strategyVersion: this.strategyVersion, reason: decision.reason, submittedAt: now }; const sized = this.risk.size(intent, price, state); if (!sized.allowed) return { snapshot, decision: { ...decision, action: "NO_TRADE", allowed: false, reason: `Risk rejected: ${sized.reason}` }, filled: 0 }; this.broker.submit({ ...intent, id: `integrated-order-${now}-${this.orderSequence++}`, quantity: sized.quantity, status: "NEW", fills: [] }); const fills = this.broker.onQuote(quote); this.orderTimes.push(now); this.highWaterMark = Math.max(this.highWaterMark, this.markToMarket(bar.symbol, quote)); return { snapshot, decision, filled: fills.reduce((sum, fill) => sum + fill.quantity, 0) }; }
  private rejected(bar: Bar, reason: string): IntegratedResult { const snapshot: MarketAnalysisSnapshot = { symbol: bar.symbol, timestamp: bar.startMs + bar.intervalMs, features: null, structure: null, regime: null, patterns: [], decision: "NO_TRADE", reason }; return { snapshot, decision: { action: "NO_TRADE", symbol: bar.symbol, timestamp: snapshot.timestamp, allowed: false, reason }, filled: 0 }; }
  portfolioSnapshot(ts: number): PortfolioSnapshot { const marks = Object.fromEntries(this.marks); const equity = this.broker.markToMarket(marks); return { ts, cash: this.broker.balance, equity, marks, grossExposure: this.broker.openPositions.reduce((sum, position) => sum + Math.abs(position.quantity * (marks[position.symbol] ?? position.averagePrice)), 0), drawdown: this.highWaterMark ? (this.highWaterMark - equity) / this.highWaterMark : 0, dayStartEquity: this.dayStartEquity, highWaterMark: this.highWaterMark }; }
  private markToMarket(symbol: string, quote: Quote) { return this.broker.markToMarket({ [symbol]: quote.last ?? (quote.bid + quote.ask) / 2 }); }
  setOperationalNow(ts: number) { this.operationalNowMs = ts; }
  pause() { this.paused = true; }
  resume() { if (!this.killSwitch) this.paused = false; }
  activateKillSwitch() { this.killSwitch = true; this.paused = true; }
  resetKillSwitch() { this.killSwitch = false; }
  get health() { const now = this.operationalNowMs; const staleSymbols = now === undefined ? [] : [...this.lastQuoteTs.entries()].filter(([, timestamp]) => now - timestamp > 120_000).map(([symbol]) => symbol); return { paused: this.paused || this.killSwitch, killSwitch: this.killSwitch, dataFresh: this.lastQuoteTs.size > 0 && staleSymbols.length === 0, staleSymbols, lastQuoteTs: Object.fromEntries(this.lastQuoteTs), symbols: [...this.lastQuoteTs.keys()], bars: this.bars, balance: this.broker.balance, positions: this.broker.openPositions }; }
}

export function replayIntegrated(events: readonly IntegratedEvent[], engine: IntegratedPaperResearchEngine): IntegratedReplayResult { const ledger = new TradeLedger(); const snapshots: PortfolioSnapshot[] = []; const processed = new Set<string>(); for (const event of [...events].sort((a, b) => a.quote.ts - b.quote.ts)) { engine.onBar(event.bar, event.quote); for (const order of engine.broker.allOrders) for (const fill of order.fills) if (!processed.has(fill.id)) { processed.add(fill.id); ledger.applyFill(order, fill, { high: event.bar.high, low: event.bar.low }); } snapshots.push(engine.portfolioSnapshot(event.quote.ts)); } const trades = ledger.all(); const equity = snapshots.map((snapshot) => ({ ts: snapshot.ts, value: snapshot.equity })); return { snapshots, trades, metrics: performanceMetrics(equity.length > 1 ? equity : [{ ts: 0, value: engine.broker.balance }, { ts: 1, value: engine.broker.balance }], trades.map((trade) => trade.netPnl)), finalEquity: snapshots.at(-1)?.equity ?? engine.broker.balance }; }
