import type { Bar, PortfolioSnapshot, Quote } from "./domain";
import { validateBar, validateQuote } from "./data";
import { PaperBroker } from "./broker";
import { DecisionEngine, type DecisionContext, type DecisionResult } from "./decision";
import { IntelligenceEngine, type MarketAnalysisSnapshot } from "./intelligence";
import { RiskManager, type RiskState } from "./risk";
import { TradeLedger } from "./trades";
import { approximatePeriodsPerYear, performanceMetrics, resampleEquityCurve, type EquityFrequency, type PerformanceMetrics } from "./metrics";
import { TradingCalendar } from "./calendar";
import type { LocalEnginePort } from "./local-service";
import type { EventRepository } from "./research-ledger";
import { PredictionQueue, resolvePrediction, defaultTargetRegistry, type ExperienceRecord, type PredictionRecord } from "./experience";
import type { TradeRepository } from "./research-ledger";
import type { TargetRegistry } from "./targets";

export interface IntegratedEvent { bar: Bar; quote: Quote; }
export interface IntegratedResult { snapshot: MarketAnalysisSnapshot; decision: DecisionResult; filled: number; }
export interface PositionResearchContext { entryTimestamp: number; predictionId?: string; decisionId: string; modelId?: string; modelVersion?: string; targetVersion?: string; entryProbability?: number; entryRegime?: string; entryPatterns: readonly string[]; exitPolicyVersion?: string; }
export interface IntegratedReplayResult { snapshots: readonly PortfolioSnapshot[]; trades: ReturnType<TradeLedger["all"]>; metrics: PerformanceMetrics; finalEquity: number; }

export class IntegratedPaperResearchEngine implements LocalEnginePort {
  private paused = false; private killSwitch = false; private operationalNowMs?: number; private highWaterMark: number; private dayStartEquity: number; private dayKey?: string; private orderSequence = 0; private bars = 0;
  private readonly orderTimes: number[] = []; private readonly marks = new Map<string, number>(); private readonly lastQuoteTs = new Map<string, number>(); private readonly orderSnapshots = new Map<string, MarketAnalysisSnapshot>(); private readonly processedFills = new Set<string>();
  readonly ledger: TradeLedger; readonly predictionQueue = new PredictionQueue(); private readonly history = new Map<string, Bar[]>(); private readonly positionResearch = new Map<string, PositionResearchContext>(); private eventSequence = 0; private readonly targetRegistry: TargetRegistry;
  constructor(readonly intelligence: IntelligenceEngine, readonly decisions: DecisionEngine, readonly broker: PaperBroker, private readonly risk: RiskManager, private readonly strategyId = "integrated-intelligence", private readonly strategyVersion = "1", readonly calendar = new TradingCalendar(), ledger?: TradeLedger, private readonly journal?: EventRepository, private readonly experienceRepository?: TradeRepository<ExperienceRecord>, targetRegistry?: TargetRegistry) { this.highWaterMark = broker.balance; this.dayStartEquity = broker.balance; this.ledger = ledger ?? new TradeLedger(); this.targetRegistry = targetRegistry ?? intelligence.targetRegistry(); }
  onBar(bar: Bar, quote: Quote): IntegratedResult {
    validateBar(bar); validateQuote(quote); const barCloseTimestamp = bar.startMs + bar.intervalMs;
    if (quote.symbol !== bar.symbol || quote.ts < barCloseTimestamp) return this.rejected(bar, "QUOTE_STALE", "Quote is not aligned to completed bar");
    if (this.operationalNowMs !== undefined && quote.ts > this.operationalNowMs + 1_000) return this.rejected(bar, "QUOTE_FROM_FUTURE", "Quote is from the future");
    if (this.operationalNowMs !== undefined && this.operationalNowMs - quote.ts > 120_000) return this.rejected(bar, "QUOTE_STALE", "Market data is stale");
    const snapshot = this.intelligence.analyze(bar, quote); this.bars++; const priorBars = this.history.get(bar.symbol) ?? []; this.history.set(bar.symbol, [...priorBars, bar]); this.emit("MARKET_BAR_ACCEPTED", bar, { eventTimestamp: barCloseTimestamp, intervalMs: bar.intervalMs }); this.emit("QUOTE_ACCEPTED", bar, { eventTimestamp: quote.ts, quoteTimestamp: quote.ts }); this.ledger.updateMark(bar.symbol, bar.high, bar.low);
    this.marks.set(bar.symbol, quote.last ?? (quote.bid + quote.ask) / 2); this.lastQuoteTs.set(bar.symbol, quote.ts);
    const now = Math.max(barCloseTimestamp, quote.ts); const equity = this.markToMarket(); this.updateSession(now, equity);
    const position = this.broker.openPositions.find((item) => item.symbol === bar.symbol); const savedContext = this.positionResearch.get(bar.symbol); const context: DecisionContext = { analysis: snapshot, position, portfolio: this.portfolioSnapshot(now), exitPolicyState: { now, entryTimestamp: savedContext?.entryTimestamp ?? position?.entryTimestamp, entryModelProbability: savedContext?.entryProbability ?? position?.entryModelProbability, entryRegime: savedContext?.entryRegime ?? position?.entryRegime, entryPatterns: savedContext?.entryPatterns ?? position?.entryPatterns } };
    let decision = this.decisions.decide(context); this.emit("FEATURES_COMPUTED", bar, { eventTimestamp: snapshot.decisionTimestamp, available: Boolean(snapshot.features), decisionTimestamp: snapshot.decisionTimestamp }); if (snapshot.structure) this.emit("MARKET_STRUCTURE_UPDATED", bar, { eventTimestamp: snapshot.decisionTimestamp, trend: snapshot.structure.trend }); if (snapshot.regime) this.emit("REGIME_UPDATED", bar, { eventTimestamp: snapshot.decisionTimestamp, trend: snapshot.regime.trend }); for (const pattern of snapshot.patterns) this.emit("PATTERN_DETECTED", bar, { eventTimestamp: snapshot.decisionTimestamp, type: pattern.type, version: pattern.version }); const outsideRth = !this.calendar.isRegularSession(now);
    if (outsideRth && decision.action === "BUY") decision = this.blocked(decision, "OUTSIDE_TRADING_SESSION", "New risk is disabled outside regular trading hours");
    if (this.paused && decision.action === "BUY") decision = this.blocked(decision, "NO_POSITION", "Engine is paused; new entries are disabled");
    if (snapshot.prediction && snapshot.targetState?.status === "AVAILABLE") { const prediction: PredictionRecord = { predictionId: snapshot.prediction.predictionId, symbol: bar.symbol, featureTimestamp: snapshot.featureTimestamp!, decisionTimestamp: snapshot.decisionTimestamp, targetVersion: snapshot.prediction.targetVersion, modelId: snapshot.prediction.modelId, modelVersion: snapshot.prediction.modelVersion, featureSetVersion: snapshot.prediction.featureSetVersion, featureIds: snapshot.prediction.featureIds, featureVersion: snapshot.prediction.featureSetVersion, rawProbability: snapshot.prediction.rawProbability, calibratedProbability: snapshot.prediction.calibratedProbability, probability: snapshot.prediction.probability, targetStateAtDecision: snapshot.targetState, analysisId: `analysis-${bar.symbol}-${snapshot.decisionTimestamp}`, decisionId: `decision-${bar.symbol}-${snapshot.decisionTimestamp}`, decision: decision.action }; try { this.predictionQueue.enqueue(prediction); this.emit("PREDICTION_CREATED", bar, { eventTimestamp: snapshot.decisionTimestamp, predictionId: prediction.predictionId, decisionId: prediction.decisionId, targetVersion: prediction.targetVersion, modelId: prediction.modelId, modelVersion: prediction.modelVersion, featureSetVersion: prediction.featureSetVersion }); } catch { /* deterministic duplicate event is harmless on replay */ } }
    const resolved = this.predictionQueue.resolveAvailable(this.history.get(bar.symbol) ?? [], this.targetRegistry); for (const experience of resolved) { this.experienceRepository?.append(experience); this.emit("PREDICTION_RESOLVED", bar, { eventTimestamp: experience.resolved.resolutionTimestamp, predictionId: experience.predictionId, label: experience.resolved.label }); }
    this.emit("DECISION_CREATED", bar, { eventTimestamp: now, action: decision.action, allowed: decision.allowed, reasonCodes: decision.reasonCodes });
    if (decision.action === "HOLD" || decision.action === "NO_TRADE" || !decision.allowed) return { snapshot, decision, filled: 0 };
    if (this.killSwitch && decision.action === "BUY") return { snapshot, decision: this.blocked(decision, "KILL_SWITCH", "Kill switch blocks new risk"), filled: 0 };
    const side = decision.action; const price = side === "BUY" ? quote.ask : quote.bid; const requested = side === "SELL" ? position?.quantity ?? 0 : Math.floor(10_000 / quote.ask);
    if (requested <= 0) return { snapshot, decision: this.blocked(decision, "NO_POSITION", "No executable quantity"), filled: 0 };
    this.orderTimes.splice(0, this.orderTimes.length, ...this.orderTimes.filter((timestamp) => now - timestamp < 60_000));
    const state: RiskState = { equity, dayStartEquity: this.dayStartEquity, highWaterMark: this.highWaterMark, openPositions: this.broker.openPositions, ordersInLastMinute: this.orderTimes.length, killSwitch: this.killSwitch || this.paused, marks: Object.fromEntries(this.marks) };
    const intent = { symbol: bar.symbol, side, type: "MARKET" as const, quantity: requested, strategyId: this.strategyId, strategyVersion: this.strategyVersion, reason: decision.humanReadableReason, submittedAt: now };
    const sized = this.risk.size(intent, price, state); if (!sized.allowed) { this.emit("RISK_REJECTED", bar, { reason: sized.reason }); return { snapshot, decision: this.blocked(decision, "RISK_EXIT", `Risk rejected: ${sized.reason}`), filled: 0 }; }
    this.emit("RISK_APPROVED", bar, { side, quantity: sized.quantity }); const order = { ...intent, id: `integrated-order-${now}-${this.orderSequence++}`, quantity: sized.quantity, status: "NEW" as const, fills: [] }; this.broker.submit(order); this.orderSnapshots.set(order.id, snapshot); this.emit("ORDER_SUBMITTED", bar, { orderId: order.id, side, quantity: order.quantity });
    const fills = this.broker.onQuote(quote); this.orderTimes.push(now); this.recordFills(snapshot, bar, fills); this.highWaterMark = Math.max(this.highWaterMark, this.markToMarket()); return { snapshot, decision, filled: fills.reduce((sum, fill) => sum + fill.quantity, 0) };
  }
  private recordFills(snapshot: MarketAnalysisSnapshot, bar: Bar, fills: readonly { id: string; orderId: string; ts: number; quantity: number; price: number; fee: number }[]) { for (const fill of fills) { if (this.processedFills.has(fill.id)) continue; this.processedFills.add(fill.id); const order = this.broker.allOrders.find((item) => item.id === fill.orderId); if (order) { const closed = this.ledger.applyFill(order, fill, { high: bar.high, low: bar.low, regime: snapshot.regime?.trend, patterns: snapshot.patterns.map((pattern) => pattern.type) }); if (order.side === "BUY" && !this.positionResearch.has(bar.symbol)) this.positionResearch.set(bar.symbol, { entryTimestamp: fill.ts, predictionId: snapshot.prediction?.predictionId, decisionId: `decision-${bar.symbol}-${snapshot.decisionTimestamp}`, modelId: snapshot.prediction?.modelId, modelVersion: snapshot.prediction?.modelVersion, targetVersion: snapshot.prediction?.targetVersion, entryProbability: snapshot.prediction?.probability, entryRegime: snapshot.regime?.trend, entryPatterns: snapshot.patterns.map((pattern) => pattern.type), exitPolicyVersion: this.decisions.exitPolicyVersion }); if (closed.length && !this.broker.openPositions.some((position) => position.symbol === bar.symbol)) this.positionResearch.delete(bar.symbol); this.emit(fill.quantity < order.quantity ? "ORDER_PARTIAL_FILL" : "ORDER_FILLED", bar, { eventTimestamp: fill.ts, orderId: order.id, fillId: fill.id, quantity: fill.quantity }); for (const trade of closed) this.emit("TRADE_CLOSED", bar, { eventTimestamp: trade.exitTimestamp, tradeId: trade.tradeId, netPnl: trade.netPnl }); } } }
  private emit(eventType: import("./research-ledger").ResearchEventType, bar: Bar, payload: Record<string, unknown>) { const eventTimestamp = payload.eventTimestamp; const timestamp = typeof eventTimestamp === "number" && Number.isFinite(eventTimestamp) ? eventTimestamp : bar.startMs + bar.intervalMs; const { eventTimestamp: _, ...cleanPayload } = payload; this.journal?.append({ id: `event-${bar.symbol}-${bar.startMs}-${this.eventSequence++}`, timestamp, eventType, symbol: bar.symbol, component: "integrated-engine", version: "0.2.0", payload: cleanPayload }); }
  private blocked(decision: DecisionResult, code: DecisionResult["reasonCodes"][number], reason: string): DecisionResult { return { ...decision, action: "NO_TRADE", allowed: false, reasonCodes: [code], humanReadableReason: reason, reason }; }
  private rejected(bar: Bar, code: DecisionResult["reasonCodes"][number], reason: string): IntegratedResult { const timestamp = bar.startMs + bar.intervalMs; const snapshot: MarketAnalysisSnapshot = { symbol: bar.symbol, barCloseTimestamp: timestamp, decisionTimestamp: timestamp, timestamp, features: null, structure: null, regime: null, patterns: [], dataQuality: { ok: false, issues: [code] } }; const decision: DecisionResult = { action: "NO_TRADE", symbol: bar.symbol, timestamp, allowed: false, reasonCodes: [code], humanReadableReason: reason, reason }; return { snapshot, decision, filled: 0 }; }
  portfolioSnapshot(ts: number): PortfolioSnapshot { const marks = Object.fromEntries(this.marks); const equity = this.broker.markToMarket(marks); return { ts, cash: this.broker.balance, equity, marks, grossExposure: this.broker.openPositions.reduce((sum, position) => sum + Math.abs(position.quantity * (marks[position.symbol] ?? position.averagePrice)), 0), drawdown: this.highWaterMark ? (this.highWaterMark - equity) / this.highWaterMark : 0, dayStartEquity: this.dayStartEquity, highWaterMark: this.highWaterMark }; }
  private markToMarket() { return this.broker.markToMarket(Object.fromEntries(this.marks)); }
  private updateSession(ts: number, equity: number) { if (this.calendar.isRegularSession(ts)) { const key = this.calendar.sessionKey(ts); if (key !== this.dayKey) { this.dayKey = key; this.dayStartEquity = equity; } } this.highWaterMark = Math.max(this.highWaterMark, equity); }
  setOperationalNow(ts: number) { this.operationalNowMs = ts; }
  pause() { this.paused = true; }
  resume() { if (!this.killSwitch) this.paused = false; }
  activateKillSwitch() { this.killSwitch = true; }
  resetKillSwitch() { this.killSwitch = false; }
  get health() { const now = this.operationalNowMs; const staleSymbols = now === undefined ? [] : [...this.lastQuoteTs.entries()].filter(([, timestamp]) => now - timestamp > 120_000).map(([symbol]) => symbol); return { paused: this.paused, killSwitch: this.killSwitch, dataFresh: this.lastQuoteTs.size > 0 && staleSymbols.length === 0, staleSymbols, lastQuoteTs: Object.fromEntries(this.lastQuoteTs), symbols: [...this.lastQuoteTs.keys()], bars: this.bars, balance: this.broker.balance, positions: this.broker.openPositions, engineMode: "INTEGRATED_RESEARCH", serviceVersion: "0.2.0", protocolVersion: "1" }; }
}
export function replayIntegrated(events: readonly IntegratedEvent[], engine: IntegratedPaperResearchEngine, options: { frequency?: EquityFrequency; periodsPerYear?: number } = {}): IntegratedReplayResult { const snapshots: PortfolioSnapshot[] = []; for (const event of [...events].sort((a, b) => a.quote.ts - b.quote.ts || a.bar.startMs - b.bar.startMs || a.bar.symbol.localeCompare(b.bar.symbol))) { engine.onBar(event.bar, event.quote); snapshots.push(engine.portfolioSnapshot(event.quote.ts)); } const trades = engine.ledger.all(); const frequency = options.frequency ?? "1m"; const periodsPerYear = options.periodsPerYear ?? approximatePeriodsPerYear(frequency); const equity = resampleEquityCurve(snapshots.map((snapshot) => ({ ts: snapshot.ts, value: snapshot.equity })), frequency, engine.calendar); const safeEquity = equity.length > 1 ? equity : [{ ts: 0, value: engine.broker.balance }, { ts: 1, value: engine.broker.balance }]; return { snapshots, trades, metrics: performanceMetrics(safeEquity, trades.map((trade) => trade.netPnl), periodsPerYear, 0, { frequency, periodsPerYear }), finalEquity: snapshots.at(-1)?.equity ?? engine.broker.balance }; }
