import type { Bar, FeatureVector, Quote } from "./domain";
import { appendBar, validateQuote } from "./data";
import { buildFeatures } from "./features";
import { TrustedAnalogueEngine, type TrustedAnalogueObservation, type TargetSpecificAnalogueResult, type TrustedAnalogueScalerProfile } from "./analogues";
import { assessEvidence, assessRegimeEvidence, type EvidenceResult, type RegimeEvidenceResult } from "./evidence";
import { expectedValue } from "./statistics";
import { detectMarketStructure, type MarketStructureSnapshot } from "./structure";
import { classifyRegime, type RegimeState } from "./regime";
import { detectPatterns, type PatternDetection } from "./patterns";
import { type OodStatus } from "./ml";
import { PredictiveModelBundle } from "./ml-contracts";
import { namedFeatures, type NamedFeatureVector } from "./feature-schema";
import { averageTrueRange } from "./features";
import { type TargetRegistry, type TargetStateAtDecision } from "./targets";
import { defaultTargetRegistry } from "./experience";
import { ExecutionCostModel } from "./costs";

export type IntelligenceDecision = "BUY" | "SELL" | "HOLD" | "NO_TRADE";
export const TRIPLE_BARRIER_EV_VERSION = "triple-barrier-ev-v2";
export const TRIPLE_BARRIER_TIMEOUT_RETURN = 0;
export const TRIPLE_BARRIER_AMBIGUOUS_RETURN = 0;
export interface ExpectedValueEstimate { value: number; unit: "RETURN"; methodVersion: string; referencePrice: number; referenceMethod: "QUOTE_MID" | "BAR_CLOSE"; observedSpreadBps?: number; grossExpectedValue: number; executionCost: number; netExpectedValue: number; outcomeProbabilities?: TripleBarrierOutcomeProbabilities; }
export interface MarketAnalysisSnapshot { symbol: string; barCloseTimestamp: number; quoteTimestamp?: number; featureTimestamp?: number; decisionTimestamp: number; timestamp: number; features: FeatureVector | null; structure: MarketStructureSnapshot | null; regime: RegimeState | null; patterns: readonly PatternDetection[]; targetState?: TargetStateAtDecision; prediction?: { predictionId: string; modelId: string; modelVersion: string; featureSetVersion: string; featureIds: readonly string[]; targetVersion: string; rawProbability: number; calibratedProbability: number; probability: number; ood: { status: OodStatus; maxAbsZ: number } }; analogues?: TargetSpecificAnalogueResult & { distances: readonly number[]; evidence: "INSUFFICIENT" | "SUFFICIENT" }; regimeEvidence?: RegimeEvidenceResult; evidence?: EvidenceResult; expectedValue?: number; expectedValueEstimate?: ExpectedValueEstimate; evReferencePrice?: number; evReferenceMethod?: "QUOTE_MID" | "BAR_CLOSE"; dataQuality?: { ok: boolean; issues: readonly string[] }; }
export interface IntelligenceConfig { model?: PredictiveModelBundle; targetRegistry?: TargetRegistry; trustedAnalogues?: readonly TrustedAnalogueObservation[]; analogueScalerProfile?: TrustedAnalogueScalerProfile; minimumAnalogueSample?: number; minimumRegimeAnalogueSample?: number; minimumRegimeMatchRate?: number; regimeAnaloguePolicy?: "MATCH_CURRENT_REGIME" | "ALL_REGIMES_WITH_COVERAGE_REPORT"; probabilityThreshold?: number; costModel?: ExecutionCostModel; evidence?: import("./evidence").ResearchEvidenceContext; requiredEvidencePolicy?: import("./evidence").RequiredEvidencePolicy; featureConfig?: { sessionsPerYear?: number; sessionMinutesPerDay?: number }; }

export interface TripleBarrierOutcomeProbabilities { up: number; down: number; timeout: number; ambiguous: number; methodVersion: string; probabilityMeaning: string; }
export function decomposeTripleBarrierProbabilities(probability: number, barrier: NonNullable<TargetSpecificAnalogueResult["barrier"]>, probabilityMeaning: "P_UP_GIVEN_UP_OR_DOWN" | "P_UP_OUTCOME"): TripleBarrierOutcomeProbabilities { const decisive = barrier.upRate + barrier.downRate; let up: number; let down: number; let timeout: number; let ambiguous: number; if (probabilityMeaning === "P_UP_GIVEN_UP_OR_DOWN") { up = probability * decisive; down = (1 - probability) * decisive; timeout = barrier.timeoutRate; ambiguous = barrier.ambiguousRate; } else { up = probability; const remainder = Math.max(0, 1 - up); const nonUp = barrier.downRate + barrier.timeoutRate + barrier.ambiguousRate || 1; down = remainder * barrier.downRate / nonUp; timeout = remainder * barrier.timeoutRate / nonUp; ambiguous = remainder * barrier.ambiguousRate / nonUp; } const total = up + down + timeout + ambiguous || 1; return { up: up / total, down: down / total, timeout: timeout / total, ambiguous: ambiguous / total, methodVersion: TRIPLE_BARRIER_EV_VERSION, probabilityMeaning }; }

export function featureVectorForModel(features: FeatureVector): number[] { return [features.ret1, features.ret5, features.emaFastDistance, features.emaSlowDistance, features.rsi14 / 100, features.realisedVol20, features.volumeZ, features.spreadBps ?? 0, features.bookImbalance ?? 0]; }

export class IntelligenceEngine {
  private readonly histories = new Map<string, Bar[]>();
  constructor(private readonly config: IntelligenceConfig = {}) {}
  targetRegistry(): TargetRegistry { return this.config.targetRegistry ?? defaultTargetRegistry; }
  analyze(bar: Bar, quote?: Quote): MarketAnalysisSnapshot {
    if (quote) { validateQuote(quote); if (quote.symbol !== bar.symbol || quote.ts < bar.startMs + bar.intervalMs) throw new Error("Quote must be for the same symbol at or after bar completion"); }
    const history = this.histories.get(bar.symbol) ?? []; const next = appendBar(history, bar); this.histories.set(bar.symbol, next);
    const timestamp = bar.startMs + bar.intervalMs; const decisionTimestamp = quote?.ts ?? timestamp; const rawFeatures = buildFeatures(next, quote, { ...this.config.featureConfig, decisionTimestamp }); const features = rawFeatures ? { ...rawFeatures, ts: decisionTimestamp } : null;
    if (!features) return { symbol: bar.symbol, barCloseTimestamp: timestamp, quoteTimestamp: quote?.ts, featureTimestamp: decisionTimestamp, decisionTimestamp, timestamp, features: null, structure: null, regime: null, patterns: [], targetState: { status: "WARMUP", values: {}, featureVersions: [] }, dataQuality: { ok: true, issues: ["FEATURE_WARMUP"] } };
    const structure = detectMarketStructure(next); const regime = classifyRegime(features, structure); const patterns = detectPatterns(features, structure, regime); const named = namedFeatures(features); const registry = this.targetRegistry(); const definition = this.config.model ? registry.get(this.config.model.targetVersion) : undefined; const atrAtDecision = definition?.kind === "TRIPLE_BARRIER" ? averageTrueRange(next, 14) : undefined; const targetState: TargetStateAtDecision = !this.config.model ? { status: "MISSING_REQUIRED_INPUT", values: {}, featureVersions: [] } : !definition ? { status: "TARGET_UNREGISTERED", values: {}, featureVersions: [] } : definition.kind === "TRIPLE_BARRIER" && !Number.isFinite(atrAtDecision) ? { status: "MISSING_REQUIRED_INPUT", values: {}, featureVersions: ["atr14-v1"] } : { status: "AVAILABLE", values: atrAtDecision === undefined ? {} : { atrAtDecision }, featureVersions: atrAtDecision === undefined ? [] : ["atr14-v1"] };
    const predictionResult = targetState.status === "AVAILABLE" && this.config.model ? this.config.model.predict(named) : undefined; const prediction = predictionResult && this.config.model ? { ...predictionResult, predictionId: `prediction-${bar.symbol}-${decisionTimestamp}`, modelId: this.config.model.modelId, modelVersion: this.config.model.modelVersion, featureSetVersion: this.config.model.featureSetVersion, featureIds: this.config.model.featureIds, targetVersion: this.config.model.targetVersion } : undefined;
    const currentRegime = regime.trend; const matchRegime = this.config.regimeAnaloguePolicy === "MATCH_CURRENT_REGIME"; const analogues = prediction && this.config.trustedAnalogues?.length && this.config.analogueScalerProfile && definition ? new TrustedAnalogueEngine().query(this.config.trustedAnalogues, { currentFeatures: named, decisionTimestamp, featureSetVersion: this.config.model!.featureSetVersion, featureIds: this.config.model!.featureIds, targetVersion: definition.targetVersion, targetKind: definition.kind, scalerProfile: this.config.analogueScalerProfile, regime: matchRegime ? currentRegime : undefined, minimumSample: this.config.minimumAnalogueSample }) : undefined;
    const regimeEvidence = analogues ? assessRegimeEvidence(currentRegime, analogues.regimeCounts, this.config.minimumRegimeAnalogueSample ?? 20, this.config.minimumRegimeMatchRate ?? 0.5) : undefined;
    const evidence = analogues ? assessEvidence({ sampleSize: analogues.sampleSize, context: this.config.evidence, expectedProvenance: this.config.model ? { modelId: this.config.model.modelId, modelVersion: this.config.model.modelVersion, experimentId: this.config.evidence?.experimentId ?? "" } : undefined, regimeEvidence, required: this.config.requiredEvidencePolicy }) : undefined;
    const evReferencePrice = quote?.bid !== undefined && quote.ask !== undefined ? (quote.bid + quote.ask) / 2 : features.close; const evReferenceMethod = quote?.bid !== undefined && quote.ask !== undefined ? "QUOTE_MID" as const : "BAR_CLOSE" as const; const observedSpreadBps = quote && quote.ask > quote.bid && evReferencePrice > 0 ? (quote.ask - quote.bid) / evReferencePrice * 10_000 : undefined; const cost = this.config.costModel?.estimateRoundTrip(evReferencePrice, evReferencePrice, "BUY", observedSpreadBps ?? features.spreadBps).returnUnits ?? 0; let ev: number | undefined; let outcomeProbabilities: TripleBarrierOutcomeProbabilities | undefined; if (prediction && analogues && definition?.kind === "FORWARD_CLOSE_RETURN" && analogues.forwardReturn) ev = prediction.probability * analogues.forwardReturn.meanPositiveReturn + (1 - prediction.probability) * analogues.forwardReturn.meanNegativeReturn - cost; if (prediction && analogues && definition?.kind === "TRIPLE_BARRIER" && analogues.barrier && Number.isFinite(targetState.values.atrAtDecision)) { outcomeProbabilities = decomposeTripleBarrierProbabilities(prediction.probability, analogues.barrier, this.config.model!.labelPolicy.probabilityMeaning ?? "P_UP_OUTCOME"); const upper = (definition.upperBarrierMultiple! * targetState.values.atrAtDecision) / evReferencePrice; const lower = (definition.lowerBarrierMultiple! * targetState.values.atrAtDecision) / evReferencePrice; ev = outcomeProbabilities.up * upper + outcomeProbabilities.down * -lower + outcomeProbabilities.timeout * TRIPLE_BARRIER_TIMEOUT_RETURN + outcomeProbabilities.ambiguous * TRIPLE_BARRIER_AMBIGUOUS_RETURN - cost; }
    return { symbol: bar.symbol, barCloseTimestamp: timestamp, quoteTimestamp: quote?.ts, featureTimestamp: features.ts, decisionTimestamp, timestamp: features.ts, features, structure, regime, patterns, targetState, prediction, analogues, regimeEvidence, evidence, expectedValue: ev, expectedValueEstimate: ev === undefined ? undefined : { value: ev, unit: "RETURN", methodVersion: TRIPLE_BARRIER_EV_VERSION, referencePrice: evReferencePrice, referenceMethod: evReferenceMethod, observedSpreadBps: features.spreadBps, grossExpectedValue: ev + cost, executionCost: cost, netExpectedValue: ev, outcomeProbabilities }, evReferencePrice, evReferenceMethod, dataQuality: { ok: true, issues: targetState.status === "AVAILABLE" ? [] : [targetState.status] } };
  }
}
