import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { Bar, Quote } from "./domain";
import type { ResearchEngine } from "./engine";

export interface LocalServiceOptions { host?: string; port?: number; maxBodyBytes?: number; }
export interface LocalServiceStatus { ok: true; service: "paper-trading-lab"; safety: "PAPER_ONLY"; engine: ResearchEngine["health"]; }
type MarketEvent = { bar: Bar; quote: Quote };

async function body(request: IncomingMessage, maximum: number): Promise<unknown> { const chunks: Buffer[] = []; let length = 0; for await (const chunk of request) { const bytes = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk); length += bytes.length; if (length > maximum) throw new Error("Request body too large"); chunks.push(bytes); } return JSON.parse(Buffer.concat(chunks).toString("utf8")); }
function json(response: ServerResponse, status: number, value: unknown) { response.statusCode = status; response.setHeader("Content-Type", "application/json"); response.setHeader("Access-Control-Allow-Origin", "*"); response.end(JSON.stringify(value)); }

export class LocalPaperEngineService {
  private server?: Server;
  constructor(readonly engine: ResearchEngine, private readonly options: LocalServiceOptions = {}) {}
  async start(): Promise<void> { if (this.server) throw new Error("Service is already running"); const host = this.options.host ?? "127.0.0.1"; const port = this.options.port ?? 47821; const maximum = this.options.maxBodyBytes ?? 1_000_000; this.server = createServer(async (request, response) => { try { if (request.method === "OPTIONS") { response.statusCode = 204; response.setHeader("Access-Control-Allow-Origin", "*"); response.setHeader("Access-Control-Allow-Methods", "GET,POST,OPTIONS"); response.setHeader("Access-Control-Allow-Headers", "Content-Type"); response.end(); return; } const path = new URL(request.url ?? "/", `http://${host}`).pathname; if (request.method === "GET" && path === "/health") { json(response, 200, { ok: true, service: "paper-trading-lab", safety: "PAPER_ONLY", engine: this.engine.health } satisfies LocalServiceStatus); return; } if (request.method === "GET" && path === "/state") { json(response, 200, { ok: true, snapshot: this.engine.portfolioSnapshot(Date.now()), health: this.engine.health }); return; } if (request.method === "POST" && path === "/market-event") { const event = await body(request, maximum) as MarketEvent; this.engine.setOperationalNow(Date.now()); const signal = this.engine.onBar(event.bar, event.quote); json(response, 200, { ok: true, signal, engine: this.engine.health }); return; } if (request.method === "POST" && path === "/control/pause") { this.engine.pause(); json(response, 200, { ok: true, engine: this.engine.health }); return; } if (request.method === "POST" && path === "/control/resume") { this.engine.resume(); json(response, 200, { ok: true, engine: this.engine.health }); return; } if (request.method === "POST" && path === "/control/kill-switch") { this.engine.activateKillSwitch(); json(response, 200, { ok: true, engine: this.engine.health }); return; } if (request.method === "POST" && path === "/control/reset-kill-switch") { this.engine.resetKillSwitch(); json(response, 200, { ok: true, engine: this.engine.health }); return; } json(response, 404, { ok: false, error: "Not found" }); } catch (error) { json(response, 400, { ok: false, error: error instanceof Error ? error.message : "Request failed" }); } }); await new Promise<void>((resolve, reject) => { this.server!.once("error", reject); this.server!.listen(port, host, () => resolve()); }); }
  async stop(): Promise<void> { if (!this.server) return; const server = this.server; this.server = undefined; await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); }
  address(): { host: string; port: number } | null { const address = this.server?.address(); return address && typeof address !== "string" ? { host: address.address, port: address.port } : null; }
}
