export interface PerformanceMetrics { totalReturn: number; cagr: number; annualisedReturn: number; annualisedVolatility: number; sharpe: number; sortino: number; calmar: number; maxDrawdown: number; drawdownDuration: number; maxDrawdownDurationMs: number; expectancy: number; winRate: number; profitFactor: number; averageWinner: number; averageLoser: number; payoffRatio: number; tradeCount: number; }
const average = (xs: readonly number[]) => xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0;
const std = (xs: readonly number[]) => { if (xs.length < 2) return 0; const m = average(xs); return Math.sqrt(xs.reduce((sum, x) => sum + (x - m) ** 2, 0) / (xs.length - 1)); };
export function maximumDrawdown(equity: readonly number[]): number { let peak = -Infinity; let max = 0; for (const value of equity) { peak = Math.max(peak, value); if (peak > 0) max = Math.max(max, (peak - value) / peak); } return max; }
export function maximumDrawdownDuration(equity: readonly number[]): number { let peak = -Infinity; let current = 0; let max = 0; for (const value of equity) { if (value >= peak) { peak = value; current = 0; } else { current++; max = Math.max(max, current); } } return max; }
export function maxDrawdownDurationMs(equity: readonly { ts: number; value: number }[]): number { let peak = -Infinity; let peakTs = 0; let max = 0; for (const point of equity) { if (point.value >= peak) { peak = point.value; peakTs = point.ts; } else max = Math.max(max, point.ts - peakTs); } return max; }
export type EquityFrequency = "1m" | "5m" | "15m" | "1h" | "1d";
export interface MetricSampling { frequency: EquityFrequency; periodsPerYear: number; }
export type ResampleGapPolicy = "FORWARD_FILL_WITHIN_SESSION" | "DROP_GAPS";
export interface ResampleQuality { sessionAnchored: boolean; partialBucketCount: number; gapCount: number; gapPolicy: ResampleGapPolicy; complete: boolean; }
export interface ResampledEquityCurve { points: readonly { ts: number; value: number }[]; quality: ResampleQuality; }
const frequencyMs: Record<EquityFrequency, number> = { "1m": 60_000, "5m": 300_000, "15m": 900_000, "1h": 3_600_000, "1d": 86_400_000 };
export function approximatePeriodsPerYear(frequency: EquityFrequency, sessionMinutes = 390, sessionsPerYear = 252): number { return frequency === "1d" ? sessionsPerYear : sessionsPerYear * sessionMinutes / (frequencyMs[frequency] / 60_000); }
export function resampleEquityCurve(points: readonly { ts: number; value: number }[], frequency: EquityFrequency, calendar?: { isRegularSession(ts: number): boolean }): readonly { ts: number; value: number }[] { if (!points.length) return []; const bucket = frequencyMs[frequency]; const ordered = [...points].sort((a, b) => a.ts - b.ts).filter((point) => !calendar || calendar.isRegularSession(point.ts)); if (!ordered.length) return []; const result: { ts: number; value: number }[] = []; let currentBucket = Math.floor(ordered[0].ts / bucket); let last = ordered[0]; for (const point of ordered) { const nextBucket = Math.floor(point.ts / bucket); if (nextBucket !== currentBucket) { result.push({ ts: currentBucket * bucket, value: last.value }); if (calendar) for (let bucketIndex = currentBucket + 1; bucketIndex < nextBucket; bucketIndex++) { const bucketTs = bucketIndex * bucket; if (calendar.isRegularSession(bucketTs)) result.push({ ts: bucketTs, value: last.value }); } currentBucket = nextBucket; } last = point; } result.push({ ts: currentBucket * bucket, value: last.value }); return result; }
export function resampleEquityCurveWithQuality(points: readonly { ts: number; value: number }[], frequency: EquityFrequency, calendar: { isRegularSession(ts: number): boolean; sessionKey?: (ts: number) => string; sessionBounds?: (ts: number) => { openMs: number; closeMs: number; sessionKey: string } }, gapPolicy: ResampleGapPolicy = "FORWARD_FILL_WITHIN_SESSION"): ResampledEquityCurve { const base = resampleEquityCurve(points, frequency, calendar); const ordered = [...points].sort((a, b) => a.ts - b.ts); let gapCount = 0; for (let i = 1; i < ordered.length; i++) if (calendar.sessionKey && calendar.sessionKey(ordered[i].ts) === calendar.sessionKey(ordered[i - 1].ts) && ordered[i].ts - ordered[i - 1].ts > frequencyMs[frequency] * 1.5) gapCount++; return { points: base, quality: { sessionAnchored: Boolean(calendar.sessionBounds), partialBucketCount: base.filter((point) => calendar.sessionBounds && point.ts > calendar.sessionBounds(point.ts).openMs && point.ts < calendar.sessionBounds(point.ts).closeMs && (point.ts - calendar.sessionBounds(point.ts).openMs) % frequencyMs[frequency] !== 0).length, gapCount, gapPolicy, complete: gapCount === 0 } }; }
export function performanceMetrics(equity: readonly number[] | readonly { ts: number; value: number }[], trades: readonly number[] = [], periodsPerYear = 252, riskFreeAnnual = 0, sampling?: MetricSampling): PerformanceMetrics { const observations = equity.map((point) => typeof point === "number" ? { value: point } : point); const values = observations.map((point) => point.value); if (values.length < 2 || values[0] <= 0 || periodsPerYear <= 0 || values.some((value) => !Number.isFinite(value) || value <= 0)) throw new Error("At least two positive equity observations and a valid frequency are required"); const returns = values.slice(1).map((v, i) => v / values[i] - 1); const meanReturn = average(returns); const elapsedYears = observations.every((point) => "ts" in point) ? Math.max(1e-12, (observations.at(-1)!.ts - observations[0].ts) / (365.2425 * 24 * 60 * 60 * 1000)) : returns.length / periodsPerYear; const declaredPeriods = sampling?.periodsPerYear ?? periodsPerYear; const annualisation = Math.sqrt(declaredPeriods); const periodRiskFree = (1 + riskFreeAnnual) ** (1 / declaredPeriods) - 1; const annualisedVolatility = std(returns) * annualisation; const downsideDeviation = Math.sqrt(average(returns.map((r) => Math.min(0, r - periodRiskFree) ** 2))) || 0; const totalReturn = values.at(-1)! / values[0] - 1; const cagr = (1 + totalReturn) ** (1 / elapsedYears) - 1; const wins = trades.filter((t) => t > 0); const losses = trades.filter((t) => t < 0); const averageWinner = average(wins); const averageLoser = average(losses); const grossLoss = Math.abs(losses.reduce((a, b) => a + b, 0)); const maxDD = maximumDrawdown(values); return { totalReturn, cagr, annualisedReturn: cagr, annualisedVolatility, sharpe: std(returns) ? ((meanReturn - periodRiskFree) / std(returns)) * annualisation : 0, sortino: downsideDeviation ? ((meanReturn - periodRiskFree) / downsideDeviation) * annualisation : 0, calmar: maxDD ? cagr / maxDD : 0, maxDrawdown: maxDD, drawdownDuration: maximumDrawdownDuration(values), maxDrawdownDurationMs: observations.every((point) => "ts" in point) ? maxDrawdownDurationMs(observations as { ts: number; value: number }[]) : 0, expectancy: average(trades), winRate: trades.length ? wins.length / trades.length : 0, profitFactor: grossLoss ? wins.reduce((a, b) => a + b, 0) / grossLoss : wins.length ? Infinity : 0, averageWinner, averageLoser, payoffRatio: averageLoser ? averageWinner / Math.abs(averageLoser) : 0, tradeCount: trades.length }; }
