export interface PerformanceMetrics {
  totalReturn: number; cagr: number; annualisedReturn: number; annualisedVolatility: number;
  sharpe: number; sortino: number; calmar: number; maxDrawdown: number; drawdownDuration: number;
  expectancy: number; winRate: number; profitFactor: number; averageWinner: number; averageLoser: number; payoffRatio: number; tradeCount: number;
}
const average = (xs: readonly number[]) => xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0;
const std = (xs: readonly number[]) => { if (xs.length < 2) return 0; const m = average(xs); return Math.sqrt(xs.reduce((sum, x) => sum + (x - m) ** 2, 0) / (xs.length - 1)); };
export function maximumDrawdown(equity: readonly number[]): number { let peak = -Infinity; let max = 0; for (const value of equity) { peak = Math.max(peak, value); if (peak > 0) max = Math.max(max, (peak - value) / peak); } return max; }
export function maximumDrawdownDuration(equity: readonly number[]): number { let peak = -Infinity; let current = 0; let max = 0; for (const value of equity) { if (value >= peak) { peak = value; current = 0; } else { current++; max = Math.max(max, current); } } return max; }
export function performanceMetrics(equity: readonly number[], trades: readonly number[] = [], periodsPerYear = 252, riskFreeAnnual = 0): PerformanceMetrics {
  if (equity.length < 2 || equity[0] <= 0 || periodsPerYear <= 0) throw new Error("At least two positive equity observations and a valid frequency are required");
  const returns = equity.slice(1).map((v, i) => v / equity[i] - 1); const meanReturn = average(returns); const periodRiskFree = (1 + riskFreeAnnual) ** (1 / periodsPerYear) - 1; const annualisedVolatility = std(returns) * Math.sqrt(periodsPerYear); const downsideDeviation = Math.sqrt(average(returns.map((r) => Math.min(0, r - periodRiskFree) ** 2))) || 0; const totalReturn = equity.at(-1)! / equity[0] - 1; const years = returns.length / periodsPerYear; const cagr = (1 + totalReturn) ** (1 / years) - 1; const wins = trades.filter((t) => t > 0); const losses = trades.filter((t) => t < 0); const averageWinner = average(wins); const averageLoser = average(losses); const grossLoss = Math.abs(losses.reduce((a, b) => a + b, 0)); const maxDD = maximumDrawdown(equity);
  return { totalReturn, cagr, annualisedReturn: meanReturn * periodsPerYear, annualisedVolatility, sharpe: std(returns) ? ((meanReturn - periodRiskFree) / std(returns)) * Math.sqrt(periodsPerYear) : 0, sortino: downsideDeviation ? ((meanReturn - periodRiskFree) / downsideDeviation) * Math.sqrt(periodsPerYear) : 0, calmar: maxDD ? cagr / maxDD : 0, maxDrawdown: maxDD, drawdownDuration: maximumDrawdownDuration(equity), expectancy: average(trades), winRate: trades.length ? wins.length / trades.length : 0, profitFactor: grossLoss ? wins.reduce((a, b) => a + b, 0) / grossLoss : wins.length ? Infinity : 0, averageWinner, averageLoser, payoffRatio: averageLoser ? averageWinner / Math.abs(averageLoser) : 0, tradeCount: trades.length };
}
