export interface PerformanceMetrics { totalReturn: number; annualisedReturn: number; annualisedVolatility: number; sharpe: number; sortino: number; maxDrawdown: number; expectancy: number; winRate: number; profitFactor: number; tradeCount: number; }
const average = (xs: readonly number[]) => xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0;
const deviation = (xs: readonly number[]) => { if (xs.length < 2) return 0; const m = average(xs); return Math.sqrt(average(xs.map((x) => (x - m) ** 2))); };
export function maximumDrawdown(equity: readonly number[]): number { let peak = -Infinity; let max = 0; for (const value of equity) { peak = Math.max(peak, value); if (peak > 0) max = Math.max(max, (peak - value) / peak); } return max; }
export function performanceMetrics(equity: readonly number[], trades: readonly number[] = [], periodsPerYear = 252): PerformanceMetrics {
  if (equity.length < 2 || equity[0] <= 0) throw new Error("At least two positive equity observations are required");
  const returns = equity.slice(1).map((v, i) => v / equity[i] - 1); const years = returns.length / periodsPerYear; const totalReturn = equity.at(-1)! / equity[0] - 1; const annualisedReturn = years > 0 ? (1 + totalReturn) ** (1 / years) - 1 : 0; const vol = deviation(returns) * Math.sqrt(periodsPerYear); const downside = deviation(returns.filter((r) => r < 0)) * Math.sqrt(periodsPerYear); const wins = trades.filter((t) => t > 0); const losses = trades.filter((t) => t < 0); const grossLoss = Math.abs(losses.reduce((a, b) => a + b, 0));
  return { totalReturn, annualisedReturn, annualisedVolatility: vol, sharpe: vol ? average(returns) * Math.sqrt(periodsPerYear) / vol : 0, sortino: downside ? average(returns) * Math.sqrt(periodsPerYear) / downside : 0, maxDrawdown: maximumDrawdown(equity), expectancy: average(trades), winRate: trades.length ? wins.length / trades.length : 0, profitFactor: grossLoss ? wins.reduce((a, b) => a + b, 0) / grossLoss : wins.length ? Infinity : 0, tradeCount: trades.length };
}
