import { selectNamedFeatures, type FeatureId, type NamedFeatureVector } from "./feature-schema";
import { transformWithScaler, type ScalerState } from "./ml";

export interface CalibratorState { slope: number; intercept: number; fittedRows: number; }
export interface PredictiveModelArtifact { modelId: string; modelVersion: string; featureSetVersion: string; featureIds: readonly FeatureId[]; targetVersion: string; scalerState: ScalerState; modelState: { weights: readonly number[]; bias: number }; calibratorState?: CalibratorState; oodProfile?: { means: readonly number[]; scales: readonly number[] }; createdAt: number; }
const sigmoid = (x: number) => x >= 0 ? 1 / (1 + Math.exp(-x)) : Math.exp(x) / (1 + Math.exp(x));
export class PredictiveModelBundle {
  constructor(readonly artifact: PredictiveModelArtifact) { if (artifact.featureIds.length !== artifact.modelState.weights.length || artifact.featureIds.length !== artifact.scalerState.means.length) throw new Error("Model feature schema width mismatch"); if (new Set(artifact.featureIds).size !== artifact.featureIds.length) throw new Error("Model feature IDs must be unique"); }
  predict(features: NamedFeatureVector) { const selected = selectNamedFeatures(features, this.artifact.featureIds); const scaled = transformWithScaler(selected, this.artifact.scalerState); const raw = sigmoid(this.artifact.modelState.bias + scaled.reduce((sum, value, index) => sum + value * this.artifact.modelState.weights[index], 0)); const calibrated = this.artifact.calibratorState ? sigmoid(this.artifact.calibratorState.intercept + this.artifact.calibratorState.slope * Math.log(raw / (1 - raw))) : undefined; return { rawProbability: raw, calibratedProbability: calibrated, probability: calibrated ?? raw }; }
}
export function expectedCalibrationError(labels: readonly (0 | 1)[], probabilities: readonly number[], binCount = 10): number { if (labels.length !== probabilities.length || !labels.length) throw new Error("Calibration inputs must be non-empty and equal length"); let total = 0; for (let bin = 0; bin < binCount; bin++) { const selected = probabilities.map((probability, index) => ({ probability, label: labels[index] })).filter(({ probability }) => probability >= bin / binCount && probability < (bin + 1) / binCount || bin === binCount - 1 && probability <= 1); if (selected.length) total += selected.length / labels.length * Math.abs(selected.reduce((sum, item) => sum + item.probability, 0) / selected.length - selected.reduce((sum, item) => sum + item.label, 0) / selected.length); } return total; }
export function fitPlattCalibrator(labels: readonly (0 | 1)[], rawProbabilities: readonly number[]): CalibratorState { if (labels.length !== rawProbabilities.length || labels.length < 2) throw new Error("Calibration requires at least two rows"); let slope = 1; let intercept = 0; for (let epoch = 0; epoch < 500; epoch++) { let gs = 0; let gi = 0; for (let i = 0; i < labels.length; i++) { const logit = Math.log(Math.min(1 - 1e-12, Math.max(1e-12, rawProbabilities[i])) / Math.max(1e-12, 1 - rawProbabilities[i])); const error = sigmoid(intercept + slope * logit) - labels[i]; gs += error * logit; gi += error; } slope -= 0.01 * gs / labels.length; intercept -= 0.01 * gi / labels.length; } return { slope, intercept, fittedRows: labels.length }; }
