export interface DatasetRow { symbol: string; decisionTimestamp: number; featureTimestamp?: number; targetStartTimestamp?: number; targetEndTimestamp?: number; features: readonly number[]; label: 0 | 1; split: "TRAIN" | "VALIDATION" | "CALIBRATION" | "TEST"; }
export type TrainingDataset = Readonly<{ role: "TRAIN"; rows: readonly DatasetRow[] }>;
export type ValidationDataset = Readonly<{ role: "VALIDATION"; rows: readonly DatasetRow[] }>;
export type CalibrationDataset = Readonly<{ role: "CALIBRATION"; rows: readonly DatasetRow[] }>;
export type TestDataset = Readonly<{ role: "TEST"; rows: readonly DatasetRow[] }>;
export function trainingDataset(rows: readonly DatasetRow[]): TrainingDataset { if (!rows.length || rows.some((row) => row.split !== "TRAIN")) throw new Error("TrainingDataset may contain TRAIN rows only"); return { role: "TRAIN", rows: structuredClone(rows) }; }
export function calibrationDataset(rows: readonly DatasetRow[]): CalibrationDataset { if (!rows.length || rows.some((row) => row.split !== "CALIBRATION")) throw new Error("CalibrationDataset may contain CALIBRATION rows only"); return { role: "CALIBRATION", rows: structuredClone(rows) }; }
export function validationDataset(rows: readonly DatasetRow[]): ValidationDataset { if (!rows.length || rows.some((row) => row.split !== "VALIDATION")) throw new Error("ValidationDataset may contain VALIDATION rows only"); return { role: "VALIDATION", rows: structuredClone(rows) }; }
export function testDataset(rows: readonly DatasetRow[]): TestDataset { if (!rows.length || rows.some((row) => row.split !== "TEST")) throw new Error("TestDataset may contain TEST rows only"); return { role: "TEST", rows: structuredClone(rows) }; }
export type DatasetSplit = "TRAIN" | "VALIDATION" | "CALIBRATION" | "TEST";
export interface LabelPolicy { version: string; description: string; }
export interface DatasetObservation { observationId: string; symbol: string; featureTimestamp: number; decisionTimestamp: number; targetStartTimestamp: number; targetEndTimestamp: number; featureSetVersion: string; featureIds: readonly string[]; targetVersion: string; targetKind: "FORWARD_CLOSE_RETURN" | "TRIPLE_BARRIER"; namedFeatures: Readonly<Record<string, number>>; label: 0 | 1; labelPolicy: LabelPolicy; split: DatasetSplit; }
export type DatasetIntegrityMode = "STRICT_REJECT" | "PURGE_OVERLAP";
export function validateDatasetIntegrity(observations: readonly DatasetObservation[], mode: DatasetIntegrityMode = "STRICT_REJECT"): readonly DatasetObservation[] { if (!observations.length) throw new Error("Dataset cannot be empty"); const ids = new Set<string>(); const schemas = new Set<string>(); const targets = new Set<string>(); const policies = new Set<string>(); for (const observation of observations) { if (ids.has(observation.observationId)) throw new Error("Dataset observation IDs must be unique"); ids.add(observation.observationId); if (![observation.featureTimestamp, observation.decisionTimestamp, observation.targetStartTimestamp, observation.targetEndTimestamp].every(Number.isFinite) || observation.featureTimestamp > observation.decisionTimestamp || observation.targetStartTimestamp < observation.decisionTimestamp || observation.targetEndTimestamp <= observation.targetStartTimestamp) throw new Error("Dataset observation timestamps are invalid"); if (new Set(observation.featureIds).size !== observation.featureIds.length || observation.featureIds.some((id) => !(id in observation.namedFeatures) || !Number.isFinite(observation.namedFeatures[id]))) throw new Error("Dataset named feature schema is invalid"); schemas.add(`${observation.featureSetVersion}:${observation.featureIds.join("|")}`); targets.add(observation.targetVersion); policies.add(observation.labelPolicy.version); } if (schemas.size !== 1 || targets.size !== 1 || policies.size !== 1) throw new Error("Dataset provenance must be uniform"); const ordered = [...observations].sort((a, b) => a.decisionTimestamp - b.decisionTimestamp); const result = ordered.filter((observation) => { const prior = ordered.filter((candidate) => candidate.split !== observation.split && candidate.decisionTimestamp < observation.decisionTimestamp && candidate.targetEndTimestamp > observation.decisionTimestamp && (["TRAIN", "VALIDATION", "CALIBRATION"] as readonly string[]).includes(candidate.split)); if (prior.length && mode === "STRICT_REJECT") throw new Error("Dataset target windows overlap protected split boundaries"); return !prior.length || mode === "STRICT_REJECT"; }); return mode === "PURGE_OVERLAP" ? result : ordered; }
export const MODEL_FEATURE_VERSION = "baseline-v1";
export interface ScalerState { means: readonly number[]; scales: readonly number[]; fittedRows: number; }

export function transformWithScaler(row: readonly number[], state: ScalerState): number[] { if (row.length !== state.means.length || row.some((value) => !Number.isFinite(value))) throw new Error("Invalid row for scaler"); return row.map((value, index) => (value - state.means[index]) / (state.scales[index] || 1)); }

export class StandardScaler {
  private state?: ScalerState;
  fitTraining(dataset: TrainingDataset) { return this.unsafeFitRaw(dataset.rows.map((row) => row.features)); }
  unsafeFitRaw(rows: readonly (readonly number[])[]) { if (!rows.length) throw new Error("Cannot fit scaler on empty training data"); const width = rows[0].length; if (!width || rows.some((row) => row.length !== width || row.some((value) => !Number.isFinite(value)))) throw new Error("Scaler requires finite equal-width rows"); const means = Array.from({ length: width }, (_, column) => rows.reduce((sum, row) => sum + row[column], 0) / rows.length); const scales = means.map((mean, column) => { const variance = rows.reduce((sum, row) => sum + (row[column] - mean) ** 2, 0) / rows.length; return Math.sqrt(variance) || 1; }); this.state = { means, scales, fittedRows: rows.length }; return this; }
  transform(row: readonly number[]): number[] { if (!this.state) throw new Error("Scaler has not been fitted"); return transformWithScaler(row, this.state); }
  transformRows(rows: readonly (readonly number[])[]) { return rows.map((row) => this.transform(row)); }
  metadata() { if (!this.state) throw new Error("Scaler has not been fitted"); return structuredClone(this.state); }
}

export interface PreparedDataset { train: readonly DatasetRow[]; validation: readonly DatasetRow[]; calibration: readonly DatasetRow[]; test: readonly DatasetRow[]; scaler: ScalerState; }
export function prepareDataset(rows: readonly DatasetRow[]): PreparedDataset { if (rows.some((row) => !Number.isFinite(row.decisionTimestamp) || row.features.some((value) => !Number.isFinite(value)))) throw new Error("Dataset timestamps and features must be finite"); const ordered = [...rows].sort((a, b) => a.decisionTimestamp - b.decisionTimestamp); const train = ordered.filter((row) => row.split === "TRAIN"); const validation = ordered.filter((row) => row.split === "VALIDATION"); const calibration = ordered.filter((row) => row.split === "CALIBRATION"); const test = ordered.filter((row) => row.split === "TEST"); if (!train.length) throw new Error("Training split is required"); const chronological = [[train, validation], [validation, calibration], [calibration, test]] as const; for (const [previous, next] of chronological) { if (previous.length && next.length) { const previousDecision = previous.at(-1)!.decisionTimestamp; const nextDecision = next[0].decisionTimestamp; const previousTargetEnd = Math.max(previousDecision, ...previous.map((row) => row.targetEndTimestamp ?? previousDecision)); if (nextDecision <= previousDecision || nextDecision <= previousTargetEnd) throw new Error("Dataset splits must be chronological and target windows must not overlap"); } } const scaler = new StandardScaler().unsafeFitRaw(train.map((row) => row.features)); const transform = (split: DatasetRow["split"]) => ordered.filter((row) => row.split === split).map((row) => ({ ...row, features: scaler.transform(row.features) })); return { train: transform("TRAIN"), validation: transform("VALIDATION"), calibration: transform("CALIBRATION"), test: transform("TEST"), scaler: scaler.metadata() }; }

const sigmoid = (value: number) => value >= 0 ? 1 / (1 + Math.exp(-value)) : Math.exp(value) / (1 + Math.exp(value));
export interface LogisticConfig { learningRate?: number; epochs?: number; l2?: number; }
export interface PlattCalibratorState { slope: number; intercept: number; fittedRows: number; }
export class PlattCalibrator { private state?: PlattCalibratorState; fit(dataset: CalibrationDataset, rawProbabilities: readonly number[], epochs = 500, learningRate = 0.05): this { if (dataset.rows.length !== rawProbabilities.length || !dataset.rows.length || rawProbabilities.some((p) => p <= 0 || p >= 1 || !Number.isFinite(p))) throw new Error("Platt calibration requires finite calibration probabilities"); let slope = 1; let intercept = 0; for (let epoch = 0; epoch < epochs; epoch++) { let slopeGradient = 0; let interceptGradient = 0; dataset.rows.forEach((row, index) => { const logit = Math.log(rawProbabilities[index] / (1 - rawProbabilities[index])); const probability = sigmoid(intercept + slope * logit); const error = probability - row.label; slopeGradient += error * logit; interceptGradient += error; }); slope -= learningRate * slopeGradient / dataset.rows.length; intercept -= learningRate * interceptGradient / dataset.rows.length; } this.state = { slope, intercept, fittedRows: dataset.rows.length }; return this; } transform(rawProbability: number): number { if (!this.state || rawProbability <= 0 || rawProbability >= 1) throw new Error("Calibrator is not fitted or probability is invalid"); return sigmoid(this.state.intercept + this.state.slope * Math.log(rawProbability / (1 - rawProbability))); } metadata(): PlattCalibratorState { if (!this.state) throw new Error("Calibrator is not fitted"); return structuredClone(this.state); } }
export class LogisticRegression {
  readonly algorithm = "logistic-regression";
  private weights: number[] = [];
  private bias = 0;
  fit(dataset: TrainingDataset, config: LogisticConfig = {}) { return this.unsafeFitRaw(dataset.rows, config); }
  unsafeFitRaw(rows: readonly DatasetRow[], config: LogisticConfig = {}) { if (!rows.length) throw new Error("Cannot fit logistic regression on empty data"); if (rows.some((row) => row.split !== "TRAIN")) throw new Error("Logistic regression may only fit TRAIN rows"); const width = rows[0].features.length; if (!width || rows.some((row) => row.features.length !== width)) throw new Error("Feature widths do not match"); const learningRate = config.learningRate ?? 0.1; const epochs = config.epochs ?? 500; const l2 = config.l2 ?? 0.01; this.weights = Array(width).fill(0); this.bias = 0; for (let epoch = 0; epoch < epochs; epoch++) { const gradient = Array(width).fill(0); let biasGradient = 0; for (const row of rows) { const prediction = this.predictProbability(row.features); const error = prediction - row.label; row.features.forEach((value, index) => { gradient[index] += error * value; }); biasGradient += error; } this.weights = this.weights.map((weight, index) => weight - learningRate * (gradient[index] / rows.length + l2 * weight)); this.bias -= learningRate * biasGradient / rows.length; } return this; }
  predictProbability(features: readonly number[]) { if (!this.weights.length || features.length !== this.weights.length) throw new Error("Model is not fitted or feature width is invalid"); return sigmoid(this.bias + features.reduce((sum, value, index) => sum + value * this.weights[index], 0)); }
  predict(features: readonly number[], threshold = 0.5): 0 | 1 { return this.predictProbability(features) >= threshold ? 1 : 0; }
  metadata() { if (!this.weights.length) throw new Error("Model is not fitted"); return { algorithm: this.algorithm, weights: [...this.weights], bias: this.bias }; }
}

export interface ModelArtifact { artifactId: string; modelId: string; modelVersion: string; algorithm: string; featureVersion: string; featureSetVersion: string; featureIds: readonly string[]; targetVersion: string; scaler: ScalerState; model: { weights: readonly number[]; bias: number }; calibratorState?: { slope: number; intercept: number; fittedRows: number }; oodProfile: OodProfile; createdAt: number; trainStart: number; trainEnd: number; validationStart: number; validationEnd: number; calibrationStart: number; calibrationEnd: number; testStart: number; testEnd: number; datasetId: string; datasetVersion: string; labelPolicyVersion: string; experimentId: string; }

export interface ClassificationMetrics { logLoss: number; brier: number; accuracy: number; precision: number; recall: number; f1: number; confusion: { truePositive: number; trueNegative: number; falsePositive: number; falseNegative: number }; }
export function classificationMetrics(labels: readonly (0 | 1)[], probabilities: readonly number[], threshold = 0.5): ClassificationMetrics { if (labels.length !== probabilities.length || !labels.length) throw new Error("Labels and probabilities must be non-empty and equal length"); let tp = 0; let tn = 0; let fp = 0; let fn = 0; let logLoss = 0; let brier = 0; labels.forEach((label, index) => { const p = Math.min(1 - 1e-15, Math.max(1e-15, probabilities[index])); logLoss += -(label * Math.log(p) + (1 - label) * Math.log(1 - p)); brier += (p - label) ** 2; const prediction = p >= threshold ? 1 : 0; if (prediction && label) tp++; else if (!prediction && !label) tn++; else if (prediction) fp++; else fn++; }); const precision = tp + fp ? tp / (tp + fp) : 0; const recall = tp + fn ? tp / (tp + fn) : 0; return { logLoss: logLoss / labels.length, brier: brier / labels.length, accuracy: (tp + tn) / labels.length, precision, recall, f1: precision + recall ? 2 * precision * recall / (precision + recall) : 0, confusion: { truePositive: tp, trueNegative: tn, falsePositive: fp, falseNegative: fn } }; }

export interface CalibrationBin { lower: number; upper: number; meanPredicted: number; eventRate: number; count: number; }
export function calibrationBins(labels: readonly (0 | 1)[], probabilities: readonly number[], binCount = 10): readonly CalibrationBin[] { if (labels.length !== probabilities.length || binCount <= 0) throw new Error("Invalid calibration inputs"); return Array.from({ length: binCount }, (_, index) => { const lower = index / binCount; const upper = (index + 1) / binCount; const selected = probabilities.map((probability, row) => ({ probability, label: labels[row] })).filter(({ probability }) => probability >= lower && (index === binCount - 1 ? probability <= upper : probability < upper)); return { lower, upper, meanPredicted: selected.length ? selected.reduce((sum, item) => sum + item.probability, 0) / selected.length : Number.NaN, eventRate: selected.length ? selected.reduce((sum, item) => sum + item.label, 0) / selected.length : Number.NaN, count: selected.length }; }); }

export interface OodProfile { featureSetVersion?: string; featureIds?: readonly string[]; means: readonly number[]; scales: readonly number[]; minimums: readonly number[]; maximums: readonly number[]; }
export type OodStatus = "IN_DISTRIBUTION" | "WARNING" | "OUT_OF_DISTRIBUTION";
export function fitOodProfile(rows: readonly (readonly number[])[]): OodProfile { const scaler = new StandardScaler().unsafeFitRaw(rows); const metadata = scaler.metadata(); return { means: metadata.means, scales: metadata.scales, minimums: rows[0].map((_, column) => Math.min(...rows.map((row) => row[column]))), maximums: rows[0].map((_, column) => Math.max(...rows.map((row) => row[column]))) }; }
export function assessOod(row: readonly number[], profile: OodProfile, warningZ = 2, outZ = 4): { status: OodStatus; maxAbsZ: number } { if (row.length !== profile.means.length || row.some((value) => !Number.isFinite(value))) throw new Error("OOD feature width or value is invalid"); const zScores = row.map((value, index) => Math.abs((value - profile.means[index]) / (profile.scales[index] || 1))); const maxAbsZ = Math.max(...zScores); return { status: maxAbsZ >= outZ ? "OUT_OF_DISTRIBUTION" : maxAbsZ >= warningZ ? "WARNING" : "IN_DISTRIBUTION", maxAbsZ }; }

import { selectNamedFeatures, type NamedFeatureVector } from "./feature-schema";
export interface ModelPrediction { rawProbability: number; calibratedProbability: number; probability: number; ood: { status: OodStatus; maxAbsZ: number }; }
export class PredictiveModelBundle {
  readonly modelId: string; readonly modelVersion: string; readonly featureSetVersion: string; readonly featureIds: readonly string[]; readonly targetVersion: string;
  constructor(readonly artifact: ModelArtifact) {
    if (artifact.algorithm !== "logistic-regression" || artifact.model.weights.length !== artifact.scaler.means.length) throw new Error("Incompatible logistic model artifact");
    if (!artifact.modelId || !artifact.modelVersion || !artifact.featureSetVersion || !artifact.featureIds.length || !artifact.targetVersion) throw new Error("Model provenance is incomplete");
    if (new Set(artifact.featureIds).size !== artifact.featureIds.length || artifact.featureIds.length !== artifact.model.weights.length) throw new Error("Model feature schema is invalid");
    if (artifact.oodProfile.featureSetVersion !== artifact.featureSetVersion || artifact.oodProfile.featureIds?.join("\u0000") !== artifact.featureIds.join("\u0000")) throw new Error("OOD profile schema does not match model schema");
    this.modelId = artifact.modelId; this.modelVersion = artifact.modelVersion; this.featureSetVersion = artifact.featureSetVersion; this.featureIds = [...artifact.featureIds]; this.targetVersion = artifact.targetVersion;
  }
  predict(features: NamedFeatureVector): ModelPrediction {
    const raw = selectNamedFeatures(features, this.featureIds); const ood = assessOod(raw, this.artifact.oodProfile); const scaled = transformWithScaler(raw, this.artifact.scaler); const rawProbability = sigmoid(this.artifact.model.bias + scaled.reduce((sum, value, index) => sum + value * this.artifact.model.weights[index], 0));
    const calibratedProbability = this.artifact.calibratorState ? sigmoid(this.artifact.calibratorState.intercept + this.artifact.calibratorState.slope * Math.log(rawProbability / (1 - rawProbability))) : rawProbability;
    return { rawProbability, calibratedProbability, probability: calibratedProbability, ood };
  }
  metadata() { return structuredClone(this.artifact); }
}
export function expectedCalibrationError(labels: readonly (0 | 1)[], probabilities: readonly number[], binCount = 10): number { const bins = calibrationBins(labels, probabilities, binCount); return bins.reduce((sum, bin) => sum + (bin.count ? bin.count / labels.length * Math.abs(bin.meanPredicted - bin.eventRate) : 0), 0); }
