export type ModelLifecycle = "CANDIDATE" | "VALIDATED" | "ACTIVE" | "REJECTED" | "RETIRED";
export interface ModelEvaluationReport { sampleSize: number; brier: number; logLoss: number; ece: number; expectedValue: number; maxDrawdown: number; walkForwardStatus: "NOT_TESTED" | "INSUFFICIENT_SAMPLE" | "PASSED" | "FAILED" | "DEGRADED"; costStressStatus: "NOT_TESTED" | "INSUFFICIENT_SAMPLE" | "PASSED" | "FAILED" | "DEGRADED"; regimeCoverage: string; parameterStability: string; }
export interface LifecycleEvent { lifecycle: ModelLifecycle; timestamp: number; reason?: string; }
export interface ModelRecord { modelId: string; version: string; artifactId?: string; algorithm: string; featureVersion: string; datasetVersion: string; metrics: Readonly<Record<string, number>>; lifecycle: ModelLifecycle; createdAt: number; evaluation?: ModelEvaluationReport; lifecycleHistory?: readonly LifecycleEvent[]; statusReason?: string; }
export type PromotionDecision = "PROMOTE" | "KEEP_ACTIVE" | "REJECT_CANDIDATE";
export interface PromotionPolicy { minimumSampleSize: number; maxBrierRegression: number; maxLogLossRegression: number; maxEceRegression: number; minimumExpectedValueImprovement: number; maxDrawdownRegression: number; requireWalkForwardPass: boolean; requireCostStressPass: boolean; }
export const defaultPromotionPolicy: PromotionPolicy = { minimumSampleSize: 30, maxBrierRegression: 0, maxLogLossRegression: 0, maxEceRegression: 0, minimumExpectedValueImprovement: 0, maxDrawdownRegression: 0, requireWalkForwardPass: true, requireCostStressPass: true };
export interface PromotionReport { modelId: string; candidateModelId?: string; candidateVersion?: string; candidateArtifactId?: string; activeModelId?: string; activeVersion?: string; activeArtifactId?: string; decision: PromotionDecision; candidate?: ModelEvaluationReport; active?: ModelEvaluationReport; eligible: boolean; reasons: readonly string[]; }
export interface RegistryClock { now(): number; }
export const systemRegistryClock: RegistryClock = { now: () => Date.now() };
export class ManualClock implements RegistryClock {
  constructor(private timestamp = 0) {}
  now() { return this.timestamp; }
  set(timestamp: number) { if (!Number.isFinite(timestamp)) throw new Error("Manual clock timestamp must be finite"); this.timestamp = timestamp; }
  advance(deltaMs: number) { if (!Number.isFinite(deltaMs)) throw new Error("Manual clock delta must be finite"); this.timestamp += deltaMs; }
}
const key = (id: string, version: string) => `${id}::${version}`;
export class ModelRegistry {
  private readonly models = new Map<string, ModelRecord>();
  constructor(private readonly clock: RegistryClock = systemRegistryClock) {}
  private record(model: ModelRecord, reason?: string) { model.lifecycleHistory = [...(model.lifecycleHistory ?? []), { lifecycle: model.lifecycle, timestamp: this.clock.now(), reason }]; if (reason) model.statusReason = reason; }
  register(model: ModelRecord): void { const modelKey = key(model.modelId, model.version); if (this.models.has(modelKey)) throw new Error(`Duplicate model version: ${model.modelId}@${model.version}`); if (model.lifecycle === "ACTIVE" && [...this.models.values()].some((item) => item.lifecycle === "ACTIVE")) throw new Error("Only one active model is permitted"); const copy = structuredClone(model); this.record(copy); this.models.set(modelKey, copy); }
  get(modelId: string, version?: string): ModelRecord | undefined { const matches = [...this.models.values()].filter((model) => model.modelId === modelId && (version === undefined || model.version === version)); if (matches.length !== 1) return undefined; return structuredClone(matches[0]); }
  versions(modelId: string): readonly ModelRecord[] { return [...this.models.values()].filter((model) => model.modelId === modelId).map((model) => structuredClone(model)); }
  active(): ModelRecord | undefined { const model = [...this.models.values()].find((item) => item.lifecycle === "ACTIVE"); return model ? structuredClone(model) : undefined; }
  markValidated(modelId: string, version?: string): ModelRecord { const model = this.must(modelId, version); if (model.lifecycle !== "CANDIDATE") throw new Error("Only candidates can be validated"); model.lifecycle = "VALIDATED"; this.record(model); return structuredClone(model); }
  reject(modelId: string, reason: string, version?: string): ModelRecord { const model = this.must(modelId, version); if (!["CANDIDATE", "VALIDATED"].includes(model.lifecycle)) throw new Error("Model cannot be rejected from its current lifecycle"); model.lifecycle = "REJECTED"; this.record(model, reason); return structuredClone(model); }
  retire(modelId: string, version?: string): ModelRecord { const model = this.must(modelId, version); if (model.lifecycle !== "ACTIVE") throw new Error("Only active models can be retired"); model.lifecycle = "RETIRED"; this.record(model); return structuredClone(model); }
  promote(modelId: string, policy: PromotionPolicy = defaultPromotionPolicy, version?: string): ModelRecord { const candidate = this.must(modelId, version); if (!["CANDIDATE", "VALIDATED"].includes(candidate.lifecycle)) throw new Error("Only a candidate or validated model can be promoted"); if (this.promotionReport(modelId, policy, candidate.version).decision !== "PROMOTE") throw new Error("Candidate does not meet promotion decision"); for (const model of this.models.values()) if (model.lifecycle === "ACTIVE") { model.lifecycle = "RETIRED"; this.record(model, "Superseded by promoted model"); } candidate.lifecycle = "ACTIVE"; this.record(candidate); return structuredClone(candidate); }
  promotionReport(modelId: string, policy: PromotionPolicy = defaultPromotionPolicy, version?: string): PromotionReport { const candidate = this.must(modelId, version); const active = [...this.models.values()].find((model) => model.lifecycle === "ACTIVE"); const reasons: string[] = []; const report = candidate.evaluation; if (!report) reasons.push("Missing evaluation report"); else { if (report.sampleSize < policy.minimumSampleSize) reasons.push("Insufficient sample"); if (policy.requireWalkForwardPass && report.walkForwardStatus !== "PASSED") reasons.push("Walk-forward validation not passed"); if (policy.requireCostStressPass && report.costStressStatus !== "PASSED") reasons.push("Cost stress not passed"); if (report.regimeCoverage === "FAILED") reasons.push("Regime coverage failed"); if (report.parameterStability === "FAILED") reasons.push("Parameter stability failed"); } if (!reasons.length && active?.evaluation && report && (report.brier > active.evaluation.brier + policy.maxBrierRegression || report.logLoss > active.evaluation.logLoss + policy.maxLogLossRegression || report.ece > active.evaluation.ece + policy.maxEceRegression || report.expectedValue < active.evaluation.expectedValue + policy.minimumExpectedValueImprovement || report.maxDrawdown > active.evaluation.maxDrawdown + policy.maxDrawdownRegression)) reasons.push("Candidate is outside promotion tolerances"); const decision = reasons.length ? (active && reasons.includes("Candidate is outside promotion tolerances") ? "KEEP_ACTIVE" : "REJECT_CANDIDATE") : "PROMOTE"; return { modelId, candidateModelId: candidate.modelId, candidateVersion: candidate.version, candidateArtifactId: candidate.artifactId, activeModelId: active?.modelId, activeVersion: active?.version, activeArtifactId: active?.artifactId, decision, candidate: report, active: active?.evaluation, eligible: decision === "PROMOTE", reasons }; }
  all(): readonly ModelRecord[] { return [...this.models.values()].map((model) => structuredClone(model)); }
  private must(modelId: string, version?: string): ModelRecord { const matches = [...this.models.values()].filter((model) => model.modelId === modelId && (version === undefined || model.version === version)); if (matches.length !== 1) throw new Error(version ? `Unknown model version: ${modelId}@${version}` : `Model id is ambiguous or unknown: ${modelId}`); return matches[0]; }
}
