export type ModelLifecycle = "CANDIDATE" | "VALIDATED" | "ACTIVE" | "REJECTED" | "RETIRED";
export interface ModelEvaluationReport { sampleSize: number; brier: number; logLoss: number; ece: number; expectedValue: number; maxDrawdown: number; walkForwardStatus: "NOT_TESTED" | "INSUFFICIENT_SAMPLE" | "PASSED" | "FAILED" | "DEGRADED"; costStressStatus: "NOT_TESTED" | "INSUFFICIENT_SAMPLE" | "PASSED" | "FAILED" | "DEGRADED"; regimeCoverage: string; parameterStability: string; }
export interface ModelRecord { modelId: string; version: string; algorithm: string; featureVersion: string; datasetVersion: string; metrics: Readonly<Record<string, number>>; lifecycle: ModelLifecycle; createdAt: number; evaluation?: ModelEvaluationReport; }
export type PromotionDecision = "PROMOTE" | "KEEP_ACTIVE" | "REJECT_CANDIDATE";
export interface PromotionReport { modelId: string; decision: PromotionDecision; candidate?: ModelEvaluationReport; active?: ModelEvaluationReport; eligible: boolean; reasons: readonly string[]; }
export class ModelRegistry {
  private readonly models = new Map<string, ModelRecord>();
  register(model: ModelRecord): void { if (this.models.has(model.modelId)) throw new Error(`Duplicate model id: ${model.modelId}`); if (model.lifecycle === "ACTIVE" && [...this.models.values()].some((item) => item.lifecycle === "ACTIVE")) throw new Error("Only one active model is permitted"); this.models.set(model.modelId, structuredClone(model)); }
  get(modelId: string): ModelRecord | undefined { const model = this.models.get(modelId); return model ? structuredClone(model) : undefined; }
  active(): ModelRecord | undefined { const model = [...this.models.values()].find((item) => item.lifecycle === "ACTIVE"); return model ? structuredClone(model) : undefined; }
  promote(modelId: string): ModelRecord { const candidate = this.models.get(modelId); if (!candidate || !["CANDIDATE", "VALIDATED"].includes(candidate.lifecycle)) throw new Error("Only a candidate or validated model can be promoted"); const report = this.promotionReport(modelId); if (report.decision !== "PROMOTE") throw new Error("Candidate does not meet promotion decision"); for (const model of this.models.values()) if (model.lifecycle === "ACTIVE") model.lifecycle = "RETIRED"; candidate.lifecycle = "ACTIVE"; return structuredClone(candidate); }
  promotionReport(modelId: string): PromotionReport { const candidate = this.models.get(modelId); if (!candidate) throw new Error("Unknown model"); const active = [...this.models.values()].find((model) => model.lifecycle === "ACTIVE"); const reasons: string[] = []; const report = candidate.evaluation; if (!report) reasons.push("Missing evaluation report"); else { if (report.sampleSize <= 0) reasons.push("Insufficient sample"); if (report.walkForwardStatus !== "PASSED") reasons.push("Walk-forward validation not passed"); if (report.costStressStatus !== "PASSED") reasons.push("Cost stress not passed"); if (report.regimeCoverage === "FAILED") reasons.push("Regime coverage failed"); if (report.parameterStability === "FAILED") reasons.push("Parameter stability failed"); } if (candidate.lifecycle === "REJECTED" || candidate.lifecycle === "RETIRED") reasons.push("Model is not promotable"); if (!reasons.length && active?.evaluation && report && (report.brier >= active.evaluation.brier || report.logLoss >= active.evaluation.logLoss || report.ece > active.evaluation.ece || report.expectedValue < active.evaluation.expectedValue || report.maxDrawdown > active.evaluation.maxDrawdown)) reasons.push("Candidate does not improve the active model"); const decision = reasons.length ? (reasons.includes("Candidate does not improve the active model") ? "KEEP_ACTIVE" : "REJECT_CANDIDATE") : "PROMOTE"; return { modelId, decision, candidate: report, active: active?.evaluation, eligible: decision === "PROMOTE", reasons }; }
  all(): readonly ModelRecord[] { return [...this.models.values()].map((model) => structuredClone(model)); }
}
