export type ResearchEventType = "MARKET_BAR_ACCEPTED" | "QUOTE_ACCEPTED" | "FEATURES_COMPUTED" | "MARKET_STRUCTURE_UPDATED" | "PATTERN_DETECTED" | "REGIME_UPDATED" | "SIGNAL_CREATED" | "DECISION_CREATED" | "RISK_APPROVED" | "RISK_REJECTED" | "ORDER_SUBMITTED" | "ORDER_PARTIAL_FILL" | "ORDER_FILLED" | "ORDER_REJECTED" | "POSITION_UPDATED" | "TRADE_CLOSED" | "PORTFOLIO_SNAPSHOT" | "PREDICTION_CREATED" | "PREDICTION_RESOLVED" | "MODEL_CREATED" | "MODEL_PROMOTED" | "MODEL_REJECTED";
export interface ResearchEvent { id: string; timestamp: number; eventType: ResearchEventType; symbol?: string; component: string; version: string; payload: Readonly<Record<string, unknown>>; }
export interface EventRepository { append(event: ResearchEvent): void; all(): readonly ResearchEvent[]; byType(type: ResearchEventType): readonly ResearchEvent[]; }
export class InMemoryEventRepository implements EventRepository { private readonly events: ResearchEvent[] = []; append(event: ResearchEvent) { if (this.events.some((existing) => existing.id === event.id)) throw new Error(`Duplicate event id: ${event.id}`); const last = this.events.at(-1); if (last && event.timestamp < last.timestamp) throw new Error("Event journal must be append-only and monotonic"); this.events.push(structuredClone(event)); } all() { return this.events.map((event) => structuredClone(event)); } byType(type: ResearchEventType) { return this.events.filter((event) => event.eventType === type).map((event) => structuredClone(event)); } }

export type HypothesisStatus = "IDEA" | "TESTING" | "REJECTED" | "SUPPORTED" | "VALIDATED";
export interface Hypothesis { id: string; status: HypothesisStatus; description: string; rationale: string; features: readonly string[]; patterns: readonly string[]; regimes: readonly string[]; target: string; testMethod: string; sampleSize?: number; results?: Readonly<Record<string, number>>; conclusion?: string; }
export interface Experiment { experimentId: string; datasetId: string; datasetVersion: string; symbols: readonly string[]; timeframe: string; featureVersions: readonly string[]; strategyVersion: string; modelVersion?: string; targetVersion?: string; parameters: Readonly<Record<string, string | number | boolean>>; costs: Readonly<{ feeBps: number; slippageBps: number; spreadBps?: number }>; seed?: number; trainRange?: readonly [number, number]; validationRange?: readonly [number, number]; testRange?: readonly [number, number]; metrics?: Readonly<Record<string, number>>; createdAt: number; codeVersion?: string; notes?: string; }
export interface ExperimentRepository { save(experiment: Experiment): void; get(id: string): Experiment | undefined; all(): readonly Experiment[]; }
export class InMemoryExperimentRepository implements ExperimentRepository { private readonly records = new Map<string, Experiment>(); save(experiment: Experiment) { if (this.records.has(experiment.experimentId)) throw new Error(`Experiment already exists: ${experiment.experimentId}`); this.records.set(experiment.experimentId, structuredClone(experiment)); } get(id: string) { const value = this.records.get(id); return value ? structuredClone(value) : undefined; } all() { return [...this.records.values()].map((value) => structuredClone(value)); } }

export interface TradeRepository<T = unknown> { append(trade: T): void; all(): readonly T[]; }
