export const mean = (values: readonly number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : Number.NaN;
export const variance = (values: readonly number[], sample = true) => { if (values.length < (sample ? 2 : 1)) return Number.NaN; const m = mean(values); return values.reduce((sum, value) => sum + (value - m) ** 2, 0) / (values.length - (sample ? 1 : 0)); };
export const standardDeviation = (values: readonly number[], sample = true) => Math.sqrt(variance(values, sample));
export const median = (values: readonly number[]) => quantile(values, 0.5);
export function quantile(values: readonly number[], q: number): number { if (!values.length || q < 0 || q > 1) return Number.NaN; const sorted = [...values].sort((a, b) => a - b); const index = (sorted.length - 1) * q; const lower = Math.floor(index); const upper = Math.ceil(index); return sorted[lower] + (sorted[upper] - sorted[lower]) * (index - lower); }
export function covariance(a: readonly number[], b: readonly number[]): number { if (a.length !== b.length || a.length < 2) return Number.NaN; const ma = mean(a); const mb = mean(b); return a.reduce((sum, value, i) => sum + (value - ma) * (b[i] - mb), 0) / (a.length - 1); }
export function correlation(a: readonly number[], b: readonly number[]): number { const denominator = standardDeviation(a) * standardDeviation(b); return denominator ? covariance(a, b) / denominator : Number.NaN; }
export function zScore(value: number, values: readonly number[]): number { const sd = standardDeviation(values); return sd ? (value - mean(values)) / sd : Number.NaN; }
export function meanConfidenceInterval(values: readonly number[], z = 1.96) { const sd = standardDeviation(values); const m = mean(values); const margin = z * sd / Math.sqrt(values.length); return { mean: m, lower: m - margin, upper: m + margin, confidence: 0.95 }; }
export function expectedValue(probabilityWin: number, averageWin: number, averageLoss: number, costs = 0): number { if (probabilityWin < 0 || probabilityWin > 1) throw new Error("Probability must be between 0 and 1"); return probabilityWin * averageWin - (1 - probabilityWin) * Math.abs(averageLoss) - costs; }
