import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import type { Bar } from "./domain";
import { canonicalDatasetHash, BAR_CANONICALIZATION_VERSION } from "./data";
import { loadBarsFile } from "./historical-data";
import { TradingCalendar, exchangeCalendarSpec } from "./calendar";
import { runHistoricalPreflight, type HistoricalPreflightResult } from "./historical-preflight";
import { buildFeatures, averageTrueRange } from "./features";
import { namedFeatures, OHLCV_FEATURE_IDS, type FeatureId } from "./feature-schema";
import { ExpectedBarClock } from "./bar-schedule";
import { type DatasetObservation, type DatasetRow, classificationMetrics, calibrationBins, expectedCalibrationError, TrustedPredictiveModelBundle, LogisticRegression, StandardScaler, trainingDataset, validateDatasetIntegrity, validateTrustedDatasetIntegrity } from "./ml";
import { TargetRegistry } from "./targets";
import { TripleBarrierResolver } from "./experience";
import { FIRST_LABEL_POLICY, FIRST_TARGET, ExperimentRunner, type DatasetManifest, type ExperimentConfig } from "./experiment";
import { TrustedAnalogueEngine, type TrustedAnalogueObservation } from "./analogues";
import { decomposeTripleBarrierProbabilities } from "./intelligence";
import { ExecutionCostModel } from "./costs";
import { sanitizeArtifact, canonicalJson, assertFiniteArtifact, verifyArtifactManifest } from "./serialization";

const args = process.argv.slice(2);
const flag = (name: string, fallback: string) => args.includes(name) ? args[args.indexOf(name) + 1] ?? fallback : fallback;
const dataPath = flag("--data", "./data/amzn-5m-20250701-20260630.csv");
const fullManifestPath = flag("--manifest", "./research/v2a-amzn-20250701-20260630/manifest.json");
const outputDir = flag("--output", "./research/v2a");
const fail = (message: string): never => { console.error(message); process.exit(1); };
const sha256Bytes = (value: Uint8Array) => createHash("sha256").update(value).digest("hex");
const finite = (value: number | undefined): number | null => value !== undefined && Number.isFinite(value) ? value : null;
const mean = (values: readonly number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : null;
const std = (values: readonly number[]) => { if (!values.length) return null; const m = mean(values)!; return Math.sqrt(values.reduce((a, b) => a + (b - m) ** 2, 0) / values.length); };
const quantile = (values: readonly number[], q: number) => { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b); const index = (sorted.length - 1) * q; const lo = Math.floor(index); const hi = Math.ceil(index); return sorted[lo]! + (sorted[hi]! - sorted[lo]!) * (index - lo); };
const date = (ms: number) => new Date(ms).toISOString().slice(0, 10);
const gitSha = (() => { try { return execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim(); } catch { return "unknown"; } })();

function writeJson(name: string, value: unknown): void {
  const safe = sanitizeArtifact(value);
  assertFiniteArtifact(safe, name);
  writeFileSync(`${outputDir}/${name}.json`, canonicalJson(safe));
}

function sessionBounds(calendar: TradingCalendar, day: string) { return calendar.sessionBounds(Date.parse(`${day}T12:00:00Z`)); }
function sessionKeys(bars: readonly Bar[], calendar: TradingCalendar): string[] { return [...new Set(bars.map((bar) => calendar.sessionKey(bar.startMs)))].sort(); }
function subset(bars: readonly Bar[], start: number, end: number): Bar[] { return bars.filter((bar) => bar.startMs >= start && bar.startMs + bar.intervalMs <= end).sort((a, b) => a.startMs - b.startMs); }
function manifestFor(base: DatasetManifest, id: string, version: string, start: number, end: number, bars: readonly Bar[], preflight: HistoricalPreflightResult): DatasetManifest {
  return { ...base, datasetId: id, datasetVersion: version, startTimestamp: start, endTimestamp: end, contentHash: preflight.canonicalDatasetHash, dataQualitySummary: preflight.dataQuality };
}
function knownQuarantineIssues(issues: readonly string[]): boolean { return issues.every((issue) => issue === "GAP:AMZN:1776279900000" || issue === "MISSING_SESSION_BARS:AMZN:2026-04-15:1"); }

function splitFor(ts: number, config: ExperimentConfig): DatasetObservation["split"] | undefined {
  const validationStart = config.validationStart ?? config.trainEnd; const calibrationStart = config.calibrationStart ?? config.validationEnd; const testStart = config.testDecisionStart ?? config.testStart ?? config.calibrationEnd; const testEnd = config.testDecisionEnd ?? config.testEnd;
  if (ts >= (config.trainStart ?? 0) && ts < validationStart) return "TRAIN";
  if (ts >= validationStart && ts < calibrationStart) return "VALIDATION";
  if (ts >= calibrationStart && ts < testStart) return "CALIBRATION";
  if (ts >= testStart && ts <= testEnd) return "TEST";
  return undefined;
}

function buildObservations(bars: readonly Bar[], manifest: DatasetManifest, config: ExperimentConfig, calendar: TradingCalendar): DatasetObservation[] {
  const registry = new TargetRegistry(); registry.register(FIRST_TARGET); registry.registerResolver(new TripleBarrierResolver()); const resolver = registry.resolver("TRIPLE_BARRIER")!; const observations: DatasetObservation[] = [];
  for (const symbol of manifest.symbols) {
    const history = bars.filter((bar) => bar.symbol === symbol).sort((a, b) => a.startMs - b.startMs); const schedule = new ExpectedBarClock(calendar, manifest.barIntervalMs);
    for (let index = 21; index < history.length - FIRST_TARGET.horizonBars; index++) {
      const completed = history.slice(0, index + 1); const decisionTimestamp = completed.at(-1)!.startMs + completed.at(-1)!.intervalMs; const features = buildFeatures(completed, undefined, { decisionTimestamp }); const atr = averageTrueRange(completed, 14); const split = splitFor(decisionTimestamp, config); if (!features || !Number.isFinite(atr) || !split) continue;
      const resolution = resolver.resolve(FIRST_TARGET, history, index + 1, atr, schedule); if (!resolution) continue; const modelLabel = resolution.label === "UP" ? 1 : resolution.label === "DOWN" ? 0 : undefined;
      observations.push({ observationId: `${symbol}-${decisionTimestamp}`, symbol, featureTimestamp: features.ts, decisionTimestamp, targetStartTimestamp: resolution.targetStartTimestamp, targetEndTimestamp: resolution.plannedTargetEndTimestamp, plannedTargetEndTimestamp: resolution.plannedTargetEndTimestamp, outcomeAvailableTimestamp: resolution.outcomeAvailableTimestamp, featureSetVersion: manifest.featureSetVersion, featureIds: OHLCV_FEATURE_IDS, targetVersion: FIRST_TARGET.targetVersion, targetKind: "TRIPLE_BARRIER", namedFeatures: namedFeatures(features), rawTargetLabel: resolution.label, modelLabel, labelPolicy: FIRST_LABEL_POLICY, split, targetScheduleVersion: `eligible-bars-v1:${manifest.barIntervalMs}`, targetCalendarSpecHash: manifest.calendarSpecHash });
    }
  }
  return observations;
}

function metrics(labels: readonly (0 | 1)[], probabilities: readonly number[], threshold = 0.5) {
  if (!labels.length) return null;
  const base = classificationMetrics(labels, probabilities, threshold); const predicted = probabilities.map((p) => p >= threshold ? 1 : 0); const tp = base.confusion.truePositive; const tn = base.confusion.trueNegative; const fp = base.confusion.falsePositive; const fn = base.confusion.falseNegative; const tpr = tp + fn ? tp / (tp + fn) : null; const tnr = tn + fp ? tn / (tn + fp) : null; const denominator = Math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)); const mcc = denominator ? (tp * tn - fp * fn) / denominator : null;
  const pairs = probabilities.map((p, i) => ({ p, label: labels[i]! })).sort((a, b) => b.p - a.p); const positives = labels.filter((label) => label === 1).length; const negatives = labels.length - positives; let concordant = 0; let ties = 0; for (const positive of pairs.filter((x) => x.label === 1)) for (const negative of pairs.filter((x) => x.label === 0)) positive.p > negative.p ? concordant++ : positive.p === negative.p ? ties++ : 0; const rocAuc = positives && negatives ? (concordant + ties / 2) / (positives * negatives) : null; let seen = 0; let sumPrecision = 0; pairs.forEach((row) => { if (row.label === 1) { seen++; sumPrecision += seen / (pairs.indexOf(row) + 1); } }); const prAuc = positives ? sumPrecision / positives : null;
  return { accuracy: base.accuracy, balancedAccuracy: tpr !== null && tnr !== null ? (tpr + tnr) / 2 : null, upPrecision: base.precision, upRecall: base.recall, upF1: base.f1, rocAuc, prAucAveragePrecision: prAuc, matthewsCorrelationCoefficient: mcc, brier: base.brier, logLoss: base.logLoss, ece: expectedCalibrationError(labels, probabilities), confusion: { TP: tp, FP: fp, TN: tn, FN: fn }, predictedPositiveCount: predicted.filter(Boolean).length };
}

function probabilityDistribution(values: readonly number[]) { return { minimum: finite(Math.min(...values)), p05: quantile(values, .05), p25: quantile(values, .25), median: quantile(values, .5), p75: quantile(values, .75), p95: quantile(values, .95), maximum: finite(Math.max(...values)), mean: mean(values) }; }
function counts(rows: readonly DatasetObservation[]) { return Object.fromEntries(["UP", "DOWN", "TIMEOUT", "AMBIGUOUS"].map((label) => [label, rows.filter((row) => row.rawTargetLabel === label).length])); }
function monthKey(ts: number, calendar: TradingCalendar) { return calendar.sessionKey(ts).slice(0, 7); }
function temporalFolds(rows: readonly DatasetObservation[], selectedL2: number) {
  const binary = rows.filter((row) => row.modelLabel !== undefined).sort((a, b) => a.decisionTimestamp - b.decisionTimestamp); const folds: Array<Record<string, unknown>> = []; const foldCoefficients: number[][] = [];
  for (let fold = 0; fold < 4; fold++) { const trainEnd = Math.max(2, Math.floor(binary.length * (.4 + fold * .15))); const evalEnd = Math.min(binary.length, Math.max(trainEnd + 1, Math.floor(binary.length * (.55 + fold * .15)))); const trainRows = binary.slice(0, trainEnd); const evalRows = binary.slice(trainEnd, evalEnd); const trainData: DatasetRow[] = trainRows.map((row) => ({ symbol: row.symbol, decisionTimestamp: row.decisionTimestamp, targetStartTimestamp: row.targetStartTimestamp, targetEndTimestamp: row.targetEndTimestamp, features: row.featureIds.map((id) => row.namedFeatures[id]), label: row.modelLabel!, split: "TRAIN" })); const evalData: DatasetRow[] = evalRows.map((row) => ({ ...trainData[0]!, symbol: row.symbol, decisionTimestamp: row.decisionTimestamp, targetStartTimestamp: row.targetStartTimestamp, targetEndTimestamp: row.targetEndTimestamp, features: row.featureIds.map((id) => row.namedFeatures[id]), label: row.modelLabel!, split: "VALIDATION" })); if (new Set(trainData.map((row) => row.label)).size < 2 || !evalData.length) continue; const scaler = new StandardScaler().fitTraining(trainingDataset(trainData)); const scaledTrain = trainData.map((row) => ({ ...row, features: scaler.transform(row.features) })); const scaledEval = evalData.map((row) => ({ ...row, features: scaler.transform(row.features) })); const model = new LogisticRegression().fit(trainingDataset(scaledTrain), { l2: selectedL2, epochs: 150 }); const probabilities = scaledEval.map((row) => model.predictProbability(row.features)); const foldMetric = metrics(scaledEval.map((row) => row.label), probabilities); foldCoefficients.push(model.metadata().weights as number[]); folds.push({ fold: fold + 1, trainingRange: [trainRows[0]!.decisionTimestamp, trainRows.at(-1)!.decisionTimestamp], evaluationRange: [evalRows[0]!.decisionTimestamp, evalRows.at(-1)!.decisionTimestamp], count: evalRows.length, binaryPrevalence: mean(evalRows.map((row) => row.modelLabel!)), selectedL2, ...foldMetric }); }
  const stability = Object.fromEntries(OHLCV_FEATURE_IDS.map((feature, index) => { const values = foldCoefficients.map((row) => row[index]!); const positive = values.filter((value) => value > 0).length; const negative = values.filter((value) => value < 0).length; return [feature, { positiveCoefficientCount: positive, negativeCoefficientCount: negative, zeroCount: values.filter((value) => value === 0).length, meanCoefficient: mean(values), stdCoefficient: std(values), signFlag: positive > 0 && negative > 0 ? "SIGN_UNSTABLE" : "STABLE_OR_ZERO" }]; })); return { folds, aggregate: Object.fromEntries(["brier", "logLoss", "balancedAccuracy", "rocAuc"].map((field) => { const values = folds.map((fold) => fold[field]).filter((value): value is number => typeof value === "number"); return [field, { mean: mean(values), std: std(values), min: values.length ? Math.min(...values) : null, max: values.length ? Math.max(...values) : null }]; })), coefficientStability: stability }; }

function main(): void {
  mkdirSync(outputDir, { recursive: true }); const base = JSON.parse(readFileSync(fullManifestPath, "utf8")) as DatasetManifest; const bars = loadBarsFile(dataPath, { intervalMs: base.barIntervalMs, symbols: base.symbols }); const calendar = new TradingCalendar({ timeZone: base.timezone, holidays: base.calendarHolidays, earlyCloses: base.calendarEarlyCloses }); const fullPreflight = runHistoricalPreflight(base, bars); writeJson("amzn-full-preflight", { ...fullPreflight, calendarSpec: undefined });
  if (!knownQuarantineIssues(fullPreflight.dataQuality.issues) || fullPreflight.blockingReasons.some((code) => !["NO_UNEXPECTED_GAPS", "SESSION_COVERAGE_VALID", "NO_MISSING_REQUIRED_SESSIONS", "DATA_QUALITY_ALL_CLEAR"].includes(code))) fail("UNEXPECTED_DATA_QUALITY_FAILURE_OUTSIDE_QUARANTINE");
  const amendment = { protocolId: "v2a-amzn-5m", amendmentVersion: 1, amendmentStage: "PRE_MODEL_DATA_QUALITY", reasonCode: "PROVIDER_INCOMPLETE_SESSION", affectedTimestampUtc: "2026-04-15T19:00:00Z", affectedSession: "2026-04-15", expectedBars: 78, observedBars: 77, targetedProviderRecheck: "SAME_GAP_CONFIRMED", originalDevelopmentStart: "2025-07-01", originalDevelopmentEnd: "2026-03-31", originalFinalHoldoutStart: "2026-04-01", originalFinalHoldoutEnd: "2026-06-30", quarantineStart: "2026-04-01", quarantineEnd: "2026-04-15", amendedDevelopmentStart: "2025-07-01", amendedDevelopmentEnd: "2026-03-31", amendedFinalHoldoutStart: "2026-04-16", amendedFinalHoldoutEnd: "2026-06-30", predictiveAnalysisOccurredBeforeAmendment: false, holdoutOutcomesInspectedBeforeAmendment: false, modelChangedBecauseOfAmendment: false, barFabricated: false, sourceCommit: gitSha };
  writeJson("protocol-amendment-pre-model", amendment);
  const developmentStart = base.startTimestamp; const developmentEnd = sessionBounds(calendar, "2026-03-31").closeMs; const holdoutStart = sessionBounds(calendar, "2026-04-16").openMs; const holdoutEnd = sessionBounds(calendar, "2026-06-30").closeMs; const devBars = subset(bars, developmentStart, developmentEnd); const holdoutBars = subset(bars, holdoutStart, holdoutEnd);
  const devBase = { ...base, datasetId: "v2a-amzn-development-20250701-20260331", startTimestamp: developmentStart, endTimestamp: developmentEnd }; const holdoutBase = { ...base, datasetId: "v2a-amzn-final-holdout-20260416-20260630", startTimestamp: holdoutStart, endTimestamp: holdoutEnd }; const devPreflight = runHistoricalPreflight({ ...devBase, contentHash: canonicalDatasetHash(devBars) }, devBars); const holdoutPreflight = runHistoricalPreflight({ ...holdoutBase, contentHash: canonicalDatasetHash(holdoutBars) }, holdoutBars); const devManifest = manifestFor(base, devBase.datasetId, "1-amended-pre-model", developmentStart, developmentEnd, devBars, devPreflight); const holdoutManifest = manifestFor(base, holdoutBase.datasetId, "1-amended-pre-model", holdoutStart, holdoutEnd, holdoutBars, holdoutPreflight);
  writeJson("development-manifest", devManifest); writeJson("final-holdout-manifest", holdoutManifest); writeJson("development-preflight", devPreflight); writeJson("final-holdout-structural-preflight", holdoutPreflight);
  if (!devPreflight.passed) fail(`DEVELOPMENT_PREFLIGHT_FAILED:${devPreflight.blockingReasons.join(",")}`); if (!holdoutPreflight.passed) fail("FINAL_HOLDOUT_DATA_QUALITY_FAILED");
  const devSessions = sessionKeys(devBars, calendar); const endOfSession = (key: string) => sessionBounds(calendar, key).closeMs; const boundaryIndex = (fraction: number) => Math.min(devSessions.length - 1, Math.max(0, Math.floor(devSessions.length * fraction) - 1)); const trainEnd = endOfSession(devSessions[boundaryIndex(.55)]!); const validationEnd = endOfSession(devSessions[boundaryIndex(.70)]!); const calibrationEnd = endOfSession(devSessions[boundaryIndex(.85)]!); const safeDecisionBar = devBars.filter((bar) => bar.symbol === base.symbols[0]).at(-FIRST_TARGET.horizonBars - 1); if (!safeDecisionBar) fail("DEVELOPMENT_TARGET_TAIL_UNAVAILABLE"); const safeBar = safeDecisionBar!; const testDecisionEnd = safeBar.startMs + safeBar.intervalMs;
  const config: ExperimentConfig = { experimentId: "v2a-amzn-5m-development", datasetId: devManifest.datasetId, modelId: "v2a-logistic-regression", modelVersion: "1", seed: 7, trainStart: developmentStart, trainEnd, validationStart: trainEnd, validationEnd, calibrationStart: validationEnd, calibrationEnd, testStart: calibrationEnd, testDecisionStart: calibrationEnd, testEnd: developmentEnd, testDecisionEnd, outcomeDataEnd: developmentEnd, targetVersion: FIRST_TARGET.targetVersion, labelPolicyVersion: FIRST_LABEL_POLICY.version, featureSetVersion: devManifest.featureSetVersion, costModel: { spreadBps: 1, entrySlippageBps: .5, exitSlippageBps: .5, entryFeeBps: .5, exitFeeBps: .5 }, initialCash: 100_000, metricFrequency: "5m", gapPolicy: "REJECT_UNEXPECTED_GAP", decisionPolicy: { minimumEvidence: "MODERATE", entryProbability: .6 }, runtimeMode: "RESEARCH_EVALUATION", executionPolicy: { version: "next-open-entry-next-open-exit-v1", entryMethod: "NEXT_BAR_OPEN", exitMethod: "NEXT_BAR_OPEN" }, exitPolicy: { version: "baseline-exit-v1", maxHoldMs: 30 * 60_000 }, paperOnly: true };
  const report = new ExperimentRunner().run({ manifest: devManifest, config, bars: devBars }); if (report.status !== "COMPLETED" || !report.persistedArtifacts?.modelArtifact || !report.test || !report.integratedReplay) fail(`V2A_DEVELOPMENT_EXPERIMENT_FAILED:${report.message}`); const persisted = report.persistedArtifacts!; const replay = report.integratedReplay!;
  const amendmentReference = "protocol-amendment-pre-model.json"; const protocol = { protocolId: "v2a-amzn-5m", protocolVersion: "2A", symbol: "AMZN", interval: "5m", developmentStart: "2025-07-01", developmentEnd: "2026-03-31", quarantineStart: "2026-04-01", quarantineEnd: "2026-04-15", finalHoldoutStart: "2026-04-16", finalHoldoutEnd: "2026-06-30", finalHoldoutStatus: "LOCKED", developmentDatasetHash: devManifest.contentHash, finalHoldoutDatasetHash: holdoutManifest.contentHash, calendarHash: base.calendarSpecHash, featureSetVersion: FIRST_LABEL_POLICY.targetVersion ? devManifest.featureSetVersion : devManifest.featureSetVersion, targetVersion: FIRST_TARGET.targetVersion, labelPolicyVersion: FIRST_LABEL_POLICY.version, modelFamily: "LOGISTIC_REGRESSION", createdGitSha: gitSha, amendmentReference, amendmentOccurredBeforePredictiveAnalysis: true, modelChangedBecauseOfAmendment: false };
  writeJson("protocol-v2a", protocol);
  const observations = validateTrustedDatasetIntegrity(validateDatasetIntegrity(buildObservations(devBars, devManifest, config, calendar), "PURGE_OVERLAP"), "PURGE_OVERLAP"); const testAll = observations.filter((row) => row.split === "TEST"); const testBinary = testAll.filter((row) => row.modelLabel !== undefined); const artifact = persisted.modelArtifact; const bundle = new TrustedPredictiveModelBundle(artifact); const predictions = testBinary.map((row) => bundle.predict(row.namedFeatures)); const labels = testBinary.map((row) => row.modelLabel!) as (0 | 1)[]; const calibrated = predictions.map((p) => p.calibratedProbability); const raw = predictions.map((p) => p.rawProbability); const trainBinary = observations.filter((row) => row.split === "TRAIN" && row.modelLabel !== undefined); const trainLabels = trainBinary.map((row) => row.modelLabel!) as (0 | 1)[]; const trainPrevalence = mean(trainLabels) ?? 0; const majority = trainPrevalence >= .5 ? 1 : 0;
  const m = { testCount: labels.length, binaryPositivePrevalence: mean(labels) ?? 0, logistic: metrics(labels, calibrated), majorityClassifier: metrics(labels, labels.map(() => majority)), constantProbabilityClassifier: metrics(labels, labels.map(() => trainPrevalence)), logisticBeatsMajorityAccuracy: (metrics(labels, calibrated)?.accuracy ?? -Infinity) > (metrics(labels, labels.map(() => majority))?.accuracy ?? Infinity), logisticBeatsTrainPrevalenceBrier: (metrics(labels, calibrated)?.brier ?? Infinity) < (metrics(labels, labels.map(() => trainPrevalence))?.brier ?? -Infinity), logisticBeatsTrainPrevalenceLogLoss: (metrics(labels, calibrated)?.logLoss ?? Infinity) < (metrics(labels, labels.map(() => trainPrevalence))?.logLoss ?? -Infinity) };
  writeJson("development-diagnostics", { protocolId: "v2a-amzn-5m", developmentOnly: true, train: { count: trainBinary.length, range: [config.trainStart, config.trainEnd], binaryCounts: { UP: trainLabels.filter((x) => x === 1).length, DOWN: trainLabels.filter((x) => x === 0).length } }, validation: { count: observations.filter((row) => row.split === "VALIDATION").length, range: [config.validationStart, config.validationEnd] }, calibration: { count: observations.filter((row) => row.split === "CALIBRATION").length, range: [config.calibrationStart, config.calibrationEnd] }, developmentTest: { allCount: testAll.length, binaryCount: testBinary.length, range: [config.testStart, config.testDecisionEnd], rawTargetCounts: counts(testAll), metrics: m, probabilityDistribution: probabilityDistribution(calibrated), rawProbabilityDistribution: probabilityDistribution(raw), calibration: { uncalibrated: metrics(labels, raw), calibrated: metrics(labels, calibrated), bins: calibrationBins(labels, calibrated).map((bin) => ({ lower: bin.lower, upper: bin.upper, count: bin.count, meanPredicted: finite(bin.meanPredicted), observedPositiveFrequency: finite(bin.eventRate) })) }, ood: Object.fromEntries(["IN_DISTRIBUTION", "WARNING", "OUT_OF_DISTRIBUTION"].map((s) => [s, predictions.filter((p) => p.ood.status === s).length])) }, selectedL2: report.validation.selectedL2 ?? null, featureParity: { expectedComparableCount: testBinary.length, checkedCount: report.featureParity?.checkedCount ?? 0, missingRuntimeFeatureCount: report.featureParity?.missingRuntimeFeatureCount ?? 0, mismatchCount: report.featureParity?.mismatchCount ?? 0, maximumAbsoluteDifference: report.featureParity?.maximumAbsoluteDifference ?? null }, historicalReadiness: report.historicalReadiness });
  const drift = Object.fromEntries(OHLCV_FEATURE_IDS.map((feature) => { const values = (split: string) => observations.filter((row) => row.split === split).map((row) => row.namedFeatures[feature]); const train = values("TRAIN"); return [feature, { trainMean: mean(train), trainStd: std(train), validationMean: mean(values("VALIDATION")), validationStd: std(values("VALIDATION")), calibrationMean: mean(values("CALIBRATION")), calibrationStd: std(values("CALIBRATION")), developmentTestMean: mean(values("TEST")), developmentTestStd: std(values("TEST")), standardizedMeanDifference: Object.fromEntries(["VALIDATION", "CALIBRATION", "TEST"].map((split) => [split, train.length && std(train) ? (mean(values(split))! - mean(train)!) / std(train)! : null])), nonfiniteCount: 0 }]; }));
  const coefficients = artifact.model.weights.map((coefficient, index) => ({ feature: artifact.featureIds[index], coefficient, sign: coefficient > 0 ? "POSITIVE" : coefficient < 0 ? "NEGATIVE" : "ZERO" })).sort((a, b) => Math.abs(b.coefficient) - Math.abs(a.coefficient)).map((row, index) => ({ ...row, absoluteMagnitudeRank: index + 1 }));
  const analoguePool = (persisted.analogueDatabase ?? []).filter((row) => trainBinary.some((candidate) => candidate.observationId === row.sourceObservationId || candidate.observationId === row.observationId)).map((row) => ({ ...row, sourceKind: "TRAIN_DATASET" as const })) as TrustedAnalogueObservation[]; const analogueScaler = persisted.analogueScaler; const analogueEngine = new TrustedAnalogueEngine(); const analogueSamples = testBinary.map((row) => analogueEngine.query(analoguePool, { currentFeatures: row.namedFeatures, decisionTimestamp: row.decisionTimestamp, featureSetVersion: row.featureSetVersion, featureIds: row.featureIds as FeatureId[], targetVersion: row.targetVersion, targetKind: row.targetKind, scalerProfile: analogueScaler, minimumSample: 20 }).sampleSize); const testHistory = devBars.filter((bar) => bar.symbol === base.symbols[0]).sort((a, b) => a.startMs - b.startMs); const costModel = new ExecutionCostModel(config.costModel!); const evByObservation = new Map<string, number>(); for (const row of testAll) { const index = testHistory.findIndex((bar) => bar.startMs + bar.intervalMs === row.decisionTimestamp); if (index < 0) continue; const atr = averageTrueRange(testHistory.slice(0, index + 1), 14); const analogue = analogueEngine.query(analoguePool, { currentFeatures: row.namedFeatures, decisionTimestamp: row.decisionTimestamp, featureSetVersion: row.featureSetVersion, featureIds: row.featureIds as FeatureId[], targetVersion: row.targetVersion, targetKind: row.targetKind, scalerProfile: analogueScaler, minimumSample: 20 }); if (!analogue.barrier || !Number.isFinite(atr)) continue; const probability = bundle.predict(row.namedFeatures).probability; const outcome = decomposeTripleBarrierProbabilities(probability, analogue.barrier, "P_UP_GIVEN_UP_OR_DOWN"); const reference = row.namedFeatures["close"] ?? testHistory[index]!.close; const upper = FIRST_TARGET.upperBarrierMultiple! * atr / reference; const lower = FIRST_TARGET.lowerBarrierMultiple! * atr / reference; const cost = costModel.estimateRoundTrip(reference, reference, "BUY").returnUnits; evByObservation.set(row.observationId, outcome.up * upper + outcome.down * -lower - cost); } const evValues = [...evByObservation.values()]; const evAudit = replay.actualExpectedValueAudit ?? { count: 0, meanGrossExpectedValue: 0, meanExecutionCost: 0, meanNetExpectedValue: 0, methodVersions: [] }; const funnel = replay.decisionFunnel ?? { allTestDecisionCount: 0, featureAvailableCount: 0, predictionAvailableCount: 0, analogueQueriedCount: 0, analogueSufficientCount: 0, evEvaluatedCount: 0, positiveEvCount: 0, thresholdPassedCount: 0, buyDecisionCount: 0, reasonCodeCounts: {} };
  const monthly = Object.fromEntries([...new Set(testAll.map((row) => monthKey(row.decisionTimestamp, calendar)))].sort().map((month) => { const rows = testBinary.filter((row) => monthKey(row.decisionTimestamp, calendar) === month); const ps = rows.map((row) => bundle.predict(row.namedFeatures)); const ys = rows.map((row) => row.modelLabel!) as (0 | 1)[]; const monthAll = testAll.filter((row) => monthKey(row.decisionTimestamp, calendar) === month); const monthEv = monthAll.map((row) => evByObservation.get(row.observationId)).filter((value): value is number => value !== undefined); return [month, { sampleSize: rows.length, binaryPrevalence: mean(ys) ?? 0, metrics: metrics(ys, ps.map((p) => p.calibratedProbability)), oodRate: rows.length ? ps.filter((p) => p.ood.status === "OUT_OF_DISTRIBUTION").length / rows.length : 0, analogueSufficientRate: rows.length ? rows.filter((row) => analogueEngine.query(analoguePool, { currentFeatures: row.namedFeatures, decisionTimestamp: row.decisionTimestamp, featureSetVersion: row.featureSetVersion, featureIds: row.featureIds as FeatureId[], targetVersion: row.targetVersion, targetKind: row.targetKind, scalerProfile: analogueScaler, minimumSample: 20 }).evidence === "SUFFICIENT").length / rows.length : 0, positiveEvRate: monthEv.length ? monthEv.filter((value) => value > 0).length / monthEv.length : 0, buyDecisionRate: funnel.buyDecisionCount === 0 ? 0 : null }]; }));
  const foldDiagnostics = temporalFolds(observations, report.validation.selectedL2 ?? .01); writeJson("development-diagnostics-extended", { monthly, featureDrift: drift, coefficients, temporalFolds: foldDiagnostics.folds, temporalFoldAggregate: foldDiagnostics.aggregate, coefficientStability: foldDiagnostics.coefficientStability, analogues: { queries: analogueSamples.length, sufficientQueries: analogueSamples.filter((n) => n >= 20).length, coverage: analogueSamples.length ? analogueSamples.filter((n) => n > 0).length / analogueSamples.length : 0, meanSampleCount: mean(analogueSamples) ?? 0, medianSampleCount: quantile(analogueSamples, .5) ?? 0, minimumSampleCount: analogueSamples.length ? Math.min(...analogueSamples) : 0, maximumSampleCount: analogueSamples.length ? Math.max(...analogueSamples) : 0 }, expectedValue: { available: evValues.length > 0, count: evValues.length, minimum: quantile(evValues, 0), p05: quantile(evValues, .05), p25: quantile(evValues, .25), median: quantile(evValues, .5), p75: quantile(evValues, .75), p95: quantile(evValues, .95), maximum: quantile(evValues, 1), mean: mean(evValues), negativeCount: evValues.filter((value) => value < 0).length, zeroCount: evValues.filter((value) => value === 0).length, positiveCount: evValues.filter((value) => value > 0).length, runtimeAggregate: evAudit }, decisionFunnel: funnel, paperReplay: { intentsCreated: replay.intentCreatedCount ?? 0, executed: replay.intentExecutedCount ?? 0, riskRejected: replay.intentRiskRejectedCount ?? 0, expired: replay.intentExpiredCount ?? 0, cancelled: replay.intentCancelledCount ?? 0, orders: replay.orderCount ?? 0, fills: replay.fills?.length ?? 0, closedTrades: replay.tradeCount, fees: replay.decisionWindowFees ?? 0, slippage: replay.decisionWindowSlippage ?? 0, decisionWindowReturn: replay.decisionWindowResult?.totalReturn ?? 0, settledReturn: replay.totalReturn ?? 0, maxDrawdown: replay.metrics?.maxDrawdown ?? null, sharpe: replay.metrics?.sharpe ?? null, reasonCodeCounts: replay.reasonCodeCounts ?? {} }, benchmarks: report.benchmarks, developmentHistoricalReadiness: report.historicalReadiness, scientificInterpretation: { usefulUpDiscrimination: (m.logistic?.rocAuc ?? 0) > .5, temporalStability: "See monthly and fold diagnostics", coefficientSignsStable: "See coefficient stability artifact", oodSubstantial: (replay.decisionFunnel?.allTestDecisionCount ?? 0) > 0 && (replay.reasonCodeCounts?.MODEL_OUT_OF_DISTRIBUTION ?? 0) / Math.max(1, replay.decisionFunnel?.allTestDecisionCount ?? 1) > .1, analogueSamplesAdequate: analogueSamples.filter((n) => n >= 20).length === analogueSamples.length, positiveEvCause: "Existing analogue-conditioned triple-barrier EV minus configured spread, slippage, and fees", tradeCause: "Existing probability, evidence, OOD, EV, and risk gates; zero trades remains valid" } });
  writeJson("holdout-lock-audit", { finalHoldoutStatus: "LOCKED", finalHoldoutFeatures: 0, finalHoldoutLabels: 0, finalHoldoutTargets: 0, finalHoldoutPredictions: 0, finalHoldoutOODReports: 0, finalHoldoutAnalogueReports: 0, finalHoldoutEVReports: 0, finalHoldoutDecisions: 0, finalHoldoutOrders: 0, finalHoldoutTrades: 0, finalHoldoutBenchmarkReports: 0, verification: "PASS" });
  const files = ["protocol-amendment-pre-model", "development-manifest", "final-holdout-manifest", "development-preflight", "final-holdout-structural-preflight", "protocol-v2a", "development-diagnostics", "development-diagnostics-extended", "holdout-lock-audit"]; const artifacts = files.map((name) => { const bytes = readFileSync(`${outputDir}/${name}.json`); return { relativePath: `${name}.json`, sizeBytes: bytes.byteLength, sha256: sha256Bytes(bytes) }; }); const artifactManifest = { protocolId: "v2a-amzn-5m", artifacts }; writeJson("artifact-manifest", artifactManifest); const verification = verifyArtifactManifest(outputDir, artifactManifest); if (!verification.valid) fail(`ARTIFACT_VERIFICATION_FAILED:${verification.failures.join(",")}`); console.log(JSON.stringify({ protocol: protocol.protocolId, developmentBars: devBars.length, developmentSessions: devSessions.length, holdoutBars: holdoutBars.length, holdoutSessions: sessionKeys(holdoutBars, calendar).length, developmentHash: devManifest.contentHash, finalHoldoutHash: holdoutManifest.contentHash, calendarHash: base.calendarSpecHash, selectedL2: report.validation.selectedL2, testBinary: labels.length, trades: replay.tradeCount, artifactVerification: "PASS" }, null, 2));
}

try { main(); } catch (error) { fail(error instanceof Error ? error.message : String(error)); }
