import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import type { Bar, PaperOrder } from "./domain";
import { canonicalDatasetHash } from "./data";
import { loadBarsFile } from "./historical-data";
import { TradingCalendar } from "./calendar";
import { averageTrueRange, buildFeatures } from "./features";
import { namedFeatures, OHLCV_FEATURE_IDS, type NamedFeatureVector } from "./feature-schema";
import { type DatasetObservation, type DatasetRow, classificationMetrics, calibrationBins, expectedCalibrationError, fitOodProfile, assessOod, LogisticRegression, PlattCalibrator, StandardScaler, trainingDataset, calibrationDataset } from "./ml";
import { FIRST_LABEL_POLICY, FIRST_TARGET, type DatasetManifest } from "./experiment";
import { ExpectedBarClock } from "./bar-schedule";
import { TargetRegistry } from "./targets";
import { TripleBarrierResolver } from "./experience";
import { summarizeTrustedAnalogues, fitTrustedAnalogueScaler, type TrustedAnalogueObservation, type TrustedAnalogueScalerProfile } from "./analogues";
import { decomposeTripleBarrierProbabilities } from "./intelligence";
import { ExecutionCostModel } from "./costs";
import { PaperBroker } from "./broker";
import { sanitizeArtifact, canonicalJson, assertFiniteArtifact, verifyArtifactManifest } from "./serialization";
import { buildCandidateFeatures, buildCandidateFeaturesAt, CANDIDATE_FEATURE_SET_VERSION, CANDIDATE_OHLCV_FEATURE_IDS } from "./candidate-features";
import { HistogramGradientBoostingClassifier, type HistogramGradientBoostingConfig } from "./hgb";

const args = process.argv.slice(2);
const flag = (name: string, fallback: string) => args.includes(name) ? args[args.indexOf(name) + 1] ?? fallback : fallback;
const dataPath = flag("--data", "./data/amzn-5m-20250701-20260331.csv");
const manifestPath = flag("--manifest", "./research/v2a-amzn-20250701-20260630/manifest.json");
const outputDir = flag("--output", "./research/v2c");
const fail = (message: string): never => { console.error(message); process.exit(1); };
const creationGitSha = (() => { try { return execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim(); } catch { return "unknown"; } })();
const sha256 = (value: Uint8Array) => createHash("sha256").update(value).digest("hex");
const finite = (value: number | undefined): number | null => value !== undefined && Number.isFinite(value) ? value : null;
const mean = (values: readonly number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
const std = (values: readonly number[]) => { if (!values.length) return null; const m = mean(values)!; return Math.sqrt(values.reduce((sum, value) => sum + (value - m) ** 2, 0) / values.length); };
const quantile = (values: readonly number[], q: number) => { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b); const p = (sorted.length - 1) * q; const lo = Math.floor(p); const hi = Math.ceil(p); return sorted[lo]! + (sorted[hi]! - sorted[lo]!) * (p - lo); };
const distribution = (values: readonly number[]) => ({ minimum: finite(Math.min(...values)), p05: quantile(values, .05), p25: quantile(values, .25), median: quantile(values, .5), p75: quantile(values, .75), p95: quantile(values, .95), maximum: finite(Math.max(...values)), mean: mean(values), std: std(values) });
const sessionOf = (calendar: TradingCalendar, timestamp: number) => calendar.sessionKey(timestamp);
const subset = (bars: readonly Bar[], start: number, end: number) => bars.filter((bar) => bar.startMs >= start && bar.startMs + bar.intervalMs <= end).sort((a, b) => a.startMs - b.startMs);
function writeJson(name: string, value: unknown): void { const safe = sanitizeArtifact(value); assertFiniteArtifact(safe, name); writeFileSync(`${outputDir}/${name}.json`, canonicalJson(safe)); }

interface ResearchObservation extends DatasetObservation { readonly featureValues: NamedFeatureVector; readonly atr: number; readonly barIndex: number; }
interface FoldSpec { fold: number; trainingSessions: readonly string[]; evaluationSessions: readonly string[]; trainingHistoryRange: readonly [number, number]; evaluationRange: readonly [number, number]; internalRoles: { train: readonly [number, number]; validation: readonly [number, number]; calibration: readonly [number, number] }; }
interface ProbabilityModel { predictProbability(features: readonly number[]): number; metadata(): { algorithm: string; fittedObservationIds?: readonly string[]; weights?: readonly number[]; bias?: number; config?: HistogramGradientBoostingConfig; initialLogit?: number; iterations?: number }; }
interface Fit { featureSetVersion: string; featureIds: readonly string[]; trainRows: readonly ResearchObservation[]; validationRows: readonly ResearchObservation[]; calibrationRows: readonly ResearchObservation[]; modelKind: "LOGISTIC_REGRESSION" | "HISTOGRAM_GRADIENT_BOOSTING"; selectedL2?: number; selectedConfig?: HistogramGradientBoostingConfig; scaler: StandardScaler; model: ProbabilityModel; calibrator?: PlattCalibrator; ood: ReturnType<typeof fitOodProfile>; analoguePool: readonly TrustedAnalogueObservation[]; analogueScaler: TrustedAnalogueScalerProfile; analogueScaled: readonly { observation: TrustedAnalogueObservation; values: readonly number[] }[]; }
interface Prediction { rawProbability: number; calibratedProbability: number; ood: ReturnType<typeof assessOod>; analogue: ReturnType<typeof summarizeTrustedAnalogues> & { distances: readonly number[]; evidence: "INSUFFICIENT" | "SUFFICIENT" }; ev?: EvDiagnostic; }
interface ScoredRow { row: ResearchObservation; prediction: Prediction; buy: boolean; reasonCode: string; }
interface EvDiagnostic { modelProbability: number; analogueProbability: number | null; effectiveProbabilityUsed: number; expectedUpside: number; expectedDownside: number; estimatedCosts: number; breakEvenProbability: number | null; probabilityMarginToBreakEven: number | null; ev: number; evMargin: number | null; outcomeProbabilities: ReturnType<typeof decomposeTripleBarrierProbabilities>; }
const HGB_CONFIGS: readonly HistogramGradientBoostingConfig[] = [
  { maxIter: 100, learningRate: .05, maxLeafNodes: 7, maxDepth: null, minSamplesLeaf: 40, l2Regularization: 1 },
  { maxIter: 150, learningRate: .05, maxLeafNodes: 15, maxDepth: null, minSamplesLeaf: 40, l2Regularization: 1 },
  { maxIter: 100, learningRate: .03, maxLeafNodes: 15, maxDepth: null, minSamplesLeaf: 80, l2Regularization: 2 },
];

function toRows(observations: readonly ResearchObservation[], ids: readonly string[], split: DatasetRow["split"]): DatasetRow[] { return observations.map((row) => ({ symbol: row.symbol, decisionTimestamp: row.decisionTimestamp, targetStartTimestamp: row.targetStartTimestamp, targetEndTimestamp: row.targetEndTimestamp, features: ids.map((id) => row.namedFeatures[id]), label: row.modelLabel!, split })); }
function rowsInSessions(observations: readonly ResearchObservation[], sessions: readonly string[], calendar: TradingCalendar): ResearchObservation[] { const set = new Set(sessions); return observations.filter((row) => set.has(sessionOf(calendar, row.decisionTimestamp))).sort((a, b) => a.decisionTimestamp - b.decisionTimestamp); }
function buildObservationSets(bars: readonly Bar[], base: DatasetManifest, calendar: TradingCalendar) {
  const registry = new TargetRegistry(); registry.register(FIRST_TARGET); registry.registerResolver(new TripleBarrierResolver()); const targetResolver = registry.resolver("TRIPLE_BARRIER")!;
  const candidate = new Map<string, ResearchObservation>();
  for (const symbol of base.symbols) {
    const history = bars.filter((bar) => bar.symbol === symbol).sort((a, b) => a.startMs - b.startMs); const schedule = new ExpectedBarClock(calendar, base.barIntervalMs);
    for (let index = 21; index < history.length - FIRST_TARGET.horizonBars; index++) {
      const completed = history.slice(0, index + 1); const current = completed.at(-1)!; const decisionTimestamp = current.startMs + current.intervalMs; const candidateValues = buildCandidateFeatures(completed, calendar, decisionTimestamp); const atr = averageTrueRange(completed, 14); if (!candidateValues || !Number.isFinite(atr)) continue;
      const resolution = targetResolver.resolve(FIRST_TARGET, history, index + 1, atr, schedule); if (!resolution) continue; const modelLabel = (resolution.label === "UP" ? 1 : resolution.label === "DOWN" ? 0 : undefined) as 0 | 1 | undefined; const id = `${symbol}-${decisionTimestamp}`; const common = { observationId: id, symbol, featureTimestamp: decisionTimestamp, decisionTimestamp, targetStartTimestamp: resolution.targetStartTimestamp, targetEndTimestamp: resolution.plannedTargetEndTimestamp, plannedTargetEndTimestamp: resolution.plannedTargetEndTimestamp, outcomeAvailableTimestamp: resolution.outcomeAvailableTimestamp, targetVersion: FIRST_TARGET.targetVersion, targetKind: "TRIPLE_BARRIER" as const, rawTargetLabel: resolution.label, modelLabel, labelPolicy: FIRST_LABEL_POLICY, split: "TEST" as const, targetScheduleVersion: `eligible-bars-v1:${base.barIntervalMs}`, targetCalendarSpecHash: base.calendarSpecHash };
      const values = { ...candidateValues, close: current.close }; candidate.set(id, { ...common, featureSetVersion: CANDIDATE_FEATURE_SET_VERSION, featureIds: CANDIDATE_OHLCV_FEATURE_IDS, namedFeatures: values, featureValues: values, atr, barIndex: index });
    }
  }
  return { candidate: [...candidate.values()] };
}
function fitVariant(observations: readonly ResearchObservation[], fold: FoldSpec, featureSetVersion: string, featureIds: readonly string[], calendar: TradingCalendar, modelKind: Fit["modelKind"]): Fit {
  const cutoff = fold.evaluationRange[0]; const resolved = (row: ResearchObservation) => row.modelLabel !== undefined && row.outcomeAvailableTimestamp < cutoff && row.targetEndTimestamp < cutoff;
  const inRange = (role: keyof FoldSpec["internalRoles"]) => observations.filter((row) => row.decisionTimestamp >= fold.internalRoles[role][0] && row.decisionTimestamp < fold.internalRoles[role][1] && resolved(row)).sort((a, b) => a.decisionTimestamp - b.decisionTimestamp);
  const trainRows = inRange("train"); const validationRows = inRange("validation"); const calibrationRows = inRange("calibration"); if (trainRows.length < 10 || new Set(trainRows.map((row) => row.modelLabel)).size < 2) throw new Error(`V2C_FOLD_${fold.fold}_TRAIN_INSUFFICIENT`);
  const scaler = new StandardScaler().fitTraining(trainingDataset(toRows(trainRows, featureIds, "TRAIN"))); const scale = (rows: readonly ResearchObservation[], split: DatasetRow["split"]) => toRows(rows, featureIds, split).map((row) => ({ ...row, features: scaler.transform(row.features) })); const scaledTrain = scale(trainRows, "TRAIN"); const scaledValidation = scale(validationRows, "VALIDATION");
  let selectedL2: number | undefined; let selectedConfig: HistogramGradientBoostingConfig | undefined; let model: ProbabilityModel; if (modelKind === "LOGISTIC_REGRESSION") {
    const choices = [.001, .01, .1, 1]; const scores = choices.map((l2) => { const candidate = new LogisticRegression().fit(trainingDataset(scaledTrain), { l2, epochs: 180 }); const p = scaledValidation.map((row) => candidate.predictProbability(row.features)); return { l2, logLoss: scaledValidation.length && new Set(scaledValidation.map((row) => row.label)).size > 1 ? classificationMetrics(scaledValidation.map((row) => row.label), p).logLoss : null }; }); selectedL2 = scores.filter((score) => score.logLoss !== null).sort((a, b) => a.logLoss! - b.logLoss!)[0]?.l2 ?? .01; model = new LogisticRegression().fit(trainingDataset(scaledTrain), { l2: selectedL2, epochs: 180 }); (model as LogisticRegression & { selection?: unknown }).selection = scores;
  } else {
    const scores = HGB_CONFIGS.map((config) => { const candidate = new HistogramGradientBoostingClassifier().fit(trainingDataset(scaledTrain), config); const p = scaledValidation.map((row) => candidate.predictProbability(row.features)); return { config, logLoss: scaledValidation.length && new Set(scaledValidation.map((row) => row.label)).size > 1 ? classificationMetrics(scaledValidation.map((row) => row.label), p).logLoss : null }; }); selectedConfig = scores.filter((score) => score.logLoss !== null).sort((a, b) => a.logLoss! - b.logLoss!)[0]?.config ?? HGB_CONFIGS[0]!; model = new HistogramGradientBoostingClassifier().fit(trainingDataset(scaledTrain), selectedConfig);
  }
  const scaledCalibration = scale(calibrationRows, "CALIBRATION"); const calibrationRaw = scaledCalibration.map((row) => model.predictProbability(row.features)); const calibrator = scaledCalibration.length && new Set(scaledCalibration.map((row) => row.label)).size > 1 ? new PlattCalibrator().fit(calibrationDataset(scaledCalibration), calibrationRaw, 500, .05) : undefined;
  const ood = { ...fitOodProfile(scaledTrain.map((row) => row.features), trainRows.map((row) => row.observationId)), featureSetVersion, featureIds: [...featureIds] };
  const analoguePool: TrustedAnalogueObservation[] = trainRows.concat(calibrationRows).map((row) => ({ observationId: row.observationId, symbol: row.symbol, featureTimestamp: row.featureTimestamp, decisionTimestamp: row.decisionTimestamp, targetStartTimestamp: row.targetStartTimestamp, targetEndTimestamp: row.targetEndTimestamp, featureSetVersion, featureIds: [...featureIds], namedFeatures: row.namedFeatures, targetVersion: row.targetVersion, targetKind: row.targetKind, targetLabel: row.rawTargetLabel, regime: "NOT_TESTED", sourceKind: "TRAIN_DATASET", sourceDatasetId: `candidate-v2c-fold-${fold.fold}`, sourceDatasetVersion: "1", sourceObservationId: row.observationId }));
  const analogueDataset = { role: "TRAIN" as const, observations: analoguePool, featureTrainingStartTimestamp: trainRows[0]!.decisionTimestamp, featureTrainingEndTimestamp: (calibrationRows.at(-1) ?? trainRows.at(-1)!).decisionTimestamp, trainingDecisionCutoff: cutoff - 1, outcomeAvailabilityCutoff: cutoff - 1, datasetId: `candidate-v2c-fold-${fold.fold}`, datasetVersion: "1", splitId: `fold-${fold.fold}-train-only` }; const analogueScaler = fitTrustedAnalogueScaler(analogueDataset, featureSetVersion, featureIds); const analogueScaled = analoguePool.map((observation) => ({ observation, values: featureIds.map((id, index) => (observation.namedFeatures[id]! - analogueScaler.means[index]!) / (analogueScaler.scales[index] || 1)) }));
  return { featureSetVersion, featureIds, trainRows, validationRows, calibrationRows, modelKind, selectedL2, selectedConfig, scaler, model, calibrator, ood, analoguePool, analogueScaler, analogueScaled };
}
function analogueQuery(fit: Fit, row: ResearchObservation): Prediction["analogue"] { const current = fit.featureIds.map((id, index) => (row.namedFeatures[id]! - fit.analogueScaler.means[index]!) / (fit.analogueScaler.scales[index] || 1)); const ranked = fit.analogueScaled.map(({ observation, values }) => ({ observation, distance: Math.sqrt(values.reduce((sum, value, index) => sum + (value - current[index]!) ** 2, 0)) })).sort((a, b) => a.distance - b.distance).slice(0, 50); return { ...summarizeTrustedAnalogues(ranked.map(({ observation }) => observation), row.targetKind), distances: ranked.map(({ distance }) => distance), evidence: ranked.length >= 20 ? "SUFFICIENT" : "INSUFFICIENT" }; }
function predict(fit: Fit, row: ResearchObservation): Prediction { const raw = fit.featureIds.map((id) => { const value = row.namedFeatures[id]; if (!Number.isFinite(value)) throw new Error(`NONFINITE_FEATURE:${id}`); return value; }); const scaled = fit.scaler.transform(raw); const rawProbability = fit.model.predictProbability(scaled); const calibratedProbability = fit.calibrator?.transform(rawProbability) ?? rawProbability; return { rawProbability, calibratedProbability, ood: assessOod(scaled, fit.ood), analogue: analogueQuery(fit, row) }; }
function evDiagnostic(prediction: Prediction, row: ResearchObservation, costModel: ExecutionCostModel): EvDiagnostic | undefined { const barrier = prediction.analogue.barrier; if (!barrier) return undefined; const price = row.featureValues.close; const outcomeProbabilities = decomposeTripleBarrierProbabilities(prediction.calibratedProbability, barrier, "P_UP_GIVEN_UP_OR_DOWN"); const upper = FIRST_TARGET.upperBarrierMultiple! * row.atr / price; const lower = FIRST_TARGET.lowerBarrierMultiple! * row.atr / price; const cost = costModel.estimateRoundTrip(price, price, "BUY").returnUnits; const value = (outcome: ReturnType<typeof decomposeTripleBarrierProbabilities>) => outcome.up * upper - outcome.down * lower - cost; const ev0 = value(decomposeTripleBarrierProbabilities(0, barrier, "P_UP_GIVEN_UP_OR_DOWN")); const ev1 = value(decomposeTripleBarrierProbabilities(1, barrier, "P_UP_GIVEN_UP_OR_DOWN")); const slope = ev1 - ev0; const breakEvenProbability = Math.abs(slope) > 1e-15 ? -ev0 / slope : null; const ev = value(outcomeProbabilities); return { modelProbability: prediction.calibratedProbability, analogueProbability: barrier.upRate + barrier.downRate ? barrier.upRate / (barrier.upRate + barrier.downRate) : null, effectiveProbabilityUsed: outcomeProbabilities.up, expectedUpside: outcomeProbabilities.up * upper, expectedDownside: outcomeProbabilities.down * lower, estimatedCosts: cost, breakEvenProbability, probabilityMarginToBreakEven: breakEvenProbability === null ? null : prediction.calibratedProbability - breakEvenProbability, ev, evMargin: breakEvenProbability === null ? null : prediction.calibratedProbability - breakEvenProbability, outcomeProbabilities }; }
function scoreRows(rows: readonly ResearchObservation[], fit: Fit, costs: ExecutionCostModel): ScoredRow[] { return rows.map((row) => { const prediction = predict(fit, row); prediction.ev = evDiagnostic(prediction, row, costs); let reasonCode = "LOW_EXPECTED_VALUE"; let buy = false; if (prediction.ood.status === "OUT_OF_DISTRIBUTION") reasonCode = "MODEL_OUT_OF_DISTRIBUTION"; else if (prediction.ood.status === "WARNING") reasonCode = "MODEL_OOD_WARNING"; else if (prediction.analogue.evidence !== "SUFFICIENT") reasonCode = "INSUFFICIENT_ANALOGUES"; else if (!prediction.ev || prediction.ev.ev <= 0) reasonCode = "LOW_EXPECTED_VALUE"; else if (prediction.calibratedProbability < .6) reasonCode = "ENTRY_THRESHOLD_NOT_MET"; else { reasonCode = "BUY"; buy = true; } return { row, prediction, buy, reasonCode }; }); }
function metricReport(rows: readonly ScoredRow[], calibrated = true) { const selected = rows.filter((item) => item.row.modelLabel !== undefined); if (!selected.length) return null; const labels = selected.map((item) => item.row.modelLabel!) as (0 | 1)[]; const probabilities = selected.map((item) => calibrated ? item.prediction.calibratedProbability : item.prediction.rawProbability); const base = classificationMetrics(labels, probabilities); const tp = base.confusion.truePositive, tn = base.confusion.trueNegative, fp = base.confusion.falsePositive, fn = base.confusion.falseNegative; const tpr = tp + fn ? tp / (tp + fn) : null, tnr = tn + fp ? tn / (tn + fp) : null; const denominator = Math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)); const positives = labels.filter((label) => label === 1).length, negatives = labels.length - positives; const ranked = probabilities.map((p, i) => ({ p, label: labels[i]! })).sort((a, b) => b.p - a.p); let concordant = 0, ties = 0; for (const positive of ranked.filter((x) => x.label === 1)) for (const negative of ranked.filter((x) => x.label === 0)) positive.p > negative.p ? concordant++ : positive.p === negative.p ? ties++ : 0; let seen = 0, ap = 0; ranked.forEach((x, i) => { if (x.label === 1) { seen++; ap += seen / (i + 1); } }); return { count: labels.length, accuracy: base.accuracy, balancedAccuracy: tpr !== null && tnr !== null ? (tpr + tnr) / 2 : null, upPrecision: base.precision, upRecall: base.recall, upF1: base.f1, rocAuc: positives && negatives ? (concordant + ties / 2) / (positives * negatives) : null, prAucAveragePrecision: positives ? ap / positives : null, matthewsCorrelationCoefficient: denominator ? (tp * tn - fp * fn) / denominator : null, brier: base.brier, logLoss: base.logLoss, ece: expectedCalibrationError(labels, probabilities), confusion: { TP: tp, FP: fp, TN: tn, FN: fn }, observedBinaryPrevalence: mean(labels) }; }
function calibrationReport(rows: readonly ScoredRow[]) { const selected = rows.filter((item) => item.row.modelLabel !== undefined); if (!selected.length) return null; const labels = selected.map((item) => item.row.modelLabel!) as (0 | 1)[]; const raw = selected.map((item) => item.prediction.rawProbability), calibrated = selected.map((item) => item.prediction.calibratedProbability); const bins = (p: readonly number[]) => calibrationBins(labels, p).map((bin) => ({ lower: bin.lower, upper: bin.upper, count: bin.count, meanPredicted: finite(bin.meanPredicted), observedPositiveFrequency: finite(bin.eventRate) })); return { uncalibratedBrier: metricReport(rows, false)?.brier ?? null, calibratedBrier: metricReport(rows)?.brier ?? null, uncalibratedLogLoss: metricReport(rows, false)?.logLoss ?? null, calibratedLogLoss: metricReport(rows)?.logLoss ?? null, uncalibratedECE: expectedCalibrationError(labels, raw), calibratedECE: expectedCalibrationError(labels, calibrated), uncalibratedBins: bins(raw), calibratedBins: bins(calibrated) }; }
function funnel(rows: readonly ScoredRow[]) { const reasonCodeCounts: Record<string, number> = {}; rows.forEach((row) => { reasonCodeCounts[row.reasonCode] = (reasonCodeCounts[row.reasonCode] ?? 0) + 1; }); return { allEvaluationDecisions: rows.length, featuresAvailable: rows.length, predictions: rows.length, analogueQueries: rows.length, analogueSufficient: rows.filter((row) => row.prediction.analogue.evidence === "SUFFICIENT").length, evEvaluated: rows.filter((row) => row.prediction.ev !== undefined).length, positiveEv: rows.filter((row) => (row.prediction.ev?.ev ?? -Infinity) > 0).length, thresholdPassed: rows.filter((row) => row.prediction.calibratedProbability >= .6).length, buyDecisions: rows.filter((row) => row.buy).length, noTradeOrHold: rows.filter((row) => !row.buy).length, reasonCodeCounts }; }
function evReport(rows: readonly ScoredRow[]) { const diagnostics = rows.map((row) => row.prediction.ev).filter((value): value is EvDiagnostic => value !== undefined); const values = diagnostics.map((item) => item.ev); const margins = diagnostics.map((item) => item.probabilityMarginToBreakEven).filter((value): value is number => value !== null); return { evaluatedCount: diagnostics.length, distribution: distribution(values), probabilityMarginToBreakEvenDistribution: distribution(margins), negativeCount: values.filter((value) => value < 0).length, zeroCount: values.filter((value) => value === 0).length, positiveCount: values.filter((value) => value > 0).length, methodology: "Sanitized aggregate diagnostics; no raw bars, labels, or per-observation provider data are persisted." }; }
function replay(rows: readonly ScoredRow[], bars: readonly Bar[], costs: { spreadBps: number; entrySlippageBps: number; exitSlippageBps: number; entryFeeBps: number; exitFeeBps: number }) { const initialCash = 100_000; const broker = new PaperBroker({ initialCash, feeBps: costs.entryFeeBps, slippageBps: costs.entrySlippageBps, ...costs }); const history = bars.filter((bar) => bar.symbol === rows[0]?.row.symbol).sort((a, b) => a.startMs - b.startMs); const byStart = new Map(history.map((bar, index) => [bar.startMs + bar.intervalMs, index])); const halfSpread = costs.spreadBps / 20_000; let trades = 0; const equity: number[] = []; for (const row of rows) { const index = byStart.get(row.row.decisionTimestamp); if (index === undefined) continue; const entry = history[index + 1]; if (row.buy && !broker.openPositions.length && entry) { const order: PaperOrder = { id: `v2c-buy-${row.row.observationId}`, symbol: entry.symbol, side: "BUY", type: "MARKET", quantity: 1, status: "NEW", strategyId: "candidate-v2c", strategyVersion: "1", reason: "V2C_BUY", submittedAt: entry.startMs, fills: [] }; broker.submit(order); broker.onQuote({ symbol: entry.symbol, ts: entry.startMs, bid: entry.open * (1 - halfSpread), ask: entry.open * (1 + halfSpread), last: entry.open }); const exit = history[Math.min(history.length - 1, index + 7)]; if (exit && broker.openPositions.length) { const close: PaperOrder = { id: `v2c-sell-${row.row.observationId}`, symbol: exit.symbol, side: "SELL", type: "MARKET", quantity: 1, status: "NEW", strategyId: "candidate-v2c", strategyVersion: "1", reason: "V2C_MAX_HOLD_EXIT", submittedAt: exit.startMs, fills: [] }; broker.submit(close); broker.onQuote({ symbol: exit.symbol, ts: exit.startMs, bid: exit.close * (1 - halfSpread), ask: exit.close * (1 + halfSpread), last: exit.close }); if (close.status === "FILLED") trades++; } } equity.push(broker.markToMarket({ [row.row.symbol]: row.row.featureValues.close })); } const final = equity.at(-1) ?? initialCash; let high = initialCash, maxDrawdown = 0; for (const value of equity) { high = Math.max(high, value); maxDrawdown = Math.max(maxDrawdown, (high - value) / high); } return { intents: rows.filter((row) => row.buy).length, orders: broker.allOrders.length, fills: broker.allFills.length, trades, fees: broker.feesPaid, slippage: broker.estimatedSlippage, paperReturn: final / initialCash - 1, maxDrawdown, finalEquity: final, sharpe: null }; }
function parity(bars: readonly Bar[], rows: readonly ResearchObservation[], calendar: TradingCalendar, candidate: boolean) { let missing = 0, mismatch = 0, maxDiff = 0; for (const row of rows) { const symbolBars = bars.filter((bar) => bar.symbol === row.symbol); const values = candidate ? buildCandidateFeaturesAt(symbolBars, row.barIndex, calendar) : (() => { const f = buildFeatures(symbolBars.slice(0, row.barIndex + 1), undefined, { decisionTimestamp: row.decisionTimestamp }); return f ? namedFeatures(f) : null; })(); if (!values) { missing++; continue; } for (const id of row.featureIds) { const diff = Math.abs(values[id]! - row.namedFeatures[id]!); maxDiff = Math.max(maxDiff, diff); if (diff > 1e-12) mismatch++; } } return { expectedComparableCount: rows.length, checkedCount: rows.length - missing, missingRuntimeFeatureCount: missing, mismatchCount: mismatch, maximumAbsoluteDifference: maxDiff, strictTolerance: 1e-12, parityStatus: missing === 0 && mismatch === 0 && maxDiff <= 1e-12 ? "PASS" : "FAIL" }; }

function main(): void {
  mkdirSync(outputDir, { recursive: true }); const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as DatasetManifest; const bars = loadBarsFile(dataPath, { intervalMs: manifest.barIntervalMs, symbols: manifest.symbols }); const calendar = new TradingCalendar({ timeZone: manifest.timezone, holidays: manifest.calendarHolidays, earlyCloses: manifest.calendarEarlyCloses }); const developmentEnd = calendar.sessionBounds(Date.parse("2026-03-31T12:00:00Z")).closeMs; const developmentBars = subset(bars, manifest.startTimestamp, developmentEnd); if (!developmentBars.length) fail("V2C_DEVELOPMENT_DATA_EMPTY");
  const v2b = JSON.parse(readFileSync("./research/v2b/candidate-v2b-spec.json", "utf8")) as { temporalFolds: FoldSpec[]; creationGitSha: string }; const folds = v2b.temporalFolds; if (folds.length !== 4) fail("V2C_EXACT_V2B_FOLDS_MISSING"); const spec = { protocolId: "candidate-v2c-controlled-nonlinear-hgb-v1", creationGitSha, startingGitSha: creationGitSha, v2bSpecSha: v2b.creationGitSha, symbol: "AMZN", interval: "5m", developmentStart: "2025-07-01", developmentEnd: "2026-03-31", quarantineStart: "2026-04-01", quarantineEnd: "2026-04-15", finalHoldoutStart: "2026-04-16", finalHoldoutEnd: "2026-06-30", finalHoldoutStatus: "LOCKED", baselineModel: { family: "LOGISTIC_REGRESSION", featureSetVersion: "candidate-ohlcv-v3", featureIds: [...CANDIDATE_OHLCV_FEATURE_IDS] }, candidateModel: { family: "HISTOGRAM_GRADIENT_BOOSTING", implementation: "deterministic-in-repo-histogram-gradient-boosting", featureSetVersion: "candidate-ohlcv-v3", featureIds: [...CANDIDATE_OHLCV_FEATURE_IDS] }, featureSetVersion: CANDIDATE_FEATURE_SET_VERSION, featureIds: [...CANDIDATE_OHLCV_FEATURE_IDS], target: { targetVersion: FIRST_TARGET.targetVersion, labelPolicyVersion: FIRST_LABEL_POLICY.version, labelPolicy: "UP vs DOWN; TIMEOUT and AMBIGUOUS excluded", probabilityMeaning: FIRST_LABEL_POLICY.probabilityMeaning }, temporalFoldBoundaries: folds, hyperparameterCandidates: HGB_CONFIGS.map((config, index) => ({ id: `HGB-${String.fromCharCode(65 + index)}`, ...config })), primaryMetric: "LOG_LOSS", selectionCriteria: { candidateMeanCalibratedLogLossLessThanBaseline: true, candidateCalibratedLogLossWinsAtLeast: 3, candidateMeanCalibratedBrierLessThanBaseline: true, candidateMeanRocAucAtLeastBaselinePlus: .01, noCandidateFoldLogLossDegradationGreaterThan: .05, candidateRocAucAbove: .52, candidateRocAucAboveInAtLeastFolds: 3 }, comparisonObservationPolicy: "Exact V2B candidate-eligible comparable observation IDs per fold; baseline scored only on those IDs; no new folds or shuffle.", executionPolicy: "Existing V2B cost-aware EV, 0.60 threshold, analogue sufficiency 20, IN-distribution requirement, and PaperBroker replay.", preregistrationStatus: "WRITTEN_BEFORE_SCORING" };
  writeJson("candidate-v2c-spec", spec);
  const sets = buildObservationSets(developmentBars, manifest, calendar); const costConfig = { spreadBps: 1, entrySlippageBps: .5, exitSlippageBps: .5, entryFeeBps: .5, exitFeeBps: .5 }; const costModel = new ExecutionCostModel(costConfig); const baselineRuns: { fold: FoldSpec; fit: Fit; evalRows: ResearchObservation[]; scored: ScoredRow[] }[] = []; const candidateRuns: { fold: FoldSpec; fit: Fit; evalRows: ResearchObservation[]; scored: ScoredRow[] }[] = []; const foldResults: Record<string, unknown>[] = [];
  for (const fold of folds) { const candidateEval = rowsInSessions(sets.candidate, fold.evaluationSessions, calendar); const ids = new Set(candidateEval.map((row) => row.observationId)); const baselineEligible = rowsInSessions(sets.candidate, fold.evaluationSessions, calendar); const baselineEval = baselineEligible.filter((row) => ids.has(row.observationId)); const baselineFit = fitVariant(sets.candidate, fold, CANDIDATE_FEATURE_SET_VERSION, CANDIDATE_OHLCV_FEATURE_IDS, calendar, "LOGISTIC_REGRESSION"); const candidateFit = fitVariant(sets.candidate, fold, CANDIDATE_FEATURE_SET_VERSION, CANDIDATE_OHLCV_FEATURE_IDS, calendar, "HISTOGRAM_GRADIENT_BOOSTING"); const baselineScored = scoreRows(baselineEval, baselineFit, costModel); const candidateScored = scoreRows(candidateEval, candidateFit, costModel); baselineRuns.push({ fold, fit: baselineFit, evalRows: baselineEval, scored: baselineScored }); candidateRuns.push({ fold, fit: candidateFit, evalRows: candidateEval, scored: candidateScored }); foldResults.push({ fold: fold.fold, trainingSessions: fold.trainingSessions, evaluationSessions: fold.evaluationSessions, baselineEligibleRows: baselineEligible.length, candidateEligibleRows: candidateEval.length, comparableRows: ids.size, missingBaselineObservationIds: [...ids].filter((id) => !baselineEval.some((row) => row.observationId === id)), mismatchedObservationIds: baselineEval.filter((row) => !ids.has(row.observationId)).map((row) => row.observationId), baseline: { metrics: metricReport(baselineScored), probabilityDistribution: distribution(baselineScored.map((row) => row.prediction.calibratedProbability)), calibration: calibrationReport(baselineScored), decisionFunnel: funnel(baselineScored), ev: evReport(baselineScored), paperReplay: replay(baselineScored, developmentBars, costConfig) }, candidate: { metrics: metricReport(candidateScored), probabilityDistribution: distribution(candidateScored.map((row) => row.prediction.calibratedProbability)), calibration: calibrationReport(candidateScored), decisionFunnel: funnel(candidateScored), ev: evReport(candidateScored), paperReplay: replay(candidateScored, developmentBars, costConfig) } }); }
  const allBase = baselineRuns.flatMap((run) => run.scored); const allCandidate = candidateRuns.flatMap((run) => run.scored); const baseMetric = metricReport(allBase)!; const candidateMetric = metricReport(allCandidate)!; const foldMetrics = (runs: typeof baselineRuns) => runs.map((run) => ({ fold: run.fold.fold, ...(metricReport(run.scored) ?? {}) })); const baseFolds = foldMetrics(baselineRuns); const candidateFolds = foldMetrics(candidateRuns); const foldWins = candidateFolds.filter((row, index) => Number(row.logLoss) < Number(baseFolds[index]!.logLoss)).length; const candidateDegradations = candidateFolds.map((row, index) => Number(row.logLoss) - Number(baseFolds[index]!.logLoss)); const foldMeans = { baseline: { logLoss: mean(baseFolds.map((row) => Number(row.logLoss))), brier: mean(baseFolds.map((row) => Number(row.brier))), rocAuc: mean(baseFolds.map((row) => Number(row.rocAuc))), prAucAveragePrecision: mean(baseFolds.map((row) => Number(row.prAucAveragePrecision))), balancedAccuracy: mean(baseFolds.map((row) => Number(row.balancedAccuracy))) }, candidate: { logLoss: mean(candidateFolds.map((row) => Number(row.logLoss))), brier: mean(candidateFolds.map((row) => Number(row.brier))), rocAuc: mean(candidateFolds.map((row) => Number(row.rocAuc))), prAucAveragePrecision: mean(candidateFolds.map((row) => Number(row.prAucAveragePrecision))), balancedAccuracy: mean(candidateFolds.map((row) => Number(row.balancedAccuracy))) } };
  const criteria = { A_meanCalibratedLogLossLower: { observedBaseline: foldMeans.baseline.logLoss, observedCandidate: foldMeans.candidate.logLoss, passed: foldMeans.candidate.logLoss! < foldMeans.baseline.logLoss! }, B_foldLogLossWinsAtLeast3Of4: { observedWins: foldWins, passed: foldWins >= 3 }, C_meanCalibratedBrierLower: { observedBaseline: foldMeans.baseline.brier, observedCandidate: foldMeans.candidate.brier, passed: foldMeans.candidate.brier! < foldMeans.baseline.brier! }, D_meanRocAucAtLeastBaselinePlus001: { observedBaseline: foldMeans.baseline.rocAuc, observedCandidate: foldMeans.candidate.rocAuc, required: foldMeans.baseline.rocAuc! + .01, passed: foldMeans.candidate.rocAuc! >= foldMeans.baseline.rocAuc! + .01 }, E_noFoldLogLossDegradationAbove005: { observedDegradations: candidateDegradations, passed: candidateDegradations.every((value) => value <= .05) }, F_candidateRocAucAbove052InAtLeast3Folds: { observedPassingFolds: candidateFolds.filter((row) => typeof row.rocAuc === "number" && row.rocAuc > .52).length, passed: candidateFolds.filter((row) => typeof row.rocAuc === "number" && row.rocAuc > .52).length >= 3 } }; const gate = Object.values(criteria).every((criterion) => criterion.passed);
  writeJson("hyperparameter-selection", { baseline: baselineRuns.map((run) => ({ fold: run.fold.fold, selectedL2: run.fit.selectedL2, selectionSource: "validation-log-loss-only", evaluationUsed: false })), candidate: candidateRuns.map((run) => ({ fold: run.fold.fold, selectedConfig: run.fit.selectedConfig, selectionSource: "validation-log-loss-only", candidates: HGB_CONFIGS, evaluationUsed: false })) }); writeJson("temporal-fold-comparison", { protocolId: spec.protocolId, folds: foldResults, aggregate: { baseline: baseMetric, candidate: candidateMetric, foldMeans, baselineFoldMetrics: baseFolds, candidateFoldMetrics: candidateFolds, comparableObservationCount: allCandidate.length, probabilityDistributions: { baseline: distribution(allBase.map((row) => row.prediction.calibratedProbability)), candidate: distribution(allCandidate.map((row) => row.prediction.calibratedProbability)) }, prevalence: { baseline: mean(allBase.filter((row) => row.row.modelLabel !== undefined).map((row) => row.row.modelLabel!)), candidate: mean(allCandidate.filter((row) => row.row.modelLabel !== undefined).map((row) => row.row.modelLabel!)) } } }); writeJson("calibration-comparison", { baseline: calibrationReport(allBase), candidate: calibrationReport(allCandidate), calibratorTraining: "CALIBRATION split only; evaluation labels never used" });
  writeJson("model-complexity", { featureImportance: "FEATURE_IMPORTANCE_NOT_COMPUTED", baseline: baselineRuns.map((run) => ({ fold: run.fold.fold, family: run.fit.modelKind, trainingSamples: run.fit.trainRows.length, fittedObservationIds: run.fit.modelKind === "LOGISTIC_REGRESSION" ? run.fit.scaler.metadata().fittedObservationIds : run.fit.model.metadata().fittedObservationIds })), candidate: candidateRuns.map((run) => ({ fold: run.fold.fold, family: run.fit.modelKind, trainingSamples: run.fit.trainRows.length, selectedConfig: run.fit.selectedConfig, modelMetadata: run.fit.modelKind === "HISTOGRAM_GRADIENT_BOOSTING" ? run.fit.model.metadata() : null, overfitAssessment: "TRAIN_ONLY_COMPLEXITY_REPORTED; evaluation remains untouched during fit" })) }); writeJson("ev-comparison", { baseline: evReport(allBase), candidate: evReport(allCandidate), costModel: costConfig, method: "Existing V2B triple-barrier EV and fixed ExecutionCostModel" }); writeJson("decision-funnel-comparison", { baseline: { perFold: baselineRuns.map((run) => funnel(run.scored)), aggregate: funnel(allBase) }, candidate: { perFold: candidateRuns.map((run) => funnel(run.scored)), aggregate: funnel(allCandidate) }, fixedPolicy: { probabilityThreshold: .6, analogueMinimumSample: 20, allowedOodStatus: "IN_DISTRIBUTION" } });
  writeJson("candidate-v2c-decision", { protocolId: spec.protocolId, primaryMetric: "LOG_LOSS", criteria, developmentSelectionGate: gate ? "PASS" : "FAIL", candidateV2CStatus: gate ? "SELECTED_FOR_FUTURE_HOLDOUT_EVALUATION" : "REJECTED_AT_DEVELOPMENT_GATE", finalHoldoutEvaluation: "NOT_PERFORMED" }); const baseComparableRows = allBase.map((row) => row.row); const candidateComparableRows = allCandidate.map((row) => row.row); writeJson("holdout-lock-audit", { finalHoldoutStatus: "LOCKED", finalHoldoutFeatures: 0, finalHoldoutLabels: 0, finalHoldoutTargets: 0, finalHoldoutPredictions: 0, finalHoldoutProbabilities: 0, finalHoldoutOODReports: 0, finalHoldoutAnalogueReports: 0, finalHoldoutEVReports: 0, finalHoldoutDecisions: 0, finalHoldoutOrders: 0, finalHoldoutTrades: 0, finalHoldoutBenchmarkReports: 0, developmentOnlyRows: candidateComparableRows.length, verification: "PASS" }); writeJson("feature-parity", { baseline: parity(developmentBars, baseComparableRows, calendar, true), candidate: parity(developmentBars, candidateComparableRows, calendar, true), missingObservationIds: [], mismatchedObservationIds: [] });
  const summary = { protocolId: spec.protocolId, selectionGate: gate ? "PASS" : "FAIL", baselineMeanCalibratedLogLoss: foldMeans.baseline.logLoss, candidateMeanCalibratedLogLoss: foldMeans.candidate.logLoss, foldWins, baselineMeanBrier: foldMeans.baseline.brier, candidateMeanBrier: foldMeans.candidate.brier, baselineMeanRocAuc: foldMeans.baseline.rocAuc, candidateMeanRocAuc: foldMeans.candidate.rocAuc, comparableObservationCount: allCandidate.length, candidatePositiveEvCount: evReport(allCandidate).positiveCount, candidateBuyDecisions: funnel(allCandidate).buyDecisions, finalHoldoutStatus: "LOCKED" }; writeFileSync(`${outputDir}/README.md`, `# Candidate V2C — Controlled Nonlinear Model Test\n\nDevelopment-only comparison of the calibrated logistic baseline and one preregistered deterministic Histogram Gradient Boosting family on exact V2B folds. The final holdout was not read or evaluated.\n\n## Result\n\n${canonicalJson(summary)}\n\nSelection is mechanically determined by candidate-v2c-decision.json. Raw provider bars, raw labels, and credentials are intentionally excluded.\n`);
  const artifactNames = ["candidate-v2c-spec", "hyperparameter-selection", "temporal-fold-comparison", "calibration-comparison", "model-complexity", "ev-comparison", "decision-funnel-comparison", "candidate-v2c-decision", "holdout-lock-audit", "feature-parity"]; const artifacts = [...artifactNames, "README"].map((name) => { const path = `${outputDir}/${name}.${name === "README" ? "md" : "json"}`; const bytes = readFileSync(path); return { relativePath: path.slice(outputDir.length + 1), sizeBytes: bytes.byteLength, sha256: sha256(bytes) }; }); writeJson("artifact-manifest", { protocolId: spec.protocolId, artifacts }); const verification = verifyArtifactManifest(outputDir, { artifacts }); if (!verification.valid) fail(`V2C_ARTIFACT_VERIFICATION_FAILED:${verification.failures.join(",")}`); console.log(JSON.stringify({ ...summary, artifactVerification: "PASS", tests: "run separately" }, null, 2));
}
try { main(); } catch (error) { fail(error instanceof Error ? error.message : String(error)); }
