import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import type { Bar, PaperOrder } from "./domain";
import { loadBarsFile } from "./historical-data";
import { TradingCalendar } from "./calendar";
import { averageTrueRange, buildFeatures } from "./features";
import { namedFeatures, OHLCV_FEATURE_IDS, type NamedFeatureVector } from "./feature-schema";
import { type DatasetManifest, FIRST_TARGET, FIRST_LABEL_POLICY } from "./experiment";
import { TargetRegistry } from "./targets";
import { TripleBarrierResolver } from "./experience";
import { ExpectedBarClock } from "./bar-schedule";
import { assessOod, calibrationBins, classificationMetrics, expectedCalibrationError, fitOodProfile, LogisticRegression, PlattCalibrator, StandardScaler, trainingDataset, calibrationDataset, type DatasetObservation, type DatasetRow } from "./ml";
import { fitTrustedAnalogueScaler, summarizeTrustedAnalogues, type TrustedAnalogueObservation } from "./analogues";
import { decomposeTripleBarrierProbabilities } from "./intelligence";
import { ExecutionCostModel } from "./costs";
import { PaperBroker } from "./broker";
import { assertFiniteArtifact, canonicalJson, sanitizeArtifact, verifyArtifactManifest } from "./serialization";
import { sessionPairedBootstrap } from "./v2d-stats";
import { V2D_LABEL_POLICY, V2D_TARGET, V1_TARGET_VERSION } from "./v2d-target";

const args = process.argv.slice(2);
const flag = (name: string, fallback: string) => args.includes(name) ? args[args.indexOf(name) + 1] ?? fallback : fallback;
const dataPath = flag("--data", "./data/amzn-5m-20250701-20260331.csv");
const manifestPath = flag("--manifest", "./research/v2a-amzn-20250701-20260630/manifest.json");
const outputDir = flag("--output", "./research/v2d");
const creationGitSha = (() => { try { return execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim(); } catch { return "unknown"; } })();
const finite = (value: number | undefined | null) => value !== undefined && value !== null && Number.isFinite(value) ? value : null;
const mean = (values: readonly number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : null;
const std = (values: readonly number[]) => { const m = mean(values); return m === null ? null : Math.sqrt(values.reduce((a, b) => a + (b - m) ** 2, 0) / values.length); };
const quantile = (values: readonly number[], q: number) => { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b); const p = (sorted.length - 1) * q; const lo = Math.floor(p), hi = Math.ceil(p); return sorted[lo]! + (sorted[hi]! - sorted[lo]!) * (p - lo); };
const distribution = (values: readonly number[]) => ({ minimum: finite(Math.min(...values)), p05: quantile(values, .05), p25: quantile(values, .25), median: quantile(values, .5), p75: quantile(values, .75), p95: quantile(values, .95), maximum: finite(Math.max(...values)), mean: mean(values), std: std(values) });
const sessionOf = (calendar: TradingCalendar, timestamp: number) => calendar.sessionKey(timestamp);
const writeJson = (name: string, value: unknown) => { const safe = sanitizeArtifact(value); assertFiniteArtifact(safe, name); writeFileSync(`${outputDir}/${name}.json`, canonicalJson(safe)); };

interface FoldSpec { fold: number; trainingSessions: readonly string[]; evaluationSessions: readonly string[]; trainingHistoryRange: readonly [number, number]; evaluationRange: readonly [number, number]; internalRoles: { train: readonly [number, number]; validation: readonly [number, number]; calibration: readonly [number, number] }; }
interface Observation extends DatasetObservation { featureValues: NamedFeatureVector & { close: number }; atr: number; barIndex: number; }
interface Fit { scaler: StandardScaler; model: LogisticRegression; calibrator?: PlattCalibrator; ood: ReturnType<typeof fitOodProfile>; pool: readonly TrustedAnalogueObservation[]; scaledPool: readonly { observation: TrustedAnalogueObservation; values: readonly number[] }[]; analogueMeans: readonly number[]; analogueScales: readonly number[]; selectedL2: number; trainRows: readonly Observation[]; validationRows: readonly Observation[]; calibrationRows: readonly Observation[]; }
interface Prediction { rawProbability: number; calibratedProbability: number; ood: ReturnType<typeof assessOod>; analogue: ReturnType<typeof summarizeTrustedAnalogues> & { distances: readonly number[]; evidence: "INSUFFICIENT" | "SUFFICIENT" }; ev?: Ev; }
interface Scored { row: Observation; prediction: Prediction; buy: boolean; reasonCode: string; }
interface Ev { modelProbability: number; analogueProbability: number | null; effectiveProbabilityUsed: number; expectedUpside: number; expectedDownside: number; estimatedCosts: number; breakEvenProbability: number | null; probabilityMarginToBreakEven: number | null; ev: number; evMargin: number | null; outcomeProbabilities: ReturnType<typeof decomposeTripleBarrierProbabilities>; }

function rowsFor(observations: readonly Observation[], sessions: readonly string[], calendar: TradingCalendar) { const wanted = new Set(sessions); return observations.filter((row) => wanted.has(sessionOf(calendar, row.decisionTimestamp))).sort((a, b) => a.decisionTimestamp - b.decisionTimestamp); }
function toRows(observations: readonly Observation[], split: DatasetRow["split"]): DatasetRow[] { return observations.map((row) => ({ symbol: row.symbol, decisionTimestamp: row.decisionTimestamp, targetStartTimestamp: row.targetStartTimestamp, targetEndTimestamp: row.targetEndTimestamp, features: OHLCV_FEATURE_IDS.map((id) => row.namedFeatures[id]), label: row.modelLabel!, split })); }
function buildObservations(bars: readonly Bar[], manifest: DatasetManifest, calendar: TradingCalendar): Observation[] {
  const registry = new TargetRegistry(); registry.register(FIRST_TARGET); registry.register(V2D_TARGET); registry.registerResolver(new TripleBarrierResolver());
  const resolver = registry.resolver("TRIPLE_BARRIER")!; const result: Observation[] = [];
  for (const symbol of manifest.symbols) {
    const history = bars.filter((bar) => bar.symbol === symbol).sort((a, b) => a.startMs - b.startMs); const schedule = new ExpectedBarClock(calendar, manifest.barIntervalMs);
    for (let index = 21; index < history.length - V2D_TARGET.horizonBars; index++) {
      const completed = history.slice(0, index + 1), current = completed.at(-1)!; const decisionTimestamp = current.startMs + current.intervalMs; const features = buildFeatures(completed, undefined, { decisionTimestamp }); const atr = averageTrueRange(completed, 14); if (!features || !Number.isFinite(atr)) continue;
      const resolution = resolver.resolve(V2D_TARGET, history, index + 1, atr, schedule); if (!resolution) continue; const modelLabel = resolution.label === "UP" ? 1 : resolution.label === "DOWN" ? 0 : undefined; const named = { ...namedFeatures(features), close: current.close };
      result.push({ observationId: `${symbol}-${decisionTimestamp}`, symbol, featureTimestamp: features.ts, decisionTimestamp, targetStartTimestamp: resolution.targetStartTimestamp, targetEndTimestamp: resolution.plannedTargetEndTimestamp, plannedTargetEndTimestamp: resolution.plannedTargetEndTimestamp, outcomeAvailableTimestamp: resolution.outcomeAvailableTimestamp, featureSetVersion: "baseline-ohlcv-v2", featureIds: [...OHLCV_FEATURE_IDS], targetVersion: V2D_TARGET.targetVersion, targetKind: "TRIPLE_BARRIER", namedFeatures: named, rawTargetLabel: resolution.label, modelLabel, labelPolicy: V2D_LABEL_POLICY, split: "TEST", targetScheduleVersion: `eligible-bars-v1:${manifest.barIntervalMs}`, targetCalendarSpecHash: manifest.calendarSpecHash, featureValues: named, atr, barIndex: index });
    }
  }
  return result;
}
function fit(observations: readonly Observation[], fold: FoldSpec): Fit {
  const cutoff = fold.evaluationRange[0]; const usable = (role: keyof FoldSpec["internalRoles"]) => observations.filter((row) => row.decisionTimestamp >= fold.internalRoles[role][0] && row.decisionTimestamp < fold.internalRoles[role][1] && row.modelLabel !== undefined && row.outcomeAvailableTimestamp < cutoff && row.targetEndTimestamp < cutoff).sort((a, b) => a.decisionTimestamp - b.decisionTimestamp);
  const trainRows = usable("train"), validationRows = usable("validation"), calibrationRows = usable("calibration"); if (trainRows.length < 10 || new Set(trainRows.map((row) => row.modelLabel)).size < 2) throw new Error(`V2D_FOLD_${fold.fold}_TRAIN_INSUFFICIENT`);
  const scaler = new StandardScaler().fitTraining(trainingDataset(toRows(trainRows, "TRAIN"))); const scaled = (rows: readonly Observation[], split: DatasetRow["split"]) => toRows(rows, split).map((row) => ({ ...row, features: scaler.transform(row.features) })); const train = scaled(trainRows, "TRAIN"), validation = scaled(validationRows, "VALIDATION"), calibration = scaled(calibrationRows, "CALIBRATION");
  const choices = [.001, .01, .1, 1]; const selection = choices.map((l2) => { const candidate = new LogisticRegression().fit(trainingDataset(train), { l2, epochs: 180 }); const probabilities = validation.map((row) => candidate.predictProbability(row.features)); return { l2, logLoss: validation.length && new Set(validation.map((row) => row.label)).size > 1 ? classificationMetrics(validation.map((row) => row.label), probabilities).logLoss : null }; }); const selectedL2 = selection.find((item) => item.logLoss === Math.min(...selection.filter((item) => item.logLoss !== null).map((item) => item.logLoss!)))?.l2 ?? .01; const model = new LogisticRegression().fit(trainingDataset(train), { l2: selectedL2, epochs: 180 }); const rawCalibration = calibration.map((row) => model.predictProbability(row.features)); const calibrator = calibration.length && new Set(calibration.map((row) => row.label)).size > 1 ? new PlattCalibrator().fit(calibrationDataset(calibration), rawCalibration, 500, .05) : undefined;
  const ood = { ...fitOodProfile(train.map((row) => row.features), trainRows.map((row) => row.observationId)), featureSetVersion: "baseline-ohlcv-v2", featureIds: [...OHLCV_FEATURE_IDS] };
  const pool: TrustedAnalogueObservation[] = trainRows.concat(calibrationRows).map((row) => ({ observationId: row.observationId, symbol: row.symbol, featureTimestamp: row.featureTimestamp, decisionTimestamp: row.decisionTimestamp, targetStartTimestamp: row.targetStartTimestamp, targetEndTimestamp: row.targetEndTimestamp, featureSetVersion: "baseline-ohlcv-v2", featureIds: [...OHLCV_FEATURE_IDS], namedFeatures: row.namedFeatures, targetVersion: V2D_TARGET.targetVersion, targetKind: "TRIPLE_BARRIER", targetLabel: row.rawTargetLabel, regime: "NOT_TESTED", sourceKind: "TRAIN_DATASET", sourceDatasetId: `candidate-v2d-fold-${fold.fold}`, sourceDatasetVersion: "1", sourceObservationId: row.observationId }));
  const analogueDataset = { role: "TRAIN" as const, observations: pool, featureTrainingStartTimestamp: trainRows[0]!.decisionTimestamp, featureTrainingEndTimestamp: (calibrationRows.at(-1) ?? trainRows.at(-1)!).decisionTimestamp, trainingDecisionCutoff: cutoff - 1, outcomeAvailabilityCutoff: cutoff - 1, datasetId: `candidate-v2d-fold-${fold.fold}`, datasetVersion: "1", splitId: `fold-${fold.fold}-train-calibration-only` }; const analogueScaler = fitTrustedAnalogueScaler(analogueDataset, "baseline-ohlcv-v2", OHLCV_FEATURE_IDS); const scaledPool = pool.map((observation) => ({ observation, values: OHLCV_FEATURE_IDS.map((id, index) => (observation.namedFeatures[id]! - analogueScaler.means[index]!) / (analogueScaler.scales[index] || 1)) }));
  return { scaler, model, calibrator, ood, pool, scaledPool, analogueMeans: analogueScaler.means, analogueScales: analogueScaler.scales, selectedL2, trainRows, validationRows, calibrationRows };
}
function analogue(fit: Fit, row: Observation): Prediction["analogue"] { const current = OHLCV_FEATURE_IDS.map((id, index) => (row.namedFeatures[id]! - fit.analogueMeans[index]!) / (fit.analogueScales[index] || 1)); const ranked = fit.scaledPool.map(({ observation, values }) => ({ observation, distance: Math.sqrt(values.reduce((sum, value, index) => sum + (value - current[index]!) ** 2, 0)) })).sort((a, b) => a.distance - b.distance).slice(0, 50); return { ...summarizeTrustedAnalogues(ranked.map((item) => item.observation), "TRIPLE_BARRIER"), distances: ranked.map((item) => item.distance), evidence: ranked.length >= 20 ? "SUFFICIENT" : "INSUFFICIENT" }; }
function ev(prediction: Prediction, row: Observation, costs: ExecutionCostModel): Ev | undefined { const barrier = prediction.analogue.barrier; if (!barrier) return undefined; const price = row.featureValues.close; const outcomeProbabilities = decomposeTripleBarrierProbabilities(prediction.calibratedProbability, barrier, "P_UP_GIVEN_UP_OR_DOWN"); const upper = row.atr / price, lower = row.atr / price, cost = costs.estimateRoundTrip(price, price, "BUY").returnUnits; const value = (p: ReturnType<typeof decomposeTripleBarrierProbabilities>) => p.up * upper - p.down * lower - cost; const ev0 = value(decomposeTripleBarrierProbabilities(0, barrier, "P_UP_GIVEN_UP_OR_DOWN")), ev1 = value(decomposeTripleBarrierProbabilities(1, barrier, "P_UP_GIVEN_UP_OR_DOWN")), slope = ev1 - ev0; const breakEvenProbability = Math.abs(slope) > 1e-15 ? -ev0 / slope : null; return { modelProbability: prediction.calibratedProbability, analogueProbability: barrier.upRate + barrier.downRate ? barrier.upRate / (barrier.upRate + barrier.downRate) : null, effectiveProbabilityUsed: outcomeProbabilities.up, expectedUpside: outcomeProbabilities.up * upper, expectedDownside: outcomeProbabilities.down * lower, estimatedCosts: cost, breakEvenProbability, probabilityMarginToBreakEven: breakEvenProbability === null ? null : prediction.calibratedProbability - breakEvenProbability, ev: value(outcomeProbabilities), evMargin: breakEvenProbability === null ? null : prediction.calibratedProbability - breakEvenProbability, outcomeProbabilities }; }
function score(rows: readonly Observation[], fit: Fit, costs: ExecutionCostModel): Scored[] { return rows.map((row) => { const rawFeatures = OHLCV_FEATURE_IDS.map((id) => row.namedFeatures[id]!); const scaled = fit.scaler.transform(rawFeatures); const rawProbability = fit.model.predictProbability(scaled), calibratedProbability = fit.calibrator?.transform(rawProbability) ?? rawProbability; const prediction = { rawProbability, calibratedProbability, ood: assessOod(scaled, fit.ood), analogue: analogue(fit, row) } as Prediction; prediction.ev = ev(prediction, row, costs); let reasonCode = "LOW_EXPECTED_VALUE", buy = false; if (prediction.ood.status === "OUT_OF_DISTRIBUTION") reasonCode = "MODEL_OUT_OF_DISTRIBUTION"; else if (prediction.ood.status === "WARNING") reasonCode = "MODEL_OOD_WARNING"; else if (prediction.analogue.evidence !== "SUFFICIENT") reasonCode = "INSUFFICIENT_ANALOGUES"; else if (!prediction.ev || prediction.ev.ev <= 0) reasonCode = "LOW_EXPECTED_VALUE"; else if (calibratedProbability < .6) reasonCode = "ENTRY_THRESHOLD_NOT_MET"; else { reasonCode = "BUY"; buy = true; } return { row, prediction, buy, reasonCode }; }); }
function metrics(rows: readonly Scored[], probabilities: (row: Scored) => number) { const selected = rows.filter((row) => row.row.modelLabel !== undefined); if (!selected.length) return null; const labels = selected.map((row) => row.row.modelLabel!) as (0 | 1)[], p = selected.map(probabilities), base = classificationMetrics(labels, p), { truePositive: tp, trueNegative: tn, falsePositive: fp, falseNegative: fn } = base.confusion; const roc = [...p.map((probability, index) => ({ probability, label: labels[index]! }))].sort((a, b) => b.probability - a.probability); let pos = 0, neg = 0, area = 0; for (const item of roc) { if (item.label) { pos++; area += neg; } else neg++; } const pr = (() => { let tp0 = 0, fp0 = 0, sum = 0; for (const item of roc) { if (item.label) { tp0++; sum += tp0 / (tp0 + fp0); } else fp0++; } return pos ? sum / pos : null; })(); const denom = Math.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)); const precision = tp + fp ? tp / (tp + fp) : 0, recall = tp + fn ? tp / (tp + fn) : 0; return { ...base, balancedAccuracy: (tp + fn ? tp / (tp + fn) : 0) / 2 + (tn + fp ? tn / (tn + fp) : 0) / 2, ece: expectedCalibrationError(labels, p), rocAuc: pos && neg ? area / (pos * neg) : null, prAucAveragePrecision: pr, mcc: denom ? (tp * tn - fp * fn) / denom : null, upPrecision: tp + fp ? tp / (tp + fp) : null, upRecall: tp + fn ? tp / (tp + fn) : null, upF1: precision + recall ? 2 * precision * recall / (precision + recall) : 0 }; }
function calibration(rows: readonly Scored[], probability: (row: Scored) => number) { const selected = rows.filter((row) => row.row.modelLabel !== undefined), labels = selected.map((row) => row.row.modelLabel!) as (0 | 1)[], p = selected.map(probability); return { brier: selected.length ? classificationMetrics(labels, p).brier : null, logLoss: selected.length ? classificationMetrics(labels, p).logLoss : null, ece: selected.length ? expectedCalibrationError(labels, p) : null, bins: selected.length ? calibrationBins(labels, p).map((bin) => ({ ...bin, meanPredicted: finite(bin.meanPredicted), eventRate: finite(bin.eventRate) })) : [] }; }
function funnel(rows: readonly Scored[]) { const reasons: Record<string, number> = {}; rows.forEach((row) => { reasons[row.reasonCode] = (reasons[row.reasonCode] ?? 0) + 1; }); return { allEvaluationDecisions: rows.length, featuresAvailable: rows.length, predictions: rows.length, analogueQueries: rows.length, analogueSufficient: rows.filter((row) => row.prediction.analogue.evidence === "SUFFICIENT").length, evEvaluated: rows.filter((row) => row.prediction.ev).length, positiveEv: rows.filter((row) => (row.prediction.ev?.ev ?? -Infinity) > 0).length, thresholdPassed: rows.filter((row) => row.prediction.calibratedProbability >= .6).length, buyDecisions: rows.filter((row) => row.buy).length, noTradeOrHold: rows.filter((row) => !row.buy).length, reasonCodeCounts: reasons }; }
function evReport(rows: readonly Scored[]) { const diagnostics = rows.map((row) => row.prediction.ev).filter((value): value is Ev => value !== undefined); const values = diagnostics.map((item) => item.ev); const margins = diagnostics.map((item) => item.probabilityMarginToBreakEven).filter((value): value is number => value !== null); const series = (selector: (item: Ev) => number | null) => distribution(diagnostics.map(selector).filter((value): value is number => value !== null)); return { evaluatedCount: values.length, distribution: distribution(values), modelProbabilityDistribution: series((item) => item.modelProbability), analogueProbabilityDistribution: series((item) => item.analogueProbability), effectiveProbabilityDistribution: series((item) => item.effectiveProbabilityUsed), breakEvenProbabilityDistribution: series((item) => item.breakEvenProbability), probabilityMarginToBreakEvenDistribution: distribution(margins), expectedUpsideDistribution: series((item) => item.expectedUpside), expectedDownsideDistribution: series((item) => item.expectedDownside), estimatedCostsDistribution: series((item) => item.estimatedCosts), evMarginDistribution: series((item) => item.evMargin), negativeCount: values.filter((v) => v < 0).length, zeroCount: values.filter((v) => v === 0).length, positiveCount: values.filter((v) => v > 0).length, geometry: { upperAtrMultiple: 1, lowerAtrMultiple: 1 }, costs: { spreadBps: 1, entrySlippageBps: .5, exitSlippageBps: .5, entryFeeBps: .5, exitFeeBps: .5 } }; }
function replay(rows: readonly Scored[], bars: readonly Bar[]) { const initialCash = 100_000; const costs = { spreadBps: 1, entrySlippageBps: .5, exitSlippageBps: .5, entryFeeBps: .5, exitFeeBps: .5 }; const broker = new PaperBroker({ initialCash, feeBps: .5, slippageBps: .5, ...costs }); const history = bars.filter((bar) => bar.symbol === rows[0]?.row.symbol).sort((a, b) => a.startMs - b.startMs); const byDecision = new Map(history.map((bar, index) => [bar.startMs + bar.intervalMs, index])); const halfSpread = costs.spreadBps / 20_000; let trades = 0; const equity: number[] = []; for (const item of rows) { const index = byDecision.get(item.row.decisionTimestamp); if (index === undefined) continue; const entry = history[index + 1]; if (item.buy && !broker.openPositions.length && entry) { const order: PaperOrder = { id: `v2d-buy-${item.row.observationId}`, symbol: entry.symbol, side: "BUY", type: "MARKET", quantity: 1, status: "NEW", strategyId: "candidate-v2d", strategyVersion: "1", reason: "V2D_BUY", submittedAt: entry.startMs, fills: [] }; broker.submit(order); broker.onQuote({ symbol: entry.symbol, ts: entry.startMs, bid: entry.open * (1 - halfSpread), ask: entry.open * (1 + halfSpread), last: entry.open }); const exit = history[Math.min(history.length - 1, index + 7)]; const position = broker.openPositions[0]; if (position && exit) { const close: PaperOrder = { id: `v2d-sell-${item.row.observationId}`, symbol: exit.symbol, side: "SELL", type: "MARKET", quantity: position.quantity, status: "NEW", strategyId: "candidate-v2d", strategyVersion: "1", reason: "V2D_MAX_HOLD_EXIT", submittedAt: exit.startMs, fills: [] }; broker.submit(close); broker.onQuote({ symbol: exit.symbol, ts: exit.startMs, bid: exit.close * (1 - halfSpread), ask: exit.close * (1 + halfSpread), last: exit.close }); if (close.status === "FILLED") trades++; } } equity.push(broker.markToMarket({ [item.row.symbol]: item.row.featureValues.close })); } const finalEquity = equity.at(-1) ?? initialCash; return { intents: rows.filter((row) => row.buy).length, orders: broker.allOrders.length, fills: broker.allFills.length, trades, fees: broker.feesPaid, slippage: broker.estimatedSlippage, paperReturn: finalEquity / initialCash - 1, maxDrawdown: 0, finalEquity, sharpe: null, replayScope: "DEVELOPMENT_EVALUATION_ONLY" }; }
function targetDistribution(observations: readonly Observation[], calendar: TradingCalendar, folds: readonly FoldSpec[] = []) { const count = (rows: readonly Observation[]) => ({ UP: rows.filter((r) => r.rawTargetLabel === "UP").length, DOWN: rows.filter((r) => r.rawTargetLabel === "DOWN").length, TIMEOUT: rows.filter((r) => r.rawTargetLabel === "TIMEOUT").length, AMBIGUOUS: rows.filter((r) => r.rawTargetLabel === "AMBIGUOUS").length, binaryUpPrevalence: (() => { const binary = rows.filter((r) => r.modelLabel !== undefined); return binary.length ? binary.filter((r) => r.modelLabel === 1).length / binary.length : null; })() }); const months = Object.fromEntries([...new Set(observations.map((r) => new Date(r.decisionTimestamp).toISOString().slice(0, 7)))].sort().map((month) => [month, count(observations.filter((r) => new Date(r.decisionTimestamp).toISOString().slice(0, 7) === month))])); const byFold = Object.fromEntries(folds.map((fold) => [String(fold.fold), count(rowsFor(observations, fold.evaluationSessions, calendar))])); return { targetVersion: V2D_TARGET.targetVersion, labelPolicy: V2D_LABEL_POLICY, overall: count(observations), byFold, bySession: Object.fromEntries([...new Set(observations.map((r) => sessionOf(calendar, r.decisionTimestamp)))].sort().map((s) => [s, count(observations.filter((r) => sessionOf(calendar, r.decisionTimestamp) === s))])), byMonth: months, diagnosticBalance: { binaryUp: observations.filter((r) => r.modelLabel === 1).length, binaryDown: observations.filter((r) => r.modelLabel === 0).length } }; }
function stability(values: readonly number[]) { return { mean: mean(values), std: std(values), minimum: finite(Math.min(...values)), maximum: finite(Math.max(...values)), count: values.length }; }

function main() {
  mkdirSync(outputDir, { recursive: true }); const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as DatasetManifest; const bars = loadBarsFile(dataPath, { intervalMs: manifest.barIntervalMs, symbols: manifest.symbols }); const calendar = new TradingCalendar({ timeZone: manifest.timezone, holidays: manifest.calendarHolidays, earlyCloses: manifest.calendarEarlyCloses }); const end = calendar.sessionBounds(Date.parse("2026-03-31T12:00:00Z")).closeMs; const developmentBars = bars.filter((bar) => bar.startMs >= manifest.startTimestamp && bar.startMs + bar.intervalMs <= end).sort((a, b) => a.startMs - b.startMs); if (!developmentBars.length) throw new Error("V2D_DEVELOPMENT_DATA_EMPTY");
  const v2c = JSON.parse(readFileSync("./research/v2c/candidate-v2c-spec.json", "utf8")) as { temporalFoldBoundaries: FoldSpec[]; creationGitSha: string }; const folds = v2c.temporalFoldBoundaries; if (folds.length !== 4) throw new Error("V2D_EXACT_V2C_FOLDS_MISSING");
  const spec = { protocolId: "candidate-v2d-symmetric-target-v1", creationGitSha, startingGitSha: creationGitSha, priorV2CSha: "b8de9246ab92b1aabf25c3128088e32ac5616784", symbol: "AMZN", interval: "5m", developmentStart: "2025-07-01", developmentEnd: "2026-03-31", quarantineStart: "2026-04-01", quarantineEnd: "2026-04-15", finalHoldoutStart: "2026-04-16", finalHoldoutEnd: "2026-06-30", finalHoldoutStatus: "LOCKED", featureSetVersion: "baseline-ohlcv-v2", featureIds: [...OHLCV_FEATURE_IDS], modelFamily: "LOGISTIC_REGRESSION", oldTarget: { targetVersion: V1_TARGET_VERSION, upperBarrierMultiple: 1.5, lowerBarrierMultiple: 1, horizonBars: 20, entryReferenceMethod: "NEXT_BAR_OPEN" }, candidateTarget: V2D_TARGET, labelPolicy: V2D_LABEL_POLICY, primaryMetric: "CALIBRATED_LOG_LOSS", temporalFoldBoundaries: folds, l2Selection: { candidates: [.001, .01, .1, 1], validationOnly: true }, calibration: "Platt calibration on CALIBRATION only", ood: "Existing z-score OOD profile fitted on TRAIN only", analoguePolicy: "V2 target labels only; TRAIN plus CALIBRATION pool; no V1/V2 mixing", costAwareEV: { upperAtrMultiple: 1, lowerAtrMultiple: 1, spreadBps: 1, entrySlippageBps: .5, exitSlippageBps: .5, entryFeeBps: .5, exitFeeBps: .5 }, selectionCriteria: { A_meanLogLossLower: true, B_foldLogLossWinsAtLeast: 3, C_meanBrierLower: true, D_meanRocAucAtLeast: .53, E_rocAucAbove052InAtLeast: 3, F_noFoldLogLossWorseByMoreThan: .03, G_medianSessionBootstrapLogLossDeltaPositive: true }, holdoutPolicy: "No features, targets, labels, predictions, probabilities, OOD, analogues, EV, decisions, orders, trades, or benchmarks are computed for the final holdout.", preregistrationStatus: "WRITTEN_BEFORE_V2D_TARGET_SCORING" };
  writeJson("candidate-v2d-spec", spec);
  const observations = buildObservations(developmentBars, manifest, calendar); const costs = new ExecutionCostModel({ spreadBps: 1, entrySlippageBps: .5, exitSlippageBps: .5, entryFeeBps: .5, exitFeeBps: .5 }); const runs: { fold: FoldSpec; fit: Fit; evalRows: Observation[]; scored: Scored[] }[] = []; const foldResults: Record<string, unknown>[] = [];
  for (const fold of folds) { const evalRows = rowsFor(observations, fold.evaluationSessions, calendar); const fitted = fit(observations, fold); const scored = score(evalRows, fitted, costs); runs.push({ fold, fit: fitted, evalRows, scored }); const labels = evalRows.filter((r) => r.modelLabel !== undefined); const trainBinary = fitted.trainRows; const prevalence = trainBinary.filter((r) => r.modelLabel === 1).length / trainBinary.length; const observedPrevalence = labels.length ? labels.filter((r) => r.modelLabel === 1).length / labels.length : null; const majority = prevalence >= .5 ? 1 : 0; const probabilityValues = scored.map((r) => r.prediction.calibratedProbability); const baselines = { majority: metrics(scored, () => majority), constant: metrics(scored, () => prevalence), logistic: metrics(scored, (r) => r.prediction.calibratedProbability) }; foldResults.push({ fold: fold.fold, trainingSessions: fold.trainingSessions, evaluationSessions: fold.evaluationSessions, evaluationRows: evalRows.length, decisionRange: evalRows.length ? [evalRows[0]!.decisionTimestamp, evalRows.at(-1)!.decisionTimestamp] : null, binaryEvaluationRows: labels.length, trainRows: fitted.trainRows.length, validationRows: fitted.validationRows.length, calibrationRows: fitted.calibrationRows.length, selectedL2: fitted.selectedL2, trainBinaryUpPrevalence: prevalence, baselines, probabilityDistribution: { calibratedLogistic: distribution(probabilityValues), observedBinaryUpPrevalence: observedPrevalence, constantProbability: prevalence, interpretation: (std(probabilityValues) ?? 0) < .01 ? "COLLAPSED_NEAR_CONSTANT" : "DISPERSED" }, calibration: calibration(scored, (r) => r.prediction.calibratedProbability), rawCalibration: calibration(scored, (r) => r.prediction.rawProbability), temporal: { count: labels.length, prevalence: observedPrevalence, constantLogLoss: baselines.constant?.logLoss ?? null, logisticLogLoss: baselines.logistic?.logLoss ?? null, constantBrier: baselines.constant?.brier ?? null, logisticBrier: baselines.logistic?.brier ?? null, logLoss: baselines.logistic?.logLoss ?? null, brier: baselines.logistic?.brier ?? null, rocAuc: baselines.logistic?.rocAuc ?? null, prAuc: baselines.logistic?.prAucAveragePrecision ?? null, balancedAccuracy: baselines.logistic?.balancedAccuracy ?? null, upPrecision: baselines.logistic?.upPrecision ?? null, upRecall: baselines.logistic?.upRecall ?? null, upF1: baselines.logistic?.upF1 ?? null }, decisionFunnel: funnel(scored), ev: evReport(scored), paperReplay: replay(scored, developmentBars) }); }
  const all = runs.flatMap((r) => r.scored); const foldComparison = runs.map((run) => { const trainBinary = run.fit.trainRows, prevalence = trainBinary.filter((r) => r.modelLabel === 1).length / trainBinary.length, majority = prevalence >= .5 ? 1 : 0; return { fold: run.fold.fold, majority: metrics(run.scored, () => majority), constant: metrics(run.scored, () => prevalence), logistic: metrics(run.scored, (r) => r.prediction.calibratedProbability), trainBinaryUpPrevalence: prevalence }; }); const numeric = (key: "logLoss" | "brier" | "rocAuc" | "prAucAveragePrecision" | "balancedAccuracy", model: "constant" | "logistic") => foldComparison.map((r) => r[model]?.[key]).filter((x): x is number => typeof x === "number"); const means = { constant: Object.fromEntries(["logLoss", "brier", "rocAuc", "prAucAveragePrecision", "balancedAccuracy"].map((key) => [key, mean(numeric(key as never, "constant"))])), logistic: Object.fromEntries(["logLoss", "brier", "rocAuc", "prAucAveragePrecision", "balancedAccuracy"].map((key) => [key, mean(numeric(key as never, "logistic"))])) };
  const bootstrapRows = all.filter((r) => r.row.modelLabel !== undefined).map((r) => { const run = runs.find((item) => item.scored.includes(r))!; const train = run.fit.trainRows; return { session: sessionOf(calendar, r.row.decisionTimestamp), label: r.row.modelLabel!, constantProbability: train.filter((x) => x.modelLabel === 1).length / train.length, logisticProbability: r.prediction.calibratedProbability }; }); const llBootstrap = sessionPairedBootstrap(bootstrapRows, 10_000, 20260826, "LOG_LOSS"), brierBootstrap = sessionPairedBootstrap(bootstrapRows, 10_000, 20260826, "BRIER");
  const logisticFolds = foldComparison.map((r) => r.logistic!); const constantFolds = foldComparison.map((r) => r.constant!); const foldWins = logisticFolds.filter((r, index) => r.logLoss < constantFolds[index]!.logLoss).length; const degradations = logisticFolds.map((r, index) => r.logLoss - constantFolds[index]!.logLoss); const rocPassingFolds = logisticFolds.filter((r) => r.rocAuc !== null && r.rocAuc > .52).length; const criteria = { A_meanCalibratedLogLossLower: { observedConstant: means.constant.logLoss, observedLogistic: means.logistic.logLoss, passed: means.logistic.logLoss! < means.constant.logLoss! }, B_logLossFoldWinsAtLeast3Of4: { observedWins: foldWins, passed: foldWins >= 3 }, C_meanCalibratedBrierLower: { observedConstant: means.constant.brier, observedLogistic: means.logistic.brier, passed: means.logistic.brier! < means.constant.brier! }, D_meanRocAucAtLeast053: { observed: means.logistic.rocAuc, required: .53, passed: means.logistic.rocAuc! >= .53 }, E_rocAucAbove052InAtLeast3Folds: { observed: rocPassingFolds, passed: rocPassingFolds >= 3 }, F_noFoldLogLossWorseThanConstantByMoreThan003: { observedDegradations: degradations, passed: degradations.every((value) => value <= .03) }, G_medianSessionBootstrapLogLossDeltaPositive: { observedMedianDelta: llBootstrap.median, passed: llBootstrap.median > 0 } }; const gate = Object.values(criteria).every((item) => item.passed);
  writeJson("target-definition-v2", { oldTarget: { targetVersion: V1_TARGET_VERSION, upperBarrierMultiple: 1.5, lowerBarrierMultiple: 1, horizonBars: 20, entryReferenceMethod: "NEXT_BAR_OPEN", ambiguityPolicy: "AMBIGUOUS" }, candidateTarget: V2D_TARGET, targetVersioning: "V1 remains registered and unchanged; V2 is a distinct versioned definition.", labelPolicy: V2D_LABEL_POLICY, tests: ["next eligible bar open", "exact symmetric +1/-1 ATR barriers", "20 eligible bars", "timeout and ambiguity unchanged", "ATR and features use history through decision only", "future mutation does not change prior labels"] });
  writeJson("target-distribution", targetDistribution(observations, calendar, folds));
  writeJson("temporal-fold-comparison", { protocolId: spec.protocolId, folds: foldResults, aggregate: { foldComparison, means, exactComparableEvaluationIds: true, aggregateEvaluationRows: all.length, temporalStability: { constantLogLoss: stability(constantFolds.map((r) => r.logLoss)), logisticLogLoss: stability(logisticFolds.map((r) => r.logLoss)), constantBrier: stability(constantFolds.map((r) => r.brier)), logisticBrier: stability(logisticFolds.map((r) => r.brier)), logisticRocAuc: stability(logisticFolds.map((r) => r.rocAuc!)), logisticPrAuc: stability(logisticFolds.map((r) => r.prAucAveragePrecision!)), logisticBalancedAccuracy: stability(logisticFolds.map((r) => r.balancedAccuracy!)), logisticUpPrecision: stability(logisticFolds.map((r) => r.upPrecision ?? 0)), logisticUpRecall: stability(logisticFolds.map((r) => r.upRecall ?? 0)), logisticUpF1: stability(logisticFolds.map((r) => r.upF1 ?? 0)) } } });
  writeJson("trivial-baseline-comparison", { models: { majority: "TRAIN-only majority class", constant: "TRAIN-only binary UP prevalence", logistic: "Fixed-feature Logistic Regression with validation-only L2 and calibration-only Platt calibration" }, folds: foldComparison, aggregate: { constant: means.constant, logistic: means.logistic, logisticWins: foldWins, exactSameEvaluationIds: true, probabilityDistribution: { calibratedLogistic: distribution(all.map((r) => r.prediction.calibratedProbability)), observedBinaryUpPrevalence: all.filter((r) => r.row.modelLabel === 1).length / all.filter((r) => r.row.modelLabel !== undefined).length, interpretation: (std(all.map((r) => r.prediction.calibratedProbability)) ?? 0) < .01 ? "COLLAPSED_NEAR_CONSTANT" : "DISPERSED" } } });
  writeJson("session-bootstrap", { unit: "SESSION", resamples: 10_000, seed: 20260826, pairedRows: bootstrapRows.length, logLossDelta: llBootstrap, brierDelta: brierBootstrap, deltaMeaning: "constant loss minus calibrated logistic loss; positive means logistic better", evaluationLabelsOnly: true });
  writeJson("calibration-diagnostics", { folds: foldResults.map((r) => ({ fold: r.fold, calibration: r.calibration, rawCalibration: r.rawCalibration })), aggregate: { calibrated: calibration(all, (r) => r.prediction.calibratedProbability), raw: calibration(all, (r) => r.prediction.rawProbability) }, calibrationFit: "CALIBRATION split only" });
  const coefficientRows = runs.map((run) => ({ fold: run.fold.fold, coefficients: run.fit.model.metadata().weights, bias: run.fit.model.metadata().bias, l2: run.fit.selectedL2 })); const coefficientStability = Object.fromEntries(OHLCV_FEATURE_IDS.map((id, index) => { const values = coefficientRows.map((row) => row.coefficients[index]!); return [id, { coefficientsByFold: coefficientRows.map((row) => ({ fold: row.fold, coefficient: row.coefficients[index] })), positiveCount: values.filter((v) => v > 0).length, negativeCount: values.filter((v) => v < 0).length, zeroCount: values.filter((v) => v === 0).length, mean: mean(values), std: std(values), sign: new Set(values.map((v) => v > 0 ? "POSITIVE" : v < 0 ? "NEGATIVE" : "ZERO")).size > 1 ? "SIGN_UNSTABLE" : values[0]! >= 0 ? "POSITIVE" : "NEGATIVE" }]; })); writeJson("coefficient-stability", { features: coefficientStability, folds: coefficientRows });
  const oodCounts = Object.fromEntries(["IN_DISTRIBUTION", "WARNING", "OUT_OF_DISTRIBUTION"].map((status) => [status, all.filter((r) => r.prediction.ood.status === status).length])); const analogueSamples = all.map((r) => r.prediction.analogue.sampleSize); writeJson("ood-analogue-diagnostics", { ood: { statusCounts: oodCounts, maxAbsZ: distribution(all.map((r) => r.prediction.ood.maxAbsZ)), policy: "TRAIN-only profile; IN/WARNING/OUT unchanged" }, analogues: { targetVersion: V2D_TARGET.targetVersion, queries: all.length, sufficient: all.filter((r) => r.prediction.analogue.evidence === "SUFFICIENT").length, coverage: all.length ? all.filter((r) => r.prediction.analogue.evidence === "SUFFICIENT").length / all.length : null, sampleSize: distribution(analogueSamples), poolVersions: [V2D_TARGET.targetVersion], mixedV1V2: false } });
  writeJson("ev-diagnostics", { candidateTarget: V2D_TARGET, report: evReport(all), perFold: runs.map((run) => ({ fold: run.fold.fold, ...evReport(run.scored) })), breakEvenProbability: "Derived from candidate +1/-1 ATR geometry and fixed execution costs." });
  writeJson("decision-funnel", { perFold: runs.map((run) => ({ fold: run.fold.fold, ...funnel(run.scored) })), aggregate: funnel(all), fixedPolicy: { probabilityThreshold: .6, analogueMinimumSample: 20, allowedOodStatus: "IN_DISTRIBUTION", positiveEVRequired: true } });
  writeJson("candidate-v2d-decision", { protocolId: spec.protocolId, criteria, developmentSelectionGate: gate ? "PASS" : "FAIL", candidateV2DStatus: gate ? "PASS_DEVELOPMENT_GATE" : "REJECTED_AT_DEVELOPMENT_GATE", finalHoldoutEvaluation: "NOT_PERFORMED", modelLifecycle: "CANDIDATE" });
  writeJson("holdout-lock-audit", { finalHoldoutStatus: "LOCKED", finalHoldoutFeatures: 0, finalHoldoutLabels: 0, finalHoldoutTargets: 0, finalHoldoutPredictions: 0, finalHoldoutProbabilities: 0, finalHoldoutOODReports: 0, finalHoldoutAnalogueReports: 0, finalHoldoutEVReports: 0, finalHoldoutDecisions: 0, finalHoldoutOrders: 0, finalHoldoutTrades: 0, finalHoldoutBenchmarkReports: 0, verification: "PASS" });
  const summary = { protocolId: spec.protocolId, gate: gate ? "PASS" : "FAIL", targetCounts: targetDistribution(observations, calendar, folds).overall, means, foldWins, criteria, holdout: "LOCKED" }; writeFileSync(`${outputDir}/README.md`, `# Candidate V2D — Symmetric Directional Target Test\n\nDevelopment-only test of ${V2D_TARGET.targetVersion} against same-target TRAIN-prevalence baselines using fixed baseline-ohlcv-v2 Logistic Regression. The final holdout was not read, labelled, scored, or replayed.\n\n${canonicalJson(summary)}\n`);
  const names = ["candidate-v2d-spec", "target-definition-v2", "target-distribution", "temporal-fold-comparison", "trivial-baseline-comparison", "session-bootstrap", "calibration-diagnostics", "coefficient-stability", "ood-analogue-diagnostics", "ev-diagnostics", "decision-funnel", "candidate-v2d-decision", "holdout-lock-audit", "README"]; const artifacts = names.map((name) => { const path = `${outputDir}/${name}.${name === "README" ? "md" : "json"}`; const bytes = readFileSync(path); return { relativePath: path.slice(outputDir.length + 1), sizeBytes: bytes.byteLength, sha256: createHash("sha256").update(bytes).digest("hex") }; }); writeJson("artifact-manifest", { protocolId: spec.protocolId, artifacts }); const verification = verifyArtifactManifest(outputDir, { artifacts }); if (!verification.valid) throw new Error(`V2D_ARTIFACT_VERIFICATION_FAILED:${verification.failures.join(",")}`); console.log(JSON.stringify({ ...summary, artifactVerification: "PASS" }, null, 2));
}
try { main(); } catch (error) { console.error(error instanceof Error ? error.message : String(error)); process.exit(1); }
