export type MasteryLevel = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
export interface KnowledgeEntry { id: string; title: string; category: string; level: MasteryLevel; definition: string; whyItMatters: string; formula?: string; commonMistakes: readonly string[]; relatedConceptIds: readonly string[]; softwareModules: readonly string[]; researchSourceSection: string; }

/** Paraphrased, structured reference entries; this is educational content, not a decision-maker. */
export const masteryEntries: readonly KnowledgeEntry[] = [
  { id: "bid-ask-spread", title: "Bid, ask and spread", category: "Market Foundations", level: 1, definition: "The bid is the highest displayed buying price, the ask is the lowest displayed selling price, and the spread is their difference.", whyItMatters: "A strategy must use executable prices and include the spread in cost estimates.", formula: "spread = ask - bid", commonMistakes: ["Using last trade as an executable buy price", "Ignoring spread in a backtest"], relatedConceptIds: ["liquidity", "slippage"], softwareModules: ["src/domain.ts", "src/broker.ts", "src/features.ts"], researchSourceSection: "Markets, instruments, data and microstructure" },
  { id: "realised-volatility", title: "Realised volatility", category: "Statistics", level: 4, definition: "A dispersion estimate computed from observed returns over a defined lookback and sampling interval.", whyItMatters: "Volatility affects sizing, regime classification, costs and the scale of expected outcomes.", formula: "annualised volatility = stdev(period returns) × sqrt(periods per year)", commonMistakes: ["Hard-coding a one-minute annualisation factor", "Treating volatility as direction"], relatedConceptIds: ["risk-sizing", "volatility-regime"], softwareModules: ["src/features.ts", "src/metrics.ts"], researchSourceSection: "Features are measurements, not magic signals" },
  { id: "maximum-drawdown", title: "Maximum drawdown", category: "Risk", level: 5, definition: "The largest peak-to-trough decline in an equity sequence.", whyItMatters: "A strategy can have positive return while exposing the account to unacceptable loss or recovery time.", formula: "drawdown = (high-water mark - equity) / high-water mark", commonMistakes: ["Measuring from the starting balance instead of the high-water mark", "Ignoring drawdown duration"], relatedConceptIds: ["position-sizing", "expected-shortfall"], softwareModules: ["src/metrics.ts", "src/risk.ts", "src/engine.ts"], researchSourceSection: "Backtesting, simulation, execution and risk" },
  { id: "look-ahead-bias", title: "Look-ahead bias", category: "Backtesting", level: 7, definition: "Using information that was not available at the decision timestamp when constructing a feature, target, or fill.", whyItMatters: "It can create apparently profitable results that cannot be reproduced prospectively.", commonMistakes: ["Fitting transforms on the full dataset", "Executing on a bar close used to create the signal"], relatedConceptIds: ["purged-split", "point-in-time-data"], softwareModules: ["src/research.ts", "src/backtest.ts", "tests/core.test.ts"], researchSourceSection: "Common reasons backtests lie" },
  { id: "transaction-costs", title: "Transaction costs", category: "Execution", level: 6, definition: "Fees, spread, slippage and liquidity costs incurred when simulated orders execute.", whyItMatters: "Small gross edges can disappear after realistic execution assumptions.", formula: "net result = gross result - fees - spread cost - slippage", commonMistakes: ["Filling every order at candle close", "Allowing limit fills beyond the limit price"], relatedConceptIds: ["bid-ask-spread", "partial-fills"], softwareModules: ["src/broker.ts", "src/metrics.ts"], researchSourceSection: "Realistic V1 fill simulation" },
  { id: "purged-split", title: "Purged time-series split", category: "Machine Learning", level: 10, definition: "A chronological split that removes training examples whose forward target window crosses into a later validation or test partition.", whyItMatters: "Overlapping forward labels can otherwise leak future partition information into training.", commonMistakes: ["Assuming chronological order alone prevents leakage", "Using random shuffling for sequential data"], relatedConceptIds: ["look-ahead-bias", "walk-forward"], softwareModules: ["src/research.ts"], researchSourceSection: "Machine learning and time-series validation" },
  { id: "no-trade", title: "No-trade decision", category: "Professional Process", level: 12, definition: "An explicit outcome when evidence, data quality, regime fit, expected value, or risk controls do not justify a paper order.", whyItMatters: "A research system should not force an action when uncertainty is high.", commonMistakes: ["Treating every signal as an order", "Hiding rejected opportunities from analysis"], relatedConceptIds: ["evidence-quality", "risk-limits"], softwareModules: ["src/risk.ts", "src/strategy.ts"], researchSourceSection: "Final decision engine" }
];

export function getKnowledgeEntry(id: string) { return masteryEntries.find((entry) => entry.id === id); }
